/**
 * Tests for the ZIP-316 UA address classifier and deriveZcashTransferType.
 *
 * Test vectors for classifyZcashRecipient (non-UA cases) use real Zcash mainnet
 * addresses from the coin-bitcoin wallet-btc test suite.
 *
 * UA-with-Orchard vector: u1u2h4ce7e2cn3z4nzur95muq2dl4da9x8h8kdp2l80gm9nl9raj8zzpx79ycjnfvar4v5exea5pqr5y9qsnlp0cdunwf9yjjx5c4q7ar9
 * Source: firmware/app-zcash/tests/standalone/test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
 * Verified: generated by the Ledger Zcash firmware using orchard::keys and
 *   zcash_address::unified::Address::try_from_items([Receiver::Orchard(...)]),
 *   which produces an Orchard-only UA per ZIP-316.
 *
 * Note: raw.githubusercontent.com was unreachable during implementation
 *   (proxy not running). The ZIP-316 appendix-C test vectors from zcash/zips
 *   were not fetched. The Orchard-only UA above is the real vector used.
 */

import {
  classifyZcashRecipient,
  decodeUnifiedAddressTypecodes,
  deriveZcashTransferType,
  TYPECODE_ORCHARD,
  TYPECODE_SAPLING,
  TYPECODE_P2PKH,
} from "../address";

// ---------------------------------------------------------------------------
// Real Zcash mainnet addresses (sourced from existing coin-bitcoin test suite)
// ---------------------------------------------------------------------------

// t1 P2PKH — from wallet-btc/__tests__/utils.test.ts
const T1_ADDRESS = "t1b1Rbw2shhJkP6MCnCyxCPuyFedHrwKty8";

// Orchard-only UA — from firmware/app-zcash test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
// Generated by the Ledger Zcash device app (Orchard only, no transparent/Sapling receiver)
const UA_ORCHARD_ONLY =
  "u1u2h4ce7e2cn3z4nzur95muq2dl4da9x8h8kdp2l80gm9nl9raj8zzpx79ycjnfvar4v5exea5pqr5y9qsnlp0cdunwf9yjjx5c4q7ar9";

// ---------------------------------------------------------------------------
// classifyZcashRecipient — non-UA cases (do not require F4Jumble)
// ---------------------------------------------------------------------------

describe("classifyZcashRecipient — transparent addresses", () => {
  it("accepts a valid t1 P2PKH address as public", () => {
    expect(classifyZcashRecipient(T1_ADDRESS)).toEqual({ recipientType: "public" });
  });

  it("accepts a synthetic t3 P2SH address as public", () => {
    // t3 prefix, 35 chars total
    const t3addr = "t3fJZ5jYsyxDtvNrWBeoMbvJaQCj4JJgbgX";
    expect(classifyZcashRecipient(t3addr)).toEqual({ recipientType: "public" });
  });

  it("rejects a too-short t1 string as invalid", () => {
    expect(classifyZcashRecipient("t1short")).toEqual({ error: "invalid" });
  });
});

describe("classifyZcashRecipient — Sapling addresses", () => {
  it("rejects a zs1 Sapling address as sapling-unsupported", () => {
    // zs1 prefix — any Sapling address is sapling-unsupported regardless of content
    const zsAddr = "zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9slya";
    expect(classifyZcashRecipient(zsAddr)).toEqual({ error: "sapling-unsupported" });
  });

  it("treats the zs prefix case-insensitively", () => {
    const zsUpper = "ZS1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9slya";
    expect(classifyZcashRecipient(zsUpper)).toEqual({ error: "sapling-unsupported" });
  });
});

describe("classifyZcashRecipient — Sprout and garbage", () => {
  it("rejects a Sprout zc address as invalid", () => {
    expect(classifyZcashRecipient("zcU1Cd6zYyZCd2VJF8yKgmzjxdiiU1rgTTjEwoN1CGUWCziPkUTXUjXmX7TMqdMNsTfuiGN1jQoVN4kGxUR4sAPN4XZ7pxmy")).toEqual(
      { error: "invalid" },
    );
  });

  it("rejects empty string as invalid", () => {
    expect(classifyZcashRecipient("")).toEqual({ error: "invalid" });
  });

  it("rejects a Bitcoin address as invalid", () => {
    expect(classifyZcashRecipient("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4")).toEqual(
      { error: "invalid" },
    );
  });

  it("rejects arbitrary garbage as invalid", () => {
    expect(classifyZcashRecipient("not-a-zcash-address")).toEqual({ error: "invalid" });
  });

  it("rejects a u1-prefixed string that is not a valid bech32m UA as invalid", () => {
    expect(classifyZcashRecipient("u1invalidsuffixnotbech32")).toEqual({ error: "invalid" });
  });
});

// ---------------------------------------------------------------------------
// classifyZcashRecipient — Orchard UA (real firmware-generated vector)
// ---------------------------------------------------------------------------

describe("classifyZcashRecipient — Orchard Unified Address", () => {
  it("classifies a real Orchard-only UA as private", () => {
    // Real address generated by Ledger Zcash firmware (Orchard-only UA, no Sapling).
    // Source: app-zcash tests/standalone/test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
    expect(classifyZcashRecipient(UA_ORCHARD_ONLY)).toEqual({ recipientType: "private" });
  });

  it("decodeUnifiedAddressTypecodes returns [TYPECODE_ORCHARD] for the Orchard-only UA", () => {
    const typecodes = decodeUnifiedAddressTypecodes(UA_ORCHARD_ONLY);
    // The UA contains exactly one Orchard receiver (typecode 0x03)
    expect(typecodes).not.toBeNull();
    expect(typecodes).toContain(TYPECODE_ORCHARD);
    expect(typecodes).not.toContain(TYPECODE_SAPLING);
    expect(typecodes).not.toContain(TYPECODE_P2PKH);
  });

  // ZIP-316/librustzcash appendix-C test vectors were not fetched:
  // raw.githubusercontent.com was unreachable (proxy not running) during
  // implementation. Additional cross-validation against published vectors
  // should be added when network access is available.
  it.todo(
    "validate F4Jumble decode against ZIP-316 appendix-C published test vectors (network unavailable during impl)",
  );
});

// ---------------------------------------------------------------------------
// deriveZcashTransferType — full truth table
// ---------------------------------------------------------------------------

describe("deriveZcashTransferType — truth table", () => {
  it("public sender + public recipient = transparent", () => {
    expect(deriveZcashTransferType("public", "public")).toBe("transparent");
  });

  it("public sender + private recipient = transparent-to-shielded", () => {
    expect(deriveZcashTransferType("public", "private")).toBe("transparent-to-shielded");
  });

  it("private sender + public recipient = shielded-to-transparent", () => {
    expect(deriveZcashTransferType("private", "public")).toBe("shielded-to-transparent");
  });

  it("private sender + private recipient = shielded", () => {
    expect(deriveZcashTransferType("private", "private")).toBe("shielded");
  });

  it("public sender + undefined recipient = transparent", () => {
    expect(deriveZcashTransferType("public", undefined)).toBe("transparent");
  });

  it("private sender + undefined recipient = shielded (safe default)", () => {
    expect(deriveZcashTransferType("private", undefined)).toBe("shielded");
  });

  it("undefined sender + any recipient = transparent", () => {
    expect(deriveZcashTransferType(undefined, "public")).toBe("transparent");
    expect(deriveZcashTransferType(undefined, "private")).toBe("transparent-to-shielded");
    expect(deriveZcashTransferType(undefined, undefined)).toBe("transparent");
  });
});
