/**
 * Tests for the ZIP-316 UA address classifier and deriveZcashTransferType.
 *
 * Test vectors for classifyZcashRecipient (non-UA cases) use real Zcash mainnet
 * addresses from the coin-bitcoin wallet-btc test suite.
 *
 * UA-with-Orchard vector: u1u2h4ce7e2cn3z4nzur95muq2dl4da9x8h8kdp2l80gm9nl9raj8zzpx79ycjnfvar4v5exea5pqr5y9qsnlp0cdunwf9yjjx5c4q7ar9
 * Source: firmware/app-zcash/tests/standalone/test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
 * Verified: generated by the Ledger Zcash firmware using orchard::keys and
 *   zcash_address::unified::Address::try_from_items([Receiver::Orchard(...)]),
 *   which produces an Orchard-only UA per ZIP-316.
 */

import {
  classifyZcashRecipient,
  decodeUnifiedAddressTypecodes,
  deriveZcashTransferType,
  readCompactSize,
  TYPECODE_ORCHARD,
  TYPECODE_SAPLING,
  TYPECODE_P2PKH,
} from "../address";

// ---------------------------------------------------------------------------
// Real Zcash mainnet addresses (sourced from existing coin-bitcoin test suite)
// ---------------------------------------------------------------------------

// t1 P2PKH — from wallet-btc/__tests__/utils.test.ts
const T1_ADDRESS = "t1b1Rbw2shhJkP6MCnCyxCPuyFedHrwKty8";

// Orchard-only UA — from firmware/app-zcash test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
// Generated by the Ledger Zcash device app (Orchard only, no transparent/Sapling receiver)
const UA_ORCHARD_ONLY =
  "u1u2h4ce7e2cn3z4nzur95muq2dl4da9x8h8kdp2l80gm9nl9raj8zzpx79ycjnfvar4v5exea5pqr5y9qsnlp0cdunwf9yjjx5c4q7ar9";

// Transparent-only UA — a mainnet UA whose sole receiver is a P2PKH (typecode 0x00).
// Constructed per ZIP-316 (single 20-byte P2PKH receiver, F4Jumble + bech32m "u"),
// verified to decode to typecodes [0x00] via decodeUnifiedAddressTypecodes.
const UA_TRANSPARENT_ONLY = "u1fcd2t573p0qtf3sz7dft0rwtcmg5q9cxkr8l4c3reshlugr8pr2l5aeersajvcatx6e";

// ---------------------------------------------------------------------------
// classifyZcashRecipient — non-UA cases (do not require F4Jumble)
// ---------------------------------------------------------------------------

describe("classifyZcashRecipient — transparent addresses", () => {
  it("accepts a valid t1 P2PKH address as public", () => {
    expect(classifyZcashRecipient(T1_ADDRESS)).toEqual({
      recipientType: "public",
    });
  });

  it("accepts a synthetic t3 P2SH address as public", () => {
    // t3 prefix, 35 chars total
    const t3addr = "t3fJZ5jYsyxDtvNrWBeoMbvJaQCj4JJgbgX";
    expect(classifyZcashRecipient(t3addr)).toEqual({ recipientType: "public" });
  });

  it("rejects a too-short t1 string as invalid", () => {
    expect(classifyZcashRecipient("t1short")).toEqual({ error: "invalid" });
  });
});

describe("classifyZcashRecipient — Sapling addresses", () => {
  it("rejects a zs1 Sapling address as sapling-unsupported", () => {
    // zs1 prefix — any Sapling address is sapling-unsupported regardless of content
    const zsAddr = "zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9slya";
    expect(classifyZcashRecipient(zsAddr)).toEqual({
      error: "sapling-unsupported",
    });
  });

  it("treats the zs prefix case-insensitively", () => {
    const zsUpper =
      "ZS1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9slya";
    expect(classifyZcashRecipient(zsUpper)).toEqual({
      error: "sapling-unsupported",
    });
  });
});

describe("classifyZcashRecipient — Sprout and garbage", () => {
  it("rejects a Sprout zc address as invalid", () => {
    expect(
      classifyZcashRecipient(
        "zcU1Cd6zYyZCd2VJF8yKgmzjxdiiU1rgTTjEwoN1CGUWCziPkUTXUjXmX7TMqdMNsTfuiGN1jQoVN4kGxUR4sAPN4XZ7pxmy",
      ),
    ).toEqual({ error: "invalid" });
  });

  it("rejects empty string as invalid", () => {
    expect(classifyZcashRecipient("")).toEqual({ error: "invalid" });
  });

  it("rejects a Bitcoin address as invalid", () => {
    expect(classifyZcashRecipient("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4")).toEqual({
      error: "invalid",
    });
  });

  it("rejects arbitrary garbage as invalid", () => {
    expect(classifyZcashRecipient("not-a-zcash-address")).toEqual({
      error: "invalid",
    });
  });

  it("rejects a u1-prefixed string that is not a valid bech32m UA as invalid", () => {
    expect(classifyZcashRecipient("u1invalidsuffixnotbech32")).toEqual({
      error: "invalid",
    });
  });
});

// ---------------------------------------------------------------------------
// classifyZcashRecipient — Orchard UA (real firmware-generated vector)
// ---------------------------------------------------------------------------

describe("classifyZcashRecipient — Orchard Unified Address", () => {
  it("classifies a real Orchard-only UA as private", () => {
    // Real address generated by Ledger Zcash firmware (Orchard-only UA, no Sapling).
    // Source: app-zcash tests/standalone/test_pubkey_cmd.py REF_ORCHARD_ADDRESS_ACC_0
    expect(classifyZcashRecipient(UA_ORCHARD_ONLY)).toEqual({
      recipientType: "private",
    });
  });

  it("decodeUnifiedAddressTypecodes returns [TYPECODE_ORCHARD] for the Orchard-only UA", () => {
    const typecodes = decodeUnifiedAddressTypecodes(UA_ORCHARD_ONLY);
    // The UA contains exactly one Orchard receiver (typecode 0x03)
    expect(typecodes).not.toBeNull();
    expect(typecodes).toContain(TYPECODE_ORCHARD);
    expect(typecodes).not.toContain(TYPECODE_SAPLING);
    expect(typecodes).not.toContain(TYPECODE_P2PKH);
  });

  it("rejects a mixed-case UA as invalid (UAs are case-sensitive per ZIP-316)", () => {
    // Upper-case a single character of an otherwise valid UA. bech32m forbids
    // mixed-case strings, so this must not be normalised and accepted.
    const mixedCase = UA_ORCHARD_ONLY[0] + UA_ORCHARD_ONLY.slice(1).toUpperCase();
    expect(classifyZcashRecipient(mixedCase)).toEqual({ error: "invalid" });
    expect(decodeUnifiedAddressTypecodes(mixedCase)).toBeNull();
  });

  it.todo("validate F4Jumble decode against ZIP-316 appendix-C published test vectors");
});

describe("classifyZcashRecipient — transparent-only Unified Address", () => {
  it("classifies a UA with only a transparent (P2PKH) receiver as public", () => {
    // A transparent-only UA is not Sapling; it must not report sapling-unsupported.
    expect(classifyZcashRecipient(UA_TRANSPARENT_ONLY)).toEqual({
      recipientType: "public",
    });
  });

  it("decodeUnifiedAddressTypecodes returns [TYPECODE_P2PKH] for the transparent-only UA", () => {
    const typecodes = decodeUnifiedAddressTypecodes(UA_TRANSPARENT_ONLY);
    expect(typecodes).not.toBeNull();
    expect(typecodes).toContain(TYPECODE_P2PKH);
    expect(typecodes).not.toContain(TYPECODE_ORCHARD);
    expect(typecodes).not.toContain(TYPECODE_SAPLING);
  });
});

// ---------------------------------------------------------------------------
// readCompactSize — ZIP-316 CompactSize (Bitcoin varint) parser
// ---------------------------------------------------------------------------

describe("readCompactSize", () => {
  it("reads a single-byte value (< 0xfd)", () => {
    expect(readCompactSize(new Uint8Array([0x00]), 0)).toEqual({
      value: 0,
      offset: 1,
    });
    expect(readCompactSize(new Uint8Array([0x2b]), 0)).toEqual({
      value: 43,
      offset: 1,
    });
    expect(readCompactSize(new Uint8Array([0xfc]), 0)).toEqual({
      value: 0xfc,
      offset: 1,
    });
  });

  it("reads a 2-byte value (0xfd prefix, little-endian)", () => {
    // 0xfd 0x00 0x01 => 0x0100 = 256
    expect(readCompactSize(new Uint8Array([0xfd, 0x00, 0x01]), 0)).toEqual({
      value: 256,
      offset: 3,
    });
  });

  it("reads a 4-byte value (0xfe prefix, little-endian)", () => {
    // 0xfe 0x00 0x00 0x01 0x00 => 0x00010000 = 65536
    expect(readCompactSize(new Uint8Array([0xfe, 0x00, 0x00, 0x01, 0x00]), 0)).toEqual({
      value: 65536,
      offset: 5,
    });
  });

  it("honours the starting offset", () => {
    expect(readCompactSize(new Uint8Array([0xff, 0x2b]), 1)).toEqual({
      value: 43,
      offset: 2,
    });
  });

  it("returns null when the buffer is truncated", () => {
    expect(readCompactSize(new Uint8Array([]), 0)).toBeNull();
    // 0xfd needs 2 more bytes but only 1 is present
    expect(readCompactSize(new Uint8Array([0xfd, 0x00]), 0)).toBeNull();
  });

  it("rejects non-canonical encodings", () => {
    // 0xfd with a value < 0xfd should have used the single-byte form
    expect(readCompactSize(new Uint8Array([0xfd, 0x10, 0x00]), 0)).toBeNull();
    // 0xfe with a value < 0x10000 should have used the 2-byte form
    expect(readCompactSize(new Uint8Array([0xfe, 0x00, 0x01, 0x00, 0x00]), 0)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// deriveZcashTransferType — full truth table
// ---------------------------------------------------------------------------

describe("deriveZcashTransferType — truth table", () => {
  it("public sender + public recipient = transparent", () => {
    expect(deriveZcashTransferType("public", "public")).toBe("transparent");
  });

  it("public sender + private recipient = transparent-to-shielded", () => {
    expect(deriveZcashTransferType("public", "private")).toBe("transparent-to-shielded");
  });

  it("private sender + public recipient = shielded-to-transparent", () => {
    expect(deriveZcashTransferType("private", "public")).toBe("shielded-to-transparent");
  });

  it("private sender + private recipient = shielded", () => {
    expect(deriveZcashTransferType("private", "private")).toBe("shielded");
  });

  it("public sender + undefined recipient = transparent", () => {
    expect(deriveZcashTransferType("public", undefined)).toBe("transparent");
  });

  it("private sender + undefined recipient = shielded (safe default)", () => {
    expect(deriveZcashTransferType("private", undefined)).toBe("shielded");
  });

  it("undefined sender + any recipient = transparent", () => {
    expect(deriveZcashTransferType(undefined, "public")).toBe("transparent");
    expect(deriveZcashTransferType(undefined, "private")).toBe("transparent-to-shielded");
    expect(deriveZcashTransferType(undefined, undefined)).toBe("transparent");
  });

  it("ironwood sender + public recipient = ironwood-to-transparent", () => {
    expect(deriveZcashTransferType("ironwood", "public")).toBe("ironwood-to-transparent");
  });

  it("ironwood sender + private recipient = ironwood", () => {
    expect(deriveZcashTransferType("ironwood", "private")).toBe("ironwood");
  });

  it("ironwood sender + undefined recipient = ironwood (safe default)", () => {
    expect(deriveZcashTransferType("ironwood", undefined)).toBe("ironwood");
  });
});
