import { MODULAR_DRAWER_ADD_ACCOUNT_STEP } from "LLD/features/AddAccountDrawer/domain";

export const CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP = {
  ...MODULAR_DRAWER_ADD_ACCOUNT_STEP,
  DISCLAIMER: "CANTON_DISCLAIMER",
  CANTON_ONBOARD: "CANTON_ONBOARD",
} as const;

export type CantonModularDrawerAddAccountStep =
  (typeof CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP)[keyof typeof CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP];

export const CANTON_ADD_ACCOUNT_STEP_ORDER: CantonModularDrawerAddAccountStep[] = [
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.DISCLAIMER,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.CONNECT_YOUR_DEVICE,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.SCAN_ACCOUNTS,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.CANTON_ONBOARD,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.ACCOUNTS_ADDED,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.ACCOUNTS_WARNING,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.SELECT_ACCOUNT,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.EDIT_ACCOUNT_NAME,
  CANTON_MODULAR_DRAWER_ADD_ACCOUNT_STEP.FUND_ACCOUNT,
];
