export const MARKET_SCREEN_TEST_IDS = {
  screen: "market-screen",
  searchBar: "market-screen-search-bar",
  highlights: "market-screen-highlights",
  highlightCard: "market-screen-highlight-card",
  list: "market-screen-list",
  assetsSubHeader: "market-screen-assets-subheader",
  assetsFilterButton: "market-screen-assets-filter-button",
  assetsCategorySwitcher: "market-screen-assets-category-switcher",
  assetsFavoritesEmptyIcon: "market-screen-assets-favorites-empty-icon",
  assetsStocksEmpty: "market-screen-assets-stocks-empty",
  filtersDrawer: "market-screen-filters-drawer",
  filtersSortingList: "market-screen-filters-sorting-list",
  filtersTimeframeList: "market-screen-filters-timeframe-list",
  assetsSkeleton: "market-screen-assets-skeleton",
  assetsEmptySearch: "market-screen-assets-empty-search",
  assetsError: "market-screen-assets-error",
  assetsFooterSpinner: "market-screen-assets-footer-spinner",
} as const;
