export type SpeculosAppType = AppInfos;
export declare class AppInfos {
    readonly name: string;
    constructor(name: string);
    static readonly BITCOIN: AppInfos;
    static readonly INJECTIVE: AppInfos;
    static readonly APTOS: AppInfos;
    static readonly BITCOIN_TESTNET: AppInfos;
    static readonly DOGECOIN: AppInfos;
    static readonly ETHEREUM: AppInfos;
    static readonly ETHEREUM_SEPOLIA: AppInfos;
    static readonly ETHEREUM_CLASSIC: AppInfos;
    static readonly SOLANA: AppInfos;
    static readonly POLKADOT: AppInfos;
    static readonly TRON: AppInfos;
    static readonly RIPPLE: AppInfos;
    static readonly CARDANO: AppInfos;
    static readonly STELLAR: AppInfos;
    static readonly BITCOIN_CASH: AppInfos;
    static readonly ALGORAND: AppInfos;
    static readonly COSMOS: AppInfos;
    static readonly TEZOS: AppInfos;
    static readonly POLYGON: AppInfos;
    static readonly BNB_CHAIN: AppInfos;
    static readonly TON: AppInfos;
    static readonly NEAR: AppInfos;
    static readonly MULTIVERS_X: AppInfos;
    static readonly OSMOSIS: AppInfos;
    static readonly LS: AppInfos;
    static readonly EXCHANGE: AppInfos;
    static readonly CELO: AppInfos;
    static readonly LTC: AppInfos;
    static readonly KASPA: AppInfos;
    static readonly HEDERA: AppInfos;
    static readonly SUI: AppInfos;
    static readonly BASE: AppInfos;
    static readonly VECHAIN: AppInfos;
    static readonly ZCASH: AppInfos;
    static readonly ALEO: AppInfos;
    static readonly INTERNET_COMPUTER: AppInfos;
    static readonly VELORA: AppInfos;
    static readonly ONE_INCH: AppInfos;
    static readonly MINA: AppInfos;
    static readonly CONCORDIUM: AppInfos;
    static readonly CONCORDIUM_TESTNET: AppInfos;
    static readonly SEI: AppInfos;
}
//# sourceMappingURL=AppInfos.d.ts.map