/// <reference path="./node-shims.d.ts" />
import { writeFileSync } from "fs";
import { scopes, scopeNames } from "./scopes.ts";

const outputPath = ".github/labeler.yml";

function toYaml(labels: Record<string, readonly string[]>): string {
  return (
    Object.entries(labels)
      .map(([name, paths]) => `${name}:\n${paths.map(path => `  - ${path}`).join("\n")}`)
      .join("\n\n") + "\n"
  );
}

const labels = Object.fromEntries(scopeNames.map(name => [name, scopes[name].paths]));

writeFileSync(
  outputPath,
  [
    "# Generated by labeler.yml.ts — do not edit manually.",
    "# Run: pnpm generate:labeler",
    "",
    toYaml(labels),
  ].join("\n"),
);

console.log(`Wrote ${outputPath}`);
