/**
 * IPC contract between the ZCash renderer client, the Electron main process,
 * and the UtilityProcess that hosts the native Rust engine.
 *
 * The same shapes are used across both hops:
 *
 *     renderer  <-- ipcRenderer -->  main  <-- utility.parentPort -->  utility
 *
 * Everything here must be `structuredClone`-safe (no BigNumber, no functions,
 * no Buffer subclasses). Numeric amounts travel as strings in
 * {@link ShieldedSyncResultRaw}; BigNumber reconstruction happens client-side.
 *
 * --- Error reporting conventions ----
 *
 * Two flavours of methods live on this contract, with two different ways of
 * signalling failure. Stick to them when adding a new method so the utility
 * protocol stays uniform:
 *
 * 1. One-shot methods (e.g. {@link ZCASH_IPC.getChainTip}): the utility replies
 *    with either a success message (`chain-tip`) or a dedicated error message
 *    (`chain-tip-error`) at the top level of {@link UtilityOutboundMessage}.
 *    The main-process bridge resolves / rejects the pending `ipcMain.handle`
 *    promise accordingly. For a new one-shot method `foo`, add
 *    `{ type: "foo-result"; ... }` and `{ type: "foo-error"; ... }`.
 *
 * 2. Streaming methods (e.g. {@link ZCASH_IPC.startSync}): errors travel
 *    *inside* the {@link StreamEvent} union as `{ kind: "error" }`, never at
 *    the top level of {@link UtilityOutboundMessage}. The renderer is
 *    subscribed to the same `stream` channel anyway, so routing errors through
 *    the stream keeps the state machine in one place (a stream ends with
 *    `"complete"` or `"error"`, never both).
 */

import type { ShieldedSyncResultRaw } from "../types";

/** Unique per-subscription id, generated by the renderer client. */
export type RequestId = string;

// --- Renderer <-> Main (ipcRenderer.invoke / webContents.send) ---

/** Channel names -- centralized to keep renderer/main/utility in lock-step. */
export const ZCASH_IPC = {
  /** invoke -> number (chain tip height) */
  getChainTip: "zcash:getChainTip",
  /** invoke -> number (block height for a given timestamp) */
  findBlockHeight: "zcash:findBlockHeight",
  /** invoke -> void once the start-sync message has been posted to the utility. Chunks arrive on `stream`. */
  startSync: "zcash:startSync",
  /** invoke -> void. Propagates a cancel signal to the utility. */
  cancelSync: "zcash:cancelSync",
  /** webContents.send -> StreamEvent. Filter by requestId on the renderer side. */
  stream: "zcash:stream",
} as const;

export type ZcashIpcChannel = (typeof ZCASH_IPC)[keyof typeof ZCASH_IPC];

// --- Request payloads ---

export type GetChainTipArgs = {
  requestId: RequestId;
  grpcUrl: string;
};

export type FindBlockHeightArgs = {
  requestId: RequestId;
  grpcUrl: string;
  timestamp: number;
};

export type StartSyncArgs = {
  requestId: RequestId;
  grpcUrl: string;
  network: string;
  viewingKey: string;
  startBlockHeight: number;
  maxBatchSize: number;
};

export type CancelSyncArgs = {
  requestId: RequestId;
};

// --- Stream events (main -> renderer, utility -> main) ---

/**
 * Events emitted during a sync subscription. The renderer client filters them
 * by `requestId` and rehydrates `chunk.result` into a `ShieldedSyncResult`
 * with real `BigNumber` instances.
 */
export type StreamEvent =
  | { requestId: RequestId; kind: "chunk"; result: ShieldedSyncResultRaw }
  | { requestId: RequestId; kind: "complete" }
  | { requestId: RequestId; kind: "error"; message: string };

// --- Utility <-> Main (parentPort.postMessage) ---
//
// The utility-facing protocol is symmetric: the main process forwards the same
// `StartSyncArgs` / `CancelSyncArgs` / `GetChainTipArgs` shapes down the
// parentPort, tagged with a `type`. The utility replies with either a
// `chain-tip` (one-shot) or a `stream` event (sync loop).

export type UtilityInboundMessage =
  | { type: "get-chain-tip"; args: GetChainTipArgs }
  | { type: "find-block-height"; args: FindBlockHeightArgs }
  | { type: "start-sync"; args: StartSyncArgs }
  | { type: "cancel-sync"; args: CancelSyncArgs };

export type UtilityOutboundMessage =
  | { type: "chain-tip"; requestId: RequestId; height: number }
  | { type: "chain-tip-error"; requestId: RequestId; message: string }
  | { type: "block-height"; requestId: RequestId; height: number }
  | { type: "block-height-error"; requestId: RequestId; message: string }
  | { type: "stream"; event: StreamEvent };
