import { SEND_FLOW_STEP } from "./types";

test("sponsored steps exist", () => {
  expect(SEND_FLOW_STEP.FEE_PAYMENT).toBe("FEE_PAYMENT");
  expect(SEND_FLOW_STEP.SPONSORED_RENT_SIGNATURE).toBe("SPONSORED_RENT_SIGNATURE");
  expect(SEND_FLOW_STEP.SPONSORED_POLLING).toBe("SPONSORED_POLLING");
  expect(SEND_FLOW_STEP.SPONSORED_FAILURE).toBe("SPONSORED_FAILURE");
});
