import { Probot } from "probot";

/**
 * Auto close PR generated by smartling
 * @param app The Probot application.
 */
export function autoClose(app: Probot) {
  app.on(["pull_request.opened", "pull_request.reopened"], async context => {
    const { payload, octokit } = context;
    const repository = context.repo();
    const branch = payload.pull_request.head.ref;
    const login = payload.pull_request.user.login;

    if (
      repository.repo !== "ledger-live" ||
      login !== "ldg-smartling-sa" ||
      !/^smartling-(content-updated|translation-completed)-.+/.test(branch)
    ) {
      return;
    }

    const comment = context.issue({
      body: "This is smartling pull request created by @ldg-smartling-sa, it will be closed automatically.",
    });

    await octokit.issues.createComment(comment);
    await octokit.pulls.update({
      owner: repository.owner,
      repo: repository.repo,
      pull_number: payload.number,
      state: "closed",
    });
  });
}
