export const COPY = {
  rowTitle: "Generic awareness modal (QA)",
  rowDesc:
    "Build carousel, feature intro, or prompt content cards, choose app start or banner/deeplink trigger, preview the modal, and clear QA cards from the store.",
  open: "Open",
  back: "Back",
  title: "Generic awareness modal — QA",
  sectionConfiguration: "Configuration",
  sectionActions: "Actions",
  sectionSavedCards: "Saved QA content cards",
  layout: "Layout",
  layoutCarousel: "Carousel",
  layoutFeatureIntro: "Feature intro",
  layoutPrompt: "Prompt",
  trigger: "Trigger",
  triggerAppStart: "App start",
  triggerBannerClick: "Banner click / deeplink",
  campaignId: "Campaign id (read-only)",
  campaignIdDeeplink: "Deeplink",
  copyDeeplink: "Copy deeplink",
  copiedDeeplink: "Copied",
  carouselSlides: "Carousel slides",
  featureIntroMain: "Main content card",
  promptMain: "Prompt content",
  featureIntroItems: "List items",
  addSlide: "Add slide",
  removeSlide: "Remove slide",
  addItem: "Add item",
  removeItem: "Remove item",
  slideLabel: (index: number) => `Slide ${index + 1}`,
  itemLabel: (index: number) => `Item ${index + 1}`,
  noSavedCards: "No QA cards saved yet.",
  removeCard: "Remove",
  addToStore: "Save card to app store",
  preview: "Preview modal",
  removeAll: "Remove all QA content cards",
  loadSamples: "Load sample fixtures",
  resetForm: "Reset form",
  fields: {
    title: "Title",
    subtitle: "Subtitle",
    imageUrl: "Image URL",
    primaryButtonLabel: "Primary button label",
    primaryButtonLink: "Primary button link",
    secondaryButtonLabel: "Secondary button label",
    secondaryButtonLink: "Secondary button link",
    icon: "Icon (Lumen symbol name)",
  },
} as const;
