import type { ServerConfig } from "@ledgerhq/wallet-api-server";
import type { WalletState } from "@ledgerhq/live-wallet/store";
import type { TrackingAPI } from "../../tracking";
import type { DeviceTransport, HandlerDeps } from "../types";
import { createAppManifest } from "../../logic/__tests__/testHelpers";

export { createAppManifest };

/**
 * Returns a `TrackingAPI` where every accessed method is a lazily-created `jest.fn()`.
 * Lets tests assert e.g. `tracking.receiveSuccess` was called without enumerating the
 * whole (large) TrackingAPI surface.
 */
export function createTrackingSpies(): TrackingAPI {
  const cache: Record<string, jest.Mock> = {};
  return new Proxy({} as TrackingAPI, {
    get: (_target, prop: string) => {
      if (!(prop in cache)) {
        cache[prop] = jest.fn();
      }
      return cache[prop];
    },
  });
}

/**
 * Builds a baseline `HandlerDeps` for handler-factory tests. Pass `overrides` to supply
 * the UI hooks under test (e.g. `{ uiAccountReceive: jest.fn() }`) and fixture `accounts`.
 *
 * Do not edit this file from package work — pass everything through `overrides` so the
 * shared fixtures stay conflict-free across parallel agents.
 */
export function makeHandlerDeps(overrides: Partial<HandlerDeps> = {}): HandlerDeps {
  return {
    walletState: {} as WalletState,
    manifest: createAppManifest(),
    accounts: [],
    tracking: createTrackingSpies(),
    config: {} as ServerConfig,
    dispatch: jest.fn(),
    deactivatedCurrencyIds: new Set<string>(),
    webviewReload: jest.fn(),
    device: {} as DeviceTransport,
    ...overrides,
  };
}

/** Convenience to turn a `HandlerDeps` into the `getDeps` callback the factories expect. */
export const getDepsFrom =
  (deps: HandlerDeps): (() => HandlerDeps) =>
  () =>
    deps;
