import { TFunction } from "react-i18next";
import { BigNumber } from "bignumber.js";
import { Account, AccountLike, SignedOperation } from "@ledgerhq/types-live";
import { Transaction, TransactionStatus } from "@ledgerhq/live-common/generated/types";
import { Device } from "@ledgerhq/live-common/hw/actions/types";
import { Step } from "~/renderer/components/Stepper";
export type StepId = "amount" | "summary" | "device" | "confirmation";
export type StepProps = {
  t: TFunction;
  transitionTo: (a: string) => void;
  openedFromAccount: boolean;
  useApp?: string;
  device: Device | undefined | null;
  account: AccountLike | undefined | null;
  parentAccount: Account | undefined | null;
  transaction: Transaction | undefined | null;
  status: TransactionStatus;
  bridgePending: boolean;
  error: Error | undefined | null;
  warning: Error | undefined | null;
  closeModal: (a: void) => void;
  openModal: (b: string, a: any) => void;
  onChangeAccount: (b?: AccountLike | null, a?: Account | null) => void;
  onChangeTransaction: (a: Transaction) => void;
  onTransactionError: (a: Error) => void;
  onTransactionSigned: (a: SignedOperation) => void;
  onRetry: (a: void) => void;
  maybeRecipient?: string;
  onResetMaybeRecipient: () => void;
  maybeAmount?: BigNumber;
  onResetMaybeAmount: () => void;
  updateTransaction: (updater: any) => void;
};
export type St = Step<StepId, StepProps>;
