// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Account from '../src/commands/account/index.js'
import Balances from '../src/commands/balances.js'
import Discover from '../src/commands/account/discover.js'
import Operations from '../src/commands/operations.js'
import Quote from '../src/commands/swap/quote.js'
import Receive from '../src/commands/receive.js'
import Send from '../src/commands/send.js'
import Swap from '../src/commands/swap/index.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['account', 'balances', 'discover', 'operations', 'quote', 'receive', 'send', 'swap'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'account': Account,
  'balances': Balances,
  'discover': Discover,
  'operations': Operations,
  'quote': Quote,
  'receive': Receive,
  'send': Send,
  'swap': Swap
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'account': {
      name: 'account',
      description: 'Account management commands',
      commands: [
        {
          name: 'discover',
          description: 'Discover accounts for a network on the connected device',
          options: {
            'network': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Network to scan, e.g. "bitcoin", "ethereum", "ethereum:goerli" (or first positional arg). No env = mainnet.', short: 'n', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
          },
          path: './src/commands/account/discover'
        }
      ],
      path: './src/commands/account/index'
    },
  'balances': {
      name: 'balances',
      description: 'Fetch native and token balances for an account descriptor (no device required)',
      options: {
        'account': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Short account descriptor (output of account discover), or pass as first positional arg', short: 'a', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
      },
      path: './src/commands/balances'
    },
  'discover': {
      name: 'discover',
      description: 'Discover accounts for a network on the connected device',
      options: {
        'network': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Network to scan, e.g. "bitcoin", "ethereum", "ethereum:goerli" (or first positional arg). No env = mainnet.', short: 'n', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
      },
      path: './src/commands/account/discover'
    },
  'operations': {
      name: 'operations',
      description: 'List operations for an account descriptor (no device required)',
      options: {
        'account': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Short account descriptor (output of account discover), or pass as first positional arg', short: 'a', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'limit': { type: 'z.coerce.number.int.min.optional', required: false, hasDefault: false, description: 'Max number of operations to return (Alpaca families only)', short: 'l', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'cursor': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Pagination cursor from a previous call\'s nextCursor (Alpaca families only)', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
      },
      path: './src/commands/operations'
    },
  'quote': {
      name: 'quote',
      description: 'Fetch swap quotes',
      options: {
        'from': { type: 'z.string.min', required: true, hasDefault: false, description: 'Source currency ID', short: 'f', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1102,"end":1103,"loc":{"start":{"line":36,"column":32,"index":1102},"end":{"line":36,"column":33,"index":1103}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Source currency is required"}]}, validator: '(val) => true' },
        'to': { type: 'z.string.min', required: true, hasDefault: false, description: 'Destination currency ID', short: 't', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1236,"end":1237,"loc":{"start":{"line":40,"column":30,"index":1236},"end":{"line":40,"column":31,"index":1237}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Destination currency is required"}]}, validator: '(val) => true' },
        'amount': { type: 'z.string.min', required: true, hasDefault: false, description: 'Amount to swap in source currency', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1384,"end":1385,"loc":{"start":{"line":44,"column":34,"index":1384},"end":{"line":44,"column":35,"index":1385}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Amount is required"}]}, validator: '(val) => true' },
        'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["human","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
      },
      path: './src/commands/swap/quote'
    },
  'receive': {
      name: 'receive',
      description: 'Get receive address for an account (optionally verify on device)',
      options: {
        'account': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Short account descriptor (output of account discover), or pass as first positional arg', short: 'a', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'verify': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Verify address on device screen (default: true). Use --no-verify to skip device.', short: 'v', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":816,"end":820,"loc":{"start":{"line":18,"column":39,"index":816},"end":{"line":18,"column":43,"index":820}},"value":true}}]}, validator: '(val) => true' },
        'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
      },
      path: './src/commands/receive'
    },
  'send': {
      name: 'send',
      description: 'Sign and broadcast a transaction (bridge only, no Alpaca)',
      options: {
        'account': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Short account descriptor (output of account discover), or pass as first positional arg', short: 'a', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'to': { type: 'z.string.min', required: true, hasDefault: false, description: 'Recipient address', short: 't', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1086,"end":1087,"loc":{"start":{"line":22,"column":30,"index":1086},"end":{"line":22,"column":31,"index":1087}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Recipient address is required (--to <address>)"}]}, validator: '(val) => true' },
        'amount': { type: 'z.string.min', required: true, hasDefault: false, description: 'Amount including ticker, e.g. \'0.001 BTC\', \'0.01 ETH\', \'0.4 USDT\'', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1249,"end":1250,"loc":{"start":{"line":27,"column":21,"index":1249},"end":{"line":27,"column":22,"index":1250}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Amount is required (--amount '<value> <TICKER>', e.g. '0.01 ETH')"}]}, validator: '(val) => true' },
        'fee-per-byte': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Fee per byte in satoshis (Bitcoin only)', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'rbf': { type: 'z.boolean.optional', required: false, hasDefault: false, description: 'Enable Replace-By-Fee (Bitcoin only)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'mode': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Transaction mode for Solana: send, stake.createAccount, stake.delegate, stake.undelegate, stake.withdraw', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'validator': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Validator address (Solana staking only)', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'stake-account': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Stake account address (Solana staking only)', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'memo': { type: 'z.string.min.optional', required: false, hasDefault: false, description: 'Memo/tag (Solana only)', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Prepare and validate transaction but do not sign or broadcast', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2268,"end":2273,"loc":{"start":{"line":51,"column":42,"index":2268},"end":{"line":51,"column":47,"index":2273}},"value":false}}]}, validator: '(val) => true' },
        'output': { type: 'OutputFormatSchema.default', required: true, hasDefault: true, default: "human", description: 'Output format: human (default) or json', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"human"}]}, validator: '(val) => true' }
      },
      path: './src/commands/send'
    },
  'swap': {
      name: 'swap',
      description: 'Swap-related commands',
      commands: [
        {
          name: 'quote',
          description: 'Fetch swap quotes',
          options: {
            'from': { type: 'z.string.min', required: true, hasDefault: false, description: 'Source currency ID', short: 'f', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1102,"end":1103,"loc":{"start":{"line":36,"column":32,"index":1102},"end":{"line":36,"column":33,"index":1103}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Source currency is required"}]}, validator: '(val) => true' },
            'to': { type: 'z.string.min', required: true, hasDefault: false, description: 'Destination currency ID', short: 't', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1236,"end":1237,"loc":{"start":{"line":40,"column":30,"index":1236},"end":{"line":40,"column":31,"index":1237}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Destination currency is required"}]}, validator: '(val) => true' },
            'amount': { type: 'z.string.min', required: true, hasDefault: false, description: 'Amount to swap in source currency', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1384,"end":1385,"loc":{"start":{"line":44,"column":34,"index":1384},"end":{"line":44,"column":35,"index":1385}},"extra":{"rawValue":1,"raw":"1"},"value":1}},{"type":"literal","value":"Amount is required"}]}, validator: '(val) => true' },
            'format': { type: 'z.enum.default', required: true, hasDefault: true, default: "json", description: 'Output format', enumValues: ["human","json"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"json"}]}, validator: '(val) => true' }
          },
          path: './src/commands/swap/quote'
        }
      ],
      path: './src/commands/swap/index'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
