import { BlockchainEVM } from "@ledgerhq/live-nft/supported";

export const nftCollectionsStatusByNetwork = {
  [BlockchainEVM.Ethereum]: {},
  [BlockchainEVM.Avalanche]: {},
  [BlockchainEVM.Polygon]: {},
  [BlockchainEVM.Arbitrum]: {},
  [BlockchainEVM.Base]: {},
  [BlockchainEVM.Blast]: {},
  [BlockchainEVM.Bsc]: {},
  [BlockchainEVM.Canto]: {},
  [BlockchainEVM.Celo]: {},
  [BlockchainEVM.Cyber]: {},
  [BlockchainEVM.Degen]: {},
  [BlockchainEVM.Fantom]: {},
  [BlockchainEVM.Gnosis]: {},
  [BlockchainEVM.Godwoken]: {},
  [BlockchainEVM.Linea]: {},
  [BlockchainEVM.Loot]: {},
  [BlockchainEVM.Manta]: {},
  [BlockchainEVM.Mode]: {},
  [BlockchainEVM.Moonbeam]: {},
  [BlockchainEVM.Opbnb]: {},
  [BlockchainEVM.Optimism]: {},
  [BlockchainEVM.Palm]: {},
  [BlockchainEVM.ProofOfPlay]: {},
  [BlockchainEVM.Rari]: {},
  [BlockchainEVM.Scroll]: {},
  [BlockchainEVM.Sei]: {},
  [BlockchainEVM.Xai]: {},
  [BlockchainEVM.Zora]: {},
};
