// @flow

// This will be converted into string enum once TypeScript is supported in this project.
export const ScreenName = {
  /* eslint sort-keys: ["error", "asc", {"caseSensitive": false}] */
  AboutSettings: "AboutSettings",
  Account: "Account",
  AccountCurrencySettings: "AccountCurrencySettings",
  Accounts: "Accounts",
  AccountSettingsMain: "AccountSettingsMain",
  AccountsSettings: "AccountsSettings",
  AddAccountsAccounts: "AddAccountsAccounts",
  AddAccountsSelectCrypto: "AddAccountsSelectCrypto",
  AddAccountsSelectDevice: "AddAccountsSelectDevice",
  AddAccountsSuccess: "AddAccountsSuccess",
  AddAccountsTokenCurrencyDisclaimer: "AddAccountsTokenCurrencyDisclaimer",
  AdvancedLogs: "AdvancedLogs",
  Asset: "Asset",
  BenchmarkQRStream: "BenchmarkQRStream",
  BitcoinEditFeePerByte: "BitcoinEditFeePerByte",
  ClaimRewardsConnectDevice: "ClaimRewardsConnectDevice",
  ClaimRewardsSelectDevice: "ClaimRewardsSelectDevice",
  ClaimRewardsValidationError: "ClaimRewardsValidationError",
  ClaimRewardsValidationSuccess: "ClaimRewardsValidationSuccess",
  ConfirmPassword: "ConfirmPassword",
  CountervalueSettings: "CountervalueSettings",
  CryptoAssetsSettings: "CryptoAssetsSettings",
  CurrenciesList: "CurrenciesList",
  CurrencySettings: "CurrencySettings",
  DebugBLE: "DebugBLE",
  DebugBLEBenchmark: "DebugBLEBenchmark",
  DebugCrash: "DebugCrash",
  DebugDevices: "DebugDevices",
  DebugExport: "DebugExport",
  DebugHttpTransport: "DebugHttpTransport",
  DebugIcons: "DebugIcons",
  DebugLogs: "DebugLogs",
  DebugLottie: "DebugLottie",
  DebugMocks: "DebugMocks",
  DebugPlayground: "DebugPlayground",
  DebugSettings: "DebugSettings",
  DebugStore: "DebugStore",
  DelegationConnectDevice: "DelegationConnectDevice",
  DelegationSelectDevice: "DelegationSelectDevice",
  DelegationSelectValidator: "DelegationSelectValidator",
  DelegationStarted: "DelegationStarted",
  DelegationSummary: "DelegationSummary",
  DelegationValidationError: "DelegationValidationError",
  DelegationValidationSuccess: "DelegationValidationSuccess",
  DisplayResult: "DisplayResult",
  Distribution: "Distribution",
  EditAccountName: "EditAccountName",
  EditAccountUnits: "EditAccountUnits",
  EditDeviceName: "EditDeviceName",
  EthereumEditFee: "EthereumEditFee",
  EthereumEditGasLimit: "EthereumEditGasLimit",
  Exchange: "Exchange",
  ExchangeBuy: "ExchangeBuy",
  ExchangeCoinifyWidget: "ExchangeCoinifyWidget",
  ExchangeConnectDevice: "ExchangeConnectDevice",
  ExchangeHistory: "ExchangeHistory",
  ExchangeSelectAccount: "ExchangeSelectAccount",
  ExchangeSelectCurrency: "ExchangeSelectCurrency",
  ExchangeSell: "ExchangeSell",
  ExchangeSellConnectDevice: "ExchangeSellConnectDevice",
  ExperimentalSettings: "ExperimentalSettings",
  FallBackCameraScreen: "FallBackCameraScreen",
  FallbackCameraSend: "FallbackCameraSend",
  FirmwareUpdateCheckId: "FirmwareUpdateCheckId",
  FirmwareUpdateConfirmation: "FirmwareUpdateConfirmation",
  FirmwareUpdateFailure: "FirmwareUpdateFailure",
  FirmwareUpdateMCU: "FirmwareUpdateMCU",
  FirmwareUpdateReleaseNotes: "FirmwareUpdateReleaseNotes",
  FreezeAmount: "FreezeAmount",
  FreezeConnectDevice: "FreezeConnectDevice",
  FreezeInfo: "FreezeInfo",
  FreezeSelectDevice: "FreezeSelectDevice",
  FreezeValidationError: "FreezeValidationError",
  FreezeValidationSuccess: "FreezeValidationSuccess",
  GeneralSettings: "GeneralSettings",
  HelpSettings: "HelpSettings",
  Manager: "Manager",
  ManagerAppsList: "ManagerAppsList",
  ManagerDevice: "ManagerDevice",
  ManagerMain: "ManagerMain",
  MigrateAccountsConnectDevice: "MigrateAccountsConnectDevice",
  MigrateAccountsOverview: "MigrateAccountsOverview",
  MigrateAccountsProgress: "MigrateAccountsProgress",

  OperationDetails: "OperationDetails",
  PairDevices: "PairDevices",
  PasswordAdd: "PasswordAdd",
  PasswordRemove: "PasswordRemove",
  Portfolio: "Portfolio",
  RateProviderSettings: "RateProviderSettings",
  ReceiveConfirmation: "ReceiveConfirmation",
  ReceiveConnectDevice: "ReceiveConnectDevice",
  ReceiveSelectAccount: "ReceiveSelectAccount",
  RepairDevice: "RepairDevice",
  Resources: "Resources",
  RippleEditFee: "RippleEditFee",
  RippleEditTag: "RippleEditTag",
  ScanAccounts: "ScanAccounts",
  ScanRecipient: "ScanRecipient",
  SendAmount: "SendAmount",
  SendConnectDevice: "SendConnectDevice",
  SendFundsMain: "SendFundsMain",
  SendSelectDevice: "SendSelectDevice",
  SendSelectRecipient: "SendSelectRecipient",
  SendSummary: "SendSummary",
  SendValidationError: "SendValidationError",
  SendValidationSuccess: "SendValidationSuccess",
  Settings: "Settings",
  SignConnectDevice: "SignConnectDevice",
  SignSelectDevice: "SignSelectDevice",
  SignSummary: "SignSummary",
  SignValidationError: "SignValidationError",
  SignValidationSuccess: "SignValidationSuccess",
  StellarEditMemoType: "StellarEditMemoType",
  StellarEditMemoValue: "StellarEditMemoValue",
  Swap: "Swap",
  SwapError: "SwapError",
  SwapForm: "SwapForm",
  SwapFormAmount: "SwapFormAmount",
  SwapFormOrHistory: "SwapFormOrHistory",
  SwapFormSelectAccount: "SwapFormSelectAccount",
  SwapFormSelectCrypto: "SwapFormSelectCrypto",
  SwapHistory: "SwapHistory",
  SwapOperationDetails: "SwapOperationDetails",
  SwapPendingOperation: "SwapPendingOperation",
  SwapSummary: "SwapSummary",
  TezosDelegationFlow: "TezosDelegationFlow",
  Transfer: "Transfer",
  UnfreezeAmount: "UnfreezeAmount",
  UnfreezeConnectDevice: "UnfreezeConnectDevice",
  UnfreezeSelectDevice: "UnfreezeSelectDevice",
  UnfreezeValidationError: "UnfreezeValidationError",
  UnfreezeValidationSuccess: "UnfreezeValidationSuccess",
  VoteCast: "VoteCast",
  VoteConnectDevice: "VoteConnectDevice",
  VoteSelectDevice: "VoteSelectDevice",
  VoteSelectValidator: "VoteSelectValidator",
  VoteStarted: "VoteStarted",
  VoteValidation: "VoteValidation",
  VoteValidationError: "VoteValidationError",
  VoteValidationSuccess: "VoteValidationSuccess",
  /* eslint-disable sort-keys */
  CosmosEditMemo: "CosmosEditMemo",
  CosmosDelegationStarted: "CosmosDelegationStarted",
  CosmosDelegationValidator: "CosmosDelegationValidator",
  CosmosDelegationAmount: "CosmosDelegationAmount",
  CosmosDelegationSelectDevice: "CosmosDelegationSelectDevice",
  CosmosDelegationConnectDevice: "CosmosDelegationConnectDevice",
  CosmosDelegationValidationError: "CosmosDelegationValidationError",
  CosmosDelegationValidationSuccess: "CosmosDelegationValidationSuccess",
  CosmosRedelegationValidator: "CosmosRedelegationValidator",
  CosmosRedelegationAmount: "CosmosRedelegationAmount",
  CosmosRedelegationSelectDevice: "CosmosRedelegationSelectDevice",
  CosmosRedelegationConnectDevice: "CosmosRedelegationConnectDevice",
  CosmosRedelegationValidationError: "CosmosRedelegationValidationError",
  CosmosRedelegationValidationSuccess: "CosmosRedelegationValidationSuccess",
  CosmosUndelegationAmount: "CosmosUndelegationAmount",
  CosmosUndelegationSelectDevice: "CosmosUndelegationSelectDevice",
  CosmosUndelegationConnectDevice: "CosmosUndelegationConnectDevice",
  CosmosUndelegationValidationError: "CosmosUndelegationValidationError",
  CosmosUndelegationValidationSuccess: "CosmosUndelegationValidationSuccess",
  CosmosClaimRewardsValidator: "CosmosClaimRewardsValidator",
  CosmosClaimRewardsMethod: "CosmosClaimRewardsMethod",
  CosmosClaimRewardsSelectDevice: "CosmosClaimRewardsSelectDevice",
  CosmosClaimRewardsConnectDevice: "CosmosClaimRewardsConnectDevice",
  CosmosClaimRewardsValidation: "CosmosClaimRewardsValidation",
  CosmosClaimRewardsValidationError: "CosmosClaimRewardsValidationError",
  CosmosClaimRewardsValidationSuccess: "CosmosClaimRewardsValidationSuccess",

  AlgorandEditMemo: "AlgorandEditMemo",
  AlgorandClaimRewardsInfo: "AlgorandClaimRewardsInfo",
  AlgorandClaimRewardsStarted: "AlgorandClaimRewardsStarted",
  AlgorandClaimRewardsSelectDevice: "AlgorandClaimRewardsSelectDevice",
  AlgorandClaimRewardsConnectDevice: "AlgorandClaimRewardsConnectDevice",
  AlgorandClaimRewardsValidation: "AlgorandClaimRewardsValidation",
  AlgorandClaimRewardsValidationError: "AlgorandClaimRewardsValidationError",
  AlgorandClaimRewardsValidationSuccess:
    "AlgorandClaimRewardsValidationSuccess",
  AlgorandOptInSelectToken: "AlgorandOptInSelectToken",
  AlgorandOptInSelectDevice: "AlgorandOptInSelectDevice",
  AlgorandOptInConnectDevice: "AlgorandOptInConnectDevice",
  AlgorandOptInValidation: "AlgorandOptInValidation",
  AlgorandOptInValidationError: "AlgorandOptInValidationError",
  AlgorandOptInValidationSuccess: "AlgorandOptInValidationSuccess",

  // Polkadot
  PolkadotBondStarted: "PolkadotBondStarted",
  PolkadotBondAmount: "PolkadotBondAmount",
  PolkadotBondSelectDevice: "PolkadotBondSelectDevice",
  PolkadotBondConnectDevice: "PolkadotBondConnectDevice",
  PolkadotBondValidationError: "PolkadotBondValidationError",
  PolkadotBondValidationSuccess: "PolkadotBondValidationSuccess",
  PolkadotUnbondAmount: "PolkadotUnbondAmount",
  PolkadotUnbondSelectDevice: "PolkadotUnbondSelectDevice",
  PolkadotUnbondConnectDevice: "PolkadotUnbondConnectDevice",
  PolkadotUnbondValidationError: "PolkadotUnbondValidationError",
  PolkadotUnbondValidationSuccess: "PolkadotUnbondValidationSuccess",
  PolkadotRebondAmount: "PolkadotRebondAmount",
  PolkadotRebondSelectDevice: "PolkadotRebondSelectDevice",
  PolkadotRebondConnectDevice: "PolkadotRebondConnectDevice",
  PolkadotRebondValidationError: "PolkadotRebondValidationError",
  PolkadotRebondValidationSuccess: "PolkadotRebondValidationSuccess",
  PolkadotNominateSelectValidators: "PolkadotNominateSelectValidators",
  PolkadotNominateSelectDevice: "PolkadotNominateSelectDevice",
  PolkadotNominateConnectDevice: "PolkadotNominateConnectDevice",
  PolkadotNominateValidationError: "PolkadotNominateValidationError",
  PolkadotNominateValidationSuccess: "PolkadotNominateValidationSuccess",
  PolkadotSimpleOperationStarted: "PolkadotSimpleOperationStarted",
  PolkadotSimpleOperationSelectDevice: "PolkadotSimpleOperationSelectDevice",
  PolkadotSimpleOperationConnectDevice: "PolkadotSimpleOperationConnectDevice",
  PolkadotSimpleOperationValidationError:
    "PolkadotSimpleOperationValidationError",
  PolkadotSimpleOperationValidationSuccess:
    "PolkadotSimpleOperationValidationSuccess",

  LendingDashboard: "LendingDashboard",
  LendingClosedLoans: "LendingClosedLoans",
  LendingHistory: "LendingHistory",
  LendingTerms: "LendingTerms",
  LendingInfo1: "LendingInfo1",
  LendingInfo2: "LendingInfo2",
  LendingInfo3: "LendingInfo3",

  LendingEnableSelectAccount: "Lend ApproveSelectAccount",
  LendingEnableAmount: "Lend ApproveAmount",
  LendingEnableAmountAdvanced: "Lend ApproveAmountAdvanced",
  LendingEnableAmountInput: "Lend ApproveAmountInput",
  LendingEnableSummary: "Lend ApproveSummary",
  LendingEnableSelectDevice: "Lend ApproveSelectDevice",
  LendingEnableConnectDevice: "Lend ApproveConnectDevice",
  LendingEnableValidation: "Lend ApproveValidation",
  LendingEnableValidationError: "Lend ApproveValidationError",
  LendingEnableValidationSuccess: "Lend ApproveValidationSuccess",

  LendingSupplyAmount: "Lend SupplyAmount",
  LendingSupplySummary: "Lend SupplySummary",
  LendingSupplySelectDevice: "Lend SupplySelectDevice",
  LendingSupplyConnectDevice: "Lend SupplyConnectDevice",
  LendingSupplyValidation: "Lend SupplyValidation",
  LendingSupplyValidationError: "Lend SupplyValidationError",
  LendingSupplyValidationSuccess: "Lend SupplyValidationSuccess",

  LendingWithdrawAmount: "Lend WithdrawAmount",
  LendingWithdrawSummary: "Lend WithdrawSummary",
  LendingWithdrawSelectDevice: "Lend WithdrawSelectDevice",
  LendingWithdrawConnectDevice: "Lend WithdrawConnectDevice",
  LendingWithdrawValidation: "Lend WithdrawValidation",
  LendingWithdrawValidationError: "Lend WithdrawValidationError",
  LendingWithdrawValidationSuccess: "Lend WithdrawValidationSuccess",

  OnboardingWelcome: "OnboardingWelcome",
  OnboardingLanguage: "OnboardingLanguage",
  OnboardingTermsOfUse: "OnboardingTermsOfUse",
  OnboardingDeviceSelection: "OnboardingDeviceSelection",
  OnboardingUseCase: "OnboardingUseCase",

  OnboardingSetNewDeviceInfo: "OnboardingSetNewDeviceInfo",
  OnboardingSetNewDevice: "OnboardingSetNewDevice",
  OnboardingInfoModal: "OnboardingInfoModal",
  OnboardingRecoveryPhrase: "OnboardingRecoveryPhrase",

  OnboardingPairNew: "OnboardingPairNew",
  OnboardingImportAccounts: "OnboardingImportAccounts",

  OnboardingImportScan: "OnboardingImportScan",
  OnboardingImportSelectAccount: "OnboardingImportSelectAccount",

  OnboardingQuiz: "OnboardingQuiz",
  OnboardingQuizFinal: "OnboardingQuizFinal",

  OnboardingFinish: "OnboardingFinish",
  WalletConnectScan: "WalletConnectScan",
  WalletConnectConnect: "WalletConnectConnect",
  WalletConnectDeeplinkingSelectAccount:
    "WalletConnectDeeplinkingSelectAccount",
};

export const NavigatorName = {
  // Stack
  /* eslint sort-keys: ["error", "asc", {"caseSensitive": false}] */
  // add "Navigator" postfix to distinguish this from ScreenName.Accounts
  Accounts: "AccountsNavigator",
  AccountSettings: "AccountSettings",
  AddAccounts: "AddAccounts",
  Exchange: "Exchange",
  ExchangeBuyFlow: "ExchangeBuyFlow",
  ExchangeSellFlow: "ExchangeSellFlow",
  Base: "Base",
  BaseOnboarding: "BaseOnboarding",
  CosmosClaimRewardsFlow: "CosmosClaimRewardsFlow",
  CosmosDelegationFlow: "CosmosDelegationFlow",
  CosmosRedelegationFlow: "CosmosRedelegationFlow",
  CosmosUndelegationFlow: "CosmosUndelegationFlow",
  AlgorandClaimRewardsFlow: "AlgorandClaimRewardsFlow",
  AlgorandOptInFlow: "AlgorandOptInFlow",
  ClaimRewards: "ClaimRewards",
  FirmwareUpdate: "FirmwareUpdate",
  Freeze: "Freeze",
  ImportAccounts: "ImportAccounts",
  Manager: "Manager",
  ManagerStack: "ManagerStack",
  MigrateAccountsFlow: "MigrateAccountsFlow",
  Onboarding: "Onboarding",
  PasswordAddFlow: "PasswordAddFlow",
  PasswordModifyFlow: "PasswordModifyFlow",
  ReceiveFunds: "ReceiveFunds",
  SendFunds: "SendFunds",
  Settings: "Settings",
  SignMessage: "SignMessage",
  Swap: "Swap",
  TezosDelegationFlow: "TezosDelegationFlow",
  TronVoteFlow: "TronVoteFlow",
  Unfreeze: "Unfreeze",
  Lending: "Lending",
  LendingInfo: "LendingInfo",
  LendingEnableFlow: "LendingEnableFlow",
  LendingSupplyFlow: "LendingSupplyFlow",
  LendingWithdrawFlow: "LendingWithdrawFlow",
  /* eslint-disable sort-keys */

  // Polkadot
  PolkadotBondFlow: "PolkadotBondFlow",
  PolkadotUnbondFlow: "PolkadotUnbondFlow",
  PolkadotRebondFlow: "PolkadotRebondFlow",
  PolkadotNominateFlow: "PolkadotNominateFlow",
  PolkadotSimpleOperationFlow: "PolkadotSimpleOperationFlow",

  // Tab
  Main: "Main",

  // Root
  RootNavigator: "RootNavigator",
};
