/**
 * IPC contract between the ZCash renderer client, the Electron main process,
 * and the UtilityProcess that hosts the native Rust engine.
 *
 * The same shapes are used across both hops:
 *
 *     renderer  <-- ipcRenderer -->  main  <-- utility.parentPort -->  utility
 *
 * Everything here must be `structuredClone`-safe (no BigNumber, no functions,
 * no Buffer subclasses). Numeric amounts travel as strings in
 * {@link ShieldedSyncResultRaw}; BigNumber reconstruction happens client-side.
 */

import type { ShieldedSyncResultRaw } from "../types";

/** Unique per-subscription id, generated by the renderer client. */
export type RequestId = string;

// ─── Renderer <-> Main (ipcRenderer.invoke / webContents.send) ───────────────

/** Channel names — centralized to keep renderer/main/utility in lock-step. */
export const ZCASH_IPC = {
  /** invoke → number (chain tip height) */
  getChainTip: "zcash:getChainTip",
  /** invoke → { ok: true } once the utility has acknowledged. Chunks arrive on `stream`. */
  startSync: "zcash:startSync",
  /** invoke → void. Propagates a cancel signal to the utility. */
  cancelSync: "zcash:cancelSync",
  /** webContents.send → StreamEvent. Filter by requestId on the renderer side. */
  stream: "zcash:stream",
} as const;

export type ZcashIpcChannel = (typeof ZCASH_IPC)[keyof typeof ZCASH_IPC];

// ─── Request payloads ────────────────────────────────────────────────────────

export type GetChainTipArgs = {
  requestId: RequestId;
  grpcUrl: string;
};

export type StartSyncArgs = {
  requestId: RequestId;
  grpcUrl: string;
  network: string;
  viewingKey: string;
  startBlockHeight: number;
  maxBatchSize: number;
};

export type CancelSyncArgs = {
  requestId: RequestId;
};

// ─── Stream events (main → renderer, utility → main) ─────────────────────────

/**
 * Events emitted during a sync subscription. The renderer client filters them
 * by `requestId` and rehydrates `chunk.result` into a `ShieldedSyncResult`
 * with real `BigNumber` instances.
 */
export type StreamEvent =
  | { requestId: RequestId; kind: "chunk"; result: ShieldedSyncResultRaw }
  | { requestId: RequestId; kind: "complete" }
  | { requestId: RequestId; kind: "error"; message: string };

// ─── Utility <-> Main (parentPort.postMessage) ──────────────────────────────
//
// The utility-facing protocol is symmetric: the main process forwards the same
// `StartSyncArgs` / `CancelSyncArgs` / `GetChainTipArgs` shapes down the
// parentPort, tagged with a `type`. The utility replies with either a
// `chain-tip` (one-shot) or a `stream` event (sync loop).

export type UtilityInboundMessage =
  | { type: "get-chain-tip"; args: GetChainTipArgs }
  | { type: "start-sync"; args: StartSyncArgs }
  | { type: "cancel-sync"; args: CancelSyncArgs };

export type UtilityOutboundMessage =
  | { type: "chain-tip"; requestId: RequestId; height: number }
  | { type: "chain-tip-error"; requestId: RequestId; message: string }
  | { type: "stream"; event: StreamEvent };
