require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Use the node resolver because pnpm nests modules.
def relative_path(module_name)
  module_pathname = Pathname.new File.dirname(`node --print "require.resolve('#{module_name}/package.json')"`)
  module_pathname.relative_path_from(Pathname.new File.absolute_path ".")
end

expo_autolinking = File.join(relative_path("expo"), "scripts/autolinking")
rct_text = File.join(relative_path("react-native"), "Libraries/Text")

require expo_autolinking
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

# Without the .pnpm path expo autolinking script will fail to locate transitive dependencies.
platform_separator = Gem.win_platform? ? ";" : ":"
pnpm_hoisted_node_modules = File.expand_path(
  File.join(
    File.dirname(__FILE__), "..", "..", "..", "node_modules", ".pnpm", "node_modules"
  )
)
common_node_modules = File.expand_path(
  File.join(
    File.dirname(__FILE__), "..", "..", "..", "libs", "ledger-live-common", "node_modules"
  )
)

ENV["NODE_PATH"] ||= pnpm_hoisted_node_modules + platform_separator + common_node_modules


target 'LiveBotRN' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'LiveBotRNTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end