/**
 * Blocklist of props that should NOT be forwarded to DOM elements.
 * These are custom/styled-system props used for styling, not valid HTML attributes.
 * Used with StyleSheetManager to prevent React console warnings.
 */
const INVALID_DOM_PROPS = new Set([
  // Desktop Box custom props
  "grow",
  "shrink",
  "noShrink",
  "flow",
  "horizontal",
  "scroll",
  "relative",
  "sticky",
  "selectable",
  "ff",
  "align",
  "justify",
  // Styled-system: space
  "m",
  "mx",
  "my",
  "mt",
  "mr",
  "mb",
  "ml",
  "p",
  "px",
  "py",
  "pt",
  "pr",
  "pb",
  "pl",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "marginX",
  "marginY",
  "padding",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "paddingX",
  "paddingY",
  // Styled-system: flexbox
  "alignItems",
  "alignContent",
  "alignSelf",
  "justifyContent",
  "justifyItems",
  "justifySelf",
  "flex",
  "flexWrap",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "order",
  // Styled-system: layout
  "width",
  "minWidth",
  "maxWidth",
  "height",
  "minHeight",
  "maxHeight",
  "size",
  "display",
  "verticalAlign",
  "overflow",
  "overflowX",
  "overflowY",
  // Styled-system: position
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "zIndex",
  // Styled-system: color
  "color",
  "bg",
  "backgroundColor",
  "opacity",
  // Styled-system: typography
  "fontSize",
  "fontWeight",
  "fontFamily",
  "textAlign",
  "textTransform",
  "lineHeight",
  "letterSpacing",
  // Styled-system: misc
  "boxShadow",
  "borderRadius",
  "border",
  "borderWidth",
  "borderStyle",
  "borderColor",
  "gap",
  "rowGap",
  "columnGap",
  "gridGap",
  "gridRowGap",
  "gridColumnGap",
  "columns",
  "rows",
  "gridTemplateColumns",
  "gridTemplateRows",
  "gridColumn",
  "gridRow",
  "gridArea",
  "cursor",
  // Other custom props from styled components
  "collapsed",
  "visible",
  "dispatch",
  "state",
  "val",
  "totalBalance",
  "optimistic",
  "isConfirmed",
  "marketColor",
  "hasFailed",
  "bordered",
  "inline",
  "isInteractive",
  "isResponsiveLayout",
  "open",
  "timing",
  "show",
  "isOpen",
  "forceBgColor",
  "isChecked",
  "withPaddingTop",
  // Additional custom props from styled components
  "status",
  "noScroll",
  "chevronVisible",
  "selected",
  "error",
  "warning",
  "info",
  "isOptimistic",
  "toExists",
  "green",
  "big",
  "small",
  "expanded",
  "danger",
  "isIncomplete",
  "isRead",
  "visibility",
  "isLoading",
  "completed",
  "disableHover",
  "image",
  "active",
  "index",
  "noMargin",
  "isSR",
  "delay",
  "bgColor",
  "dark",
  // Additional boolean/custom props from components
  "isFocused",
  "isRotating",
  "isActive",
  "hasTitle",
  "centered",
  "isOpened",
  "isopened",
  "badgeSize",
  "hasBadge",
  "iconButton",
  "deviceModel",
  "installing",
  "iconLink",
  "iconPosition",
  "Icon",
  "primary",
  "innerRef",
  "inverted",
  "fullWidth",
  "short",
  "separator",
  "focused",
  "overridesRadius",
  "lighterPrimary",
  "loading",
  "currentRef",
  "loaded",
  "mobileView",
  "isFocus",
  "outlineGrey",
  "filled",
  "isSubAccountsExpanded",
  "focus",
  "orderDirection",
  "header",
  "backdropColor",
  // Additional from components (variant, size, etc.)
  "variant",
  "medium",
  "tooltipBg",
  "followCursor",
  "placement",
  "arrow",
  "hideOnClick",
  "containerStyle",
]);

/**
 * Props that are valid HTML attributes only on specific elements.
 * We block them globally (e.g. for styled-system on div) but must allow them
 * when the target is an element that supports them (e.g. width/height on img).
 */
const ELEMENT_SPECIFIC_VALID_PROPS: Record<string, Set<string>> = {
  img: new Set(["width", "height"]),
  input: new Set(["width", "height", "size"]),
  canvas: new Set(["width", "height"]),
  video: new Set(["width", "height"]),
  svg: new Set(["width", "height", "visibility"]),
};

/**
 * For string targets (DOM elements like 'div', 'span'), forward all props
 * except those present in INVALID_DOM_PROPS.
 * Some standard attributes that are generally blocked (e.g. width/height)
 * are re-allowed on elements that support them, as defined in ELEMENT_SPECIFIC_VALID_PROPS.
 * For component targets (non-string), forward all props.
 */
export function shouldForwardProp(propName: string, target: unknown): boolean {
  if (typeof target !== "string") {
    return true;
  }
  const elementValid = ELEMENT_SPECIFIC_VALID_PROPS[target]?.has(propName);
  if (elementValid) {
    return true;
  }
  return !INVALID_DOM_PROPS.has(propName);
}
