export const ASSET_DETAIL_TEST_IDS = {
  screen: "asset-detail-screen",
  balanceGraph: "asset-detail-balance-graph",
  marketPrice: "asset-detail-market-price",
  chartPlaceholder: "asset-detail-chart-placeholder",
  receiveButton: "asset-detail-receive-button",
  balanceDetails: "asset-detail-balance-details",
  totalBalance: "asset-detail-total-balance",
  transferButton: "asset-detail-transfer-button",
  earnBanner: "asset-detail-earn-banner",
  availableBalance: "asset-detail-available-balance",
  earnDeposit: "asset-detail-earn-deposit",
  addresses: "asset-detail-addresses",
  addAccount: "asset-detail-add-account",
  marketStats: "asset-detail-market-stats",
  pricePerformance: "asset-detail-price-performance",
  transactions: "asset-detail-transactions",
  ctas: "asset-detail-ctas",
  buyButton: "asset-detail-buy-button",
  swapButton: "asset-detail-swap-button",
  footerReceiveButton: "asset-detail-footer-receive-button",
  fallbackBanner: "asset-detail-fallback-banner",
} as const;
