// This file is auto-generated by scripts/generate-graphql-types.mjs.
// Do not edit by hand. Regenerate with: pnpm graphql:codegen
// Source schema: https://graphql.mainnet.sui.io/graphql
/* eslint-disable */
export type introspection_types = {
  Address: {
    kind: "OBJECT";
    name: "Address";
    fields: {
      balances: {
        name: "balances";
        type: { kind: "OBJECT"; name: "BalanceConnection"; ofType: null };
      };
      dynamicField: {
        name: "dynamicField";
        type: { kind: "OBJECT"; name: "DynamicField"; ofType: null };
      };
      objects: {
        name: "objects";
        type: { kind: "OBJECT"; name: "MoveObjectConnection"; ofType: null };
      };
    };
  };
  Balance: {
    kind: "OBJECT";
    name: "Balance";
    fields: {
      coinType: { name: "coinType"; type: { kind: "OBJECT"; name: "MoveType"; ofType: null } };
      totalBalance: {
        name: "totalBalance";
        type: { kind: "SCALAR"; name: "BigInt"; ofType: null };
      };
      addressBalance: {
        name: "addressBalance";
        type: { kind: "SCALAR"; name: "BigInt"; ofType: null };
      };
    };
  };
  BalanceConnection: {
    kind: "OBJECT";
    name: "BalanceConnection";
    fields: {
      pageInfo: {
        name: "pageInfo";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "OBJECT"; name: "PageInfo"; ofType: null };
        };
      };
      nodes: {
        name: "nodes";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: {
            kind: "LIST";
            name: never;
            ofType: {
              kind: "NON_NULL";
              name: never;
              ofType: { kind: "OBJECT"; name: "Balance"; ofType: null };
            };
          };
        };
      };
    };
  };
  Base64: unknown;
  BigInt: unknown;
  Boolean: unknown;
  Checkpoint: {
    kind: "OBJECT";
    name: "Checkpoint";
    fields: {
      sequenceNumber: {
        name: "sequenceNumber";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "SCALAR"; name: "UInt53"; ofType: null };
        };
      };
      digest: { name: "digest"; type: { kind: "SCALAR"; name: "String"; ofType: null } };
      timestamp: { name: "timestamp"; type: { kind: "SCALAR"; name: "DateTime"; ofType: null } };
    };
  };
  DateTime: unknown;
  DynamicField: {
    kind: "OBJECT";
    name: "DynamicField";
    fields: {
      value: { name: "value"; type: { kind: "UNION"; name: "DynamicFieldValue"; ofType: null } };
    };
  };
  DynamicFieldName: {
    kind: "INPUT_OBJECT";
    name: "DynamicFieldName";
    isOneOf: false;
    inputFields: [
      {
        name: "literal";
        type: { kind: "SCALAR"; name: "String"; ofType: null };
        defaultValue: null;
      },
    ];
  };
  DynamicFieldValue: {
    kind: "UNION";
    name: "DynamicFieldValue";
    fields: {};
    possibleTypes: "MoveObject" | "MoveValue";
  };
  Epoch: {
    kind: "OBJECT";
    name: "Epoch";
    fields: {
      epochId: {
        name: "epochId";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "SCALAR"; name: "UInt53"; ofType: null };
        };
      };
      systemState: {
        name: "systemState";
        type: { kind: "OBJECT"; name: "MoveValue"; ofType: null };
      };
    };
  };
  Float: unknown;
  IAddressable: {
    kind: "INTERFACE";
    name: "IAddressable";
    fields: {};
    possibleTypes: "Address" | "DynamicField" | "MoveObject";
  };
  ID: unknown;
  IMoveObject: {
    kind: "INTERFACE";
    name: "IMoveObject";
    fields: {};
    possibleTypes: "DynamicField" | "MoveObject";
  };
  IObject: {
    kind: "INTERFACE";
    name: "IObject";
    fields: {};
    possibleTypes: "DynamicField" | "MoveObject";
  };
  Int: unknown;
  JSON: unknown;
  MoveObject: {
    kind: "OBJECT";
    name: "MoveObject";
    fields: {
      contents: { name: "contents"; type: { kind: "OBJECT"; name: "MoveValue"; ofType: null } };
    };
  };
  MoveObjectConnection: {
    kind: "OBJECT";
    name: "MoveObjectConnection";
    fields: {
      pageInfo: {
        name: "pageInfo";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "OBJECT"; name: "PageInfo"; ofType: null };
        };
      };
      nodes: {
        name: "nodes";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: {
            kind: "LIST";
            name: never;
            ofType: {
              kind: "NON_NULL";
              name: never;
              ofType: { kind: "OBJECT"; name: "MoveObject"; ofType: null };
            };
          };
        };
      };
    };
  };
  MoveType: {
    kind: "OBJECT";
    name: "MoveType";
    fields: {
      repr: {
        name: "repr";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "SCALAR"; name: "String"; ofType: null };
        };
      };
    };
  };
  MoveValue: {
    kind: "OBJECT";
    name: "MoveValue";
    fields: { json: { name: "json"; type: { kind: "SCALAR"; name: "JSON"; ofType: null } } };
  };
  Mutation: { kind: "OBJECT"; name: "Mutation"; fields: {} };
  Node: {
    kind: "INTERFACE";
    name: "Node";
    fields: {};
    possibleTypes: "Address" | "Checkpoint" | "DynamicField" | "Epoch" | "MoveObject";
  };
  ObjectFilter: {
    kind: "INPUT_OBJECT";
    name: "ObjectFilter";
    isOneOf: false;
    inputFields: [
      { name: "type"; type: { kind: "SCALAR"; name: "String"; ofType: null }; defaultValue: null },
    ];
  };
  PageInfo: {
    kind: "OBJECT";
    name: "PageInfo";
    fields: {
      hasNextPage: {
        name: "hasNextPage";
        type: {
          kind: "NON_NULL";
          name: never;
          ofType: { kind: "SCALAR"; name: "Boolean"; ofType: null };
        };
      };
      endCursor: { name: "endCursor"; type: { kind: "SCALAR"; name: "String"; ofType: null } };
    };
  };
  Query: {
    kind: "OBJECT";
    name: "Query";
    fields: {
      address: { name: "address"; type: { kind: "OBJECT"; name: "Address"; ofType: null } };
      checkpoint: {
        name: "checkpoint";
        type: { kind: "OBJECT"; name: "Checkpoint"; ofType: null };
      };
      epoch: { name: "epoch"; type: { kind: "OBJECT"; name: "Epoch"; ofType: null } };
    };
  };
  String: unknown;
  SuiAddress: unknown;
  UInt53: unknown;
  __Directive: { kind: "OBJECT"; name: "__Directive"; fields: {} };
  __DirectiveLocation: {
    name: "__DirectiveLocation";
    enumValues:
      | "QUERY"
      | "MUTATION"
      | "SUBSCRIPTION"
      | "FIELD"
      | "FRAGMENT_DEFINITION"
      | "FRAGMENT_SPREAD"
      | "INLINE_FRAGMENT"
      | "VARIABLE_DEFINITION"
      | "SCHEMA"
      | "SCALAR"
      | "OBJECT"
      | "FIELD_DEFINITION"
      | "ARGUMENT_DEFINITION"
      | "INTERFACE"
      | "UNION"
      | "ENUM"
      | "ENUM_VALUE"
      | "INPUT_OBJECT"
      | "INPUT_FIELD_DEFINITION";
  };
  __EnumValue: { kind: "OBJECT"; name: "__EnumValue"; fields: {} };
  __Field: { kind: "OBJECT"; name: "__Field"; fields: {} };
  __InputValue: { kind: "OBJECT"; name: "__InputValue"; fields: {} };
  __Schema: { kind: "OBJECT"; name: "__Schema"; fields: {} };
  __Type: { kind: "OBJECT"; name: "__Type"; fields: {} };
  __TypeKind: {
    name: "__TypeKind";
    enumValues:
      | "SCALAR"
      | "OBJECT"
      | "INTERFACE"
      | "UNION"
      | "ENUM"
      | "INPUT_OBJECT"
      | "LIST"
      | "NON_NULL";
  };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: "Query";
  mutation: "Mutation";
  subscription: never;
  types: introspection_types;
};
