/* eslint-disable @typescript-eslint/no-require-imports */
import type { CoinModuleLoader } from "./types";

// Hand-maintained: one entry per coin family. See FUTURE.md for the async evolution plan.
export const coinModuleLoaders: CoinModuleLoader[] = [
  {
    family: "aleo",
    loadSetup: () => require("../families/aleo/setup"),
    loadTransaction: () => require("@ledgerhq/coin-aleo/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-aleo/deviceTransactionConfig").default,
  },
  {
    family: "algorand",
    loadSetup: () => require("../families/algorand/setup"),
    loadTransaction: () => require("@ledgerhq/coin-algorand/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-algorand/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/algorand/bridge/mock").default,
    loadMockAccount: () => require("@ledgerhq/coin-algorand/mock").default,
  },
  {
    family: "aptos",
    loadSetup: () => require("../families/aptos/setup"),
    loadTransaction: () => require("@ledgerhq/coin-aptos/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-aptos/deviceTransactionConfig").default,
  },
  {
    family: "bitcoin",
    loadSetup: () => require("../families/bitcoin/setup"),
    loadTransaction: () => require("@ledgerhq/coin-bitcoin/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-bitcoin/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/bitcoin/walletApiAdapter").default,
    loadPlatformAdapter: () => require("../families/bitcoin/platformAdapter").default,
    loadAccount: () => require("@ledgerhq/coin-bitcoin/account").default,
    loadMockBridge: () => require("../families/bitcoin/bridge/mock").default,
    loadClearAccount: () => require("../families/bitcoin/clearAccount").clearAccount,
    loadIsEditableOperation: () => require("../families/bitcoin/operations").isEditableOperation,
    loadIsStuckOperation: () => require("../families/bitcoin/operations").isStuckOperation,
    loadGetStuckAccountAndOperation: () => require("../families/bitcoin/operations").getStuckAccountAndOperation,
  },
  {
    family: "canton",
    loadSetup: () => require("../families/canton/setup"),
    loadTransaction: () => require("@ledgerhq/coin-canton/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-canton/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/canton/bridge/mock").default,
    loadIsAccountEmpty: () => require("@ledgerhq/coin-canton").isAccountEmpty,
  },
  {
    family: "cardano",
    loadSetup: () => require("../families/cardano/setup"),
    loadTransaction: () => require("@ledgerhq/coin-cardano/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-cardano/deviceTransactionConfig").default,
    loadAccount: () => require("@ledgerhq/coin-cardano/account").default,
    loadMockBridge: () => require("../families/cardano/bridge/mock").default,
  },
  {
    family: "casper",
    loadSetup: () => require("../families/casper/setup"),
    loadTransaction: () => require("@ledgerhq/coin-casper/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-casper/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/casper/bridge/mock").default,
  },
  {
    family: "celo",
    loadSetup: () => require("../families/celo/setup"),
    loadTransaction: () => require("@ledgerhq/coin-celo/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-celo/deviceTransactionConfig").default,
  },
  {
    family: "concordium",
    loadSetup: () => require("../families/concordium/setup"),
    loadTransaction: () => require("@ledgerhq/coin-concordium/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-concordium/deviceTransactionConfig").default,
  },
  {
    family: "cosmos",
    loadSetup: () => require("../families/cosmos/setup"),
    loadTransaction: () => require("@ledgerhq/coin-cosmos/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-cosmos/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/cosmos/walletApiAdapter").default,
    loadMockBridge: () => require("../families/cosmos/bridge/mock").default,
    loadMockAccount: () => require("@ledgerhq/coin-cosmos/mock").default,
    loadIsAccountEmpty: () => require("@ledgerhq/coin-cosmos/helpers").isAccountEmpty,
    loadGetVotesCount: () => require("../families/cosmos/getVotesCount").getVotesCount,
  },
  {
    family: "evm",
    loadSetup: () => require("../families/evm/setup"),
    loadTransaction: () => require("@ledgerhq/coin-evm/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-evm/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/evm/walletApiAdapter").default,
    loadPlatformAdapter: () => require("../families/evm/platformAdapter").default,
    loadMockBridge: () => require("../families/evm/bridge/mock").default,
    loadValidateAddress: () => require("@ledgerhq/coin-evm/logic/validateAddress").validateAddress,
    loadIsEditableOperation: () => require("../families/evm/operations").isEditableOperation,
    loadIsStuckOperation: () => require("../families/evm/operations").isStuckOperation,
    loadGetStuckAccountAndOperation: () => require("../families/evm/operations").getStuckAccountAndOperation,
  },
  {
    family: "filecoin",
    loadSetup: () => require("../families/filecoin/setup"),
    loadTransaction: () => require("@ledgerhq/coin-filecoin/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-filecoin/deviceTransactionConfig").default,
  },
  {
    family: "hedera",
    loadSetup: () => require("../families/hedera/setup"),
    loadTransaction: () => require("@ledgerhq/coin-hedera/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-hedera/deviceTransactionConfig").default,
  },
  {
    family: "icon",
    loadSetup: () => require("../families/icon/setup"),
    loadTransaction: () => require("@ledgerhq/coin-icon/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-icon/deviceTransactionConfig").default,
    loadAccount: () => require("@ledgerhq/coin-icon/account").default,
    loadMockBridge: () => require("../families/icon/bridge/mock").default,
  },
  {
    family: "internet_computer",
    loadSetup: () => require("../families/internet_computer/setup"),
    loadTransaction: () => require("@ledgerhq/coin-internet_computer/transaction").default,
    loadDeviceTxConfig: () =>
      require("@ledgerhq/coin-internet_computer/deviceTransactionConfig").default,
  },
  {
    family: "kaspa",
    loadSetup: () => require("../families/kaspa/setup"),
    loadTransaction: () => require("@ledgerhq/coin-kaspa/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-kaspa/deviceTransactionConfig").default,
  },
  {
    family: "mina",
    loadSetup: () => require("../families/mina/setup"),
    loadTransaction: () => require("@ledgerhq/coin-mina/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-mina/deviceTransactionConfig").default,
  },
  {
    family: "multiversx",
    loadSetup: () => require("../families/multiversx/setup"),
    loadTransaction: () => require("@ledgerhq/coin-multiversx/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-multiversx/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/multiversx/bridge/mock").default,
  },
  {
    family: "near",
    loadSetup: () => require("../families/near/setup"),
    loadTransaction: () => require("@ledgerhq/coin-near/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-near/deviceTransactionConfig").default,
    loadAccount: () => require("@ledgerhq/coin-near/account").default,
  },
  {
    family: "polkadot",
    loadSetup: () => require("../families/polkadot/setup"),
    loadTransaction: () => require("@ledgerhq/coin-polkadot/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-polkadot/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/polkadot/walletApiAdapter").default,
    loadPlatformAdapter: () => require("../families/polkadot/platformAdapter").default,
    loadMockBridge: () => require("../families/polkadot/bridge/mock").default,
  },
  {
    family: "solana",
    loadSetup: () => require("../families/solana/setup"),
    loadTransaction: () => require("@ledgerhq/coin-solana/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-solana/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/solana/walletApiAdapter").default,
    loadMockBridge: () => require("../families/solana/bridge/mock").default,
    loadValidateAddress: () =>
      require("@ledgerhq/coin-solana/logic/validateAddress").validateAddress,
  },
  {
    family: "stacks",
    loadSetup: () => require("../families/stacks/setup"),
    loadTransaction: () => require("@ledgerhq/coin-stacks/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-stacks/deviceTransactionConfig").default,
  },
  {
    family: "stellar",
    loadSetup: () => require("../families/stellar/setup"),
    loadTransaction: () => require("../families/stellar/transaction").default,
    loadDeviceTxConfig: () => require("../families/stellar/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/stellar/bridge/mock").default,
    loadValidateAddress: () =>
      require("@ledgerhq/coin-stellar/logic/validateAddress").validateAddress,
  },
  {
    family: "sui",
    loadSetup: () => require("../families/sui/setup"),
    loadTransaction: () => require("@ledgerhq/coin-sui/transaction").default,
    // No loadDeviceTxConfig: sui has no deviceTransactionConfig
  },
  {
    family: "tezos",
    loadSetup: () => require("../families/tezos/setup"),
    loadTransaction: () => require("@ledgerhq/coin-tezos/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-tezos/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/tezos/bridge/mock").default,
    loadGetVotesCount: () => require("../families/tezos/getVotesCount").getVotesCount,
    loadValidateAddress: () =>
      require("@ledgerhq/coin-tezos/logic/validateAddress").validateAddress,
  },
  {
    family: "ton",
    loadSetup: () => require("../families/ton/setup"),
    loadTransaction: () => require("@ledgerhq/coin-ton/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-ton/deviceTransactionConfig").default,
  },
  {
    family: "tron",
    loadSetup: () => require("../families/tron/setup"),
    loadTransaction: () => require("@ledgerhq/coin-tron/transaction").default,
    loadDeviceTxConfig: () => require("@ledgerhq/coin-tron/deviceTransactionConfig").default,
    loadMockBridge: () => require("../families/tron/bridge/mock").default,
    loadIsAccountEmpty: () => require("@ledgerhq/coin-tron/index").isAccountEmpty,
    loadGetVotesCount: () => require("../families/tron/getVotesCount").getVotesCount,
  },
  {
    family: "vechain",
    loadSetup: () => require("../families/vechain/setup"),
    loadTransaction: () => require("@ledgerhq/coin-vechain/transaction").default,
    // No loadDeviceTxConfig: vechain has no deviceTransactionConfig
    loadAccount: () => require("@ledgerhq/coin-vechain/account").default,
    loadMockAccount: () => require("@ledgerhq/coin-vechain/mock").default,
    loadIsAccountEmpty: () => require("@ledgerhq/coin-vechain").isAccountEmpty,
  },
  {
    family: "xrp",
    loadSetup: () => require("../families/xrp/setup"),
    loadTransaction: () => require("../families/xrp/transaction").default,
    loadDeviceTxConfig: () => require("../families/xrp/deviceTransactionConfig").default,
    loadWalletApiAdapter: () => require("../families/xrp/walletApiAdapter").default,
    loadPlatformAdapter: () => require("../families/xrp/platformAdapter").default,
    loadMockBridge: () => require("../families/xrp/bridge/mock").default,
    loadValidateAddress: () =>
      require("@ledgerhq/coin-xrp/logic/validateAddress").validateAddress,
  },
];
