import type { CoinModuleLoader } from "./types";

// Hand-maintained: one entry per family in families/*/
// currencyIds will be auto-derived from @ledgerhq/cryptoassets once PR #15878 lands.
//
// Note: loadSpecs is intentionally absent — bot specs live in bot/specs.ts as a static barrel.
//
// Note: the array is declared without a CoinModuleLoader[] annotation because TypeScript's
// CJS/ESM interop widens dynamic-import default-export types to `T | typeof Module`, making
// each loader field infer as `() => Promise<T | typeof Module>` instead of `() => Promise<T>`.
// This is a known TypeScript limitation; the concrete types are enforced at the registry level.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const coinModuleLoaders = ([
  {
    family: "aleo",
    currencyIds: ["aleo", "aleo_testnet"],
    loadSetup: () => import("../families/aleo/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-aleo/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-aleo/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "algorand",
    currencyIds: ["algorand"],
    loadSetup: () => import("../families/algorand/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-algorand/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-algorand/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/algorand/bridge/mock.js").then(m => m.default),
    loadMockAccount: () => import("@ledgerhq/coin-algorand/mock").then(m => m.default),
  },
  {
    family: "aptos",
    currencyIds: ["aptos", "aptos_testnet"],
    loadSetup: () => import("../families/aptos/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-aptos/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-aptos/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "bitcoin",
    currencyIds: [
      "bitcoin",
      "bitcoin_cash",
      "bitcoin_gold",
      "bitcoin_private",
      "clubcoin",
      "dash",
      "decred",
      "digibyte",
      "dogecoin",
      "game_credits",
      "hcash",
      "komodo",
      "LBRY",
      "litecoin",
      "nix",
      "poswallet",
      "qtum",
      "ravencoin",
      "resistance",
      "stakenet",
      "stratis",
      "zcash",
      "zclassic",
      "zcoin",
      "zencash",
      "bitcoin_testnet",
      "bitcoin_regtest",
    ],
    loadSetup: () => import("../families/bitcoin/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-bitcoin/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-bitcoin/deviceTransactionConfig").then(m => m.default),
    loadWalletApiAdapter: () =>
      import("../families/bitcoin/walletApiAdapter.js").then(m => m.default),
    loadPlatformAdapter: () =>
      import("../families/bitcoin/platformAdapter.js").then(m => m.default),
    loadAccount: () => import("@ledgerhq/coin-bitcoin/account").then(m => m.default),
    loadMockBridge: () => import("../families/bitcoin/bridge/mock.js").then(m => m.default),
  },
  {
    family: "canton",
    currencyIds: ["canton_network", "canton_network_testnet", "canton_network_devnet"],
    loadSetup: () => import("../families/canton/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-canton/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-canton/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/canton/bridge/mock.js").then(m => m.default),
  },
  {
    family: "cardano",
    currencyIds: ["cardano", "cardano_testnet"],
    loadSetup: () => import("../families/cardano/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-cardano/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-cardano/deviceTransactionConfig").then(m => m.default),
    loadAccount: () => import("@ledgerhq/coin-cardano/account").then(m => m.default),
    loadMockBridge: () => import("../families/cardano/bridge/mock.js").then(m => m.default),
  },
  {
    family: "casper",
    currencyIds: ["casper"],
    loadSetup: () => import("../families/casper/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-casper/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-casper/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/casper/bridge/mock.js").then(m => m.default),
  },
  {
    family: "celo",
    currencyIds: ["celo"],
    loadSetup: () => import("../families/celo/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-celo/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-celo/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "concordium",
    currencyIds: ["concordium", "concordium_testnet"],
    loadSetup: () => import("../families/concordium/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-concordium/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-concordium/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "cosmos",
    currencyIds: [
      "axelar",
      "coreum",
      "cosmos",
      "cosmos_testnet",
      "desmos",
      "dydx",
      "nyx",
      "persistence",
      "quicksilver",
      "secret_network",
      "stargaze",
      "osmo",
      "stride",
      "umee",
      "crypto_org",
      "crypto_org_croeseid",
      "injective",
      "binance_beacon_chain",
      "mantra",
      "xion",
      "zenrock",
      "babylon",
    ],
    loadSetup: () => import("../families/cosmos/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-cosmos/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-cosmos/deviceTransactionConfig").then(m => m.default),
    loadWalletApiAdapter: () =>
      import("../families/cosmos/walletApiAdapter.js").then(m => m.default),
    loadMockBridge: () => import("../families/cosmos/bridge/mock.js").then(m => m.default),
    loadMockAccount: () => import("@ledgerhq/coin-cosmos/mock").then(m => m.default),
  },
  {
    family: "evm",
    currencyIds: [
      "adi",
      "akroma",
      "atheios",
      "avalanche_c_chain",
      "avalanche_c_chain_fuji",
      "bitlayer",
      "bsc",
      "callisto",
      "dexon",
      "ellaism",
      "ethereum",
      "ethereum_classic",
      "ether1",
      "ethergem",
      "ethersocial",
      "expanse",
      "gochain",
      "hpb",
      "mix",
      "musicoin",
      "pirl",
      "poa",
      "polygon",
      "polygon_amoy",
      "reosc",
      "thundercore",
      "tomo",
      "ubiq",
      "wanchain",
      "ethereum_sepolia",
      "ethereum_hoodi",
      "sonic",
      "sonic_blaze",
      "arbitrum",
      "arbitrum_sepolia",
      "cronos",
      "core",
      "fantom",
      "flare",
      "songbird",
      "moonbeam",
      "rsk",
      "bittorrent",
      "optimism",
      "optimism_sepolia",
      "energy_web",
      "astar",
      "metis",
      "boba",
      "moonriver",
      "velas_evm",
      "syscoin",
      "telos_evm",
      "berachain",
      "sei_evm",
      "hyperevm",
      "polygon_zk_evm",
      "polygon_zk_evm_testnet",
      "base",
      "base_sepolia",
      "mantle",
      "mantle_sepolia",
      "klaytn",
      "klaytn_baobab",
      "neon_evm",
      "lukso",
      "linea",
      "linea_sepolia",
      "blast",
      "blast_sepolia",
      "scroll",
      "scroll_sepolia",
      "shape",
      "story",
      "etherlink",
      "zksync",
      "zksync_sepolia",
      "monad",
      "monad_testnet",
      "somnia",
      "zero_gravity",
      "unichain",
      "unichain_sepolia",
    ],
    loadSetup: () => import("../families/evm/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-evm/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-evm/deviceTransactionConfig").then(m => m.default),
    loadWalletApiAdapter: () => import("../families/evm/walletApiAdapter.js").then(m => m.default),
    loadPlatformAdapter: () => import("../families/evm/platformAdapter.js").then(m => m.default),
    loadMockBridge: () => import("../families/evm/bridge/mock.js").then(m => m.default),
  },
  {
    family: "filecoin",
    currencyIds: ["filecoin"],
    loadSetup: () => import("../families/filecoin/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-filecoin/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-filecoin/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "hedera",
    currencyIds: ["hedera"],
    loadSetup: () => import("../families/hedera/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-hedera/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-hedera/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "icon",
    currencyIds: ["icon", "icon_berlin_testnet"],
    loadSetup: () => import("../families/icon/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-icon/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-icon/deviceTransactionConfig").then(m => m.default),
    loadAccount: () => import("@ledgerhq/coin-icon/account").then(m => m.default),
    loadMockBridge: () => import("../families/icon/bridge/mock.js").then(m => m.default),
  },
  {
    family: "internet_computer",
    currencyIds: ["internet_computer"],
    loadSetup: () => import("../families/internet_computer/setup.js"),
    loadTransaction: () =>
      import("@ledgerhq/coin-internet_computer/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-internet_computer/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "kaspa",
    currencyIds: ["kaspa"],
    loadSetup: () => import("../families/kaspa/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-kaspa/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-kaspa/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "mina",
    currencyIds: ["mina"],
    loadSetup: () => import("../families/mina/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-mina/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-mina/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "multiversx",
    currencyIds: ["elrond"],
    loadSetup: () => import("../families/multiversx/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-multiversx/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-multiversx/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/multiversx/bridge/mock.js").then(m => m.default),
  },
  {
    family: "near",
    currencyIds: ["near"],
    loadSetup: () => import("../families/near/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-near/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-near/deviceTransactionConfig").then(m => m.default),
    loadAccount: () => import("@ledgerhq/coin-near/account").then(m => m.default),
  },
  {
    family: "polkadot",
    currencyIds: ["polkadot", "assethub_polkadot", "westend", "assethub_westend"],
    loadSetup: () => import("../families/polkadot/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-polkadot/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-polkadot/deviceTransactionConfig").then(m => m.default),
    loadWalletApiAdapter: () =>
      import("../families/polkadot/walletApiAdapter.js").then(m => m.default),
    loadPlatformAdapter: () =>
      import("../families/polkadot/platformAdapter.js").then(m => m.default),
    loadMockBridge: () => import("../families/polkadot/bridge/mock.js").then(m => m.default),
  },
  {
    family: "solana",
    currencyIds: ["solana", "solana_testnet", "solana_devnet"],
    loadSetup: () => import("../families/solana/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-solana/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-solana/deviceTransactionConfig").then(m => m.default),
    loadWalletApiAdapter: () =>
      import("../families/solana/walletApiAdapter.js").then(m => m.default),
    loadMockBridge: () => import("../families/solana/bridge/mock.js").then(m => m.default),
  },
  {
    family: "stacks",
    currencyIds: ["stacks"],
    loadSetup: () => import("../families/stacks/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-stacks/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-stacks/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "stellar",
    currencyIds: ["kin", "stellar"],
    loadSetup: () => import("../families/stellar/setup.js"),
    loadTransaction: () => import("../families/stellar/transaction.js").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("../families/stellar/deviceTransactionConfig.js").then(m => m.default),
    loadMockBridge: () => import("../families/stellar/bridge/mock.js").then(m => m.default),
  },
  {
    family: "sui",
    currencyIds: ["sui", "sui_testnet"],
    loadSetup: () => import("../families/sui/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-sui/transaction").then(m => m.default),
  },
  {
    family: "tezos",
    currencyIds: ["tezos"],
    loadSetup: () => import("../families/tezos/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-tezos/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-tezos/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/tezos/bridge/mock.js").then(m => m.default),
  },
  {
    family: "ton",
    currencyIds: ["ton"],
    loadSetup: () => import("../families/ton/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-ton/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-ton/deviceTransactionConfig").then(m => m.default),
  },
  {
    family: "tron",
    currencyIds: ["tron"],
    loadSetup: () => import("../families/tron/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-tron/transaction").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("@ledgerhq/coin-tron/deviceTransactionConfig").then(m => m.default),
    loadMockBridge: () => import("../families/tron/bridge/mock.js").then(m => m.default),
  },
  {
    family: "vechain",
    currencyIds: ["vechain"],
    loadSetup: () => import("../families/vechain/setup.js"),
    loadTransaction: () => import("@ledgerhq/coin-vechain/transaction").then(m => m.default),
    loadAccount: () => import("@ledgerhq/coin-vechain/account").then(m => m.default),
    loadMockAccount: () => import("@ledgerhq/coin-vechain/mock").then(m => m.default),
  },
  {
    family: "xrp",
    currencyIds: ["ripple"],
    loadSetup: () => import("../families/xrp/setup.js"),
    loadTransaction: () => import("../families/xrp/transaction.js").then(m => m.default),
    loadDeviceTxConfig: () =>
      import("../families/xrp/deviceTransactionConfig.js").then(m => m.default),
    loadWalletApiAdapter: () => import("../families/xrp/walletApiAdapter.js").then(m => m.default),
    loadPlatformAdapter: () => import("../families/xrp/platformAdapter.js").then(m => m.default),
    loadMockBridge: () => import("../families/xrp/bridge/mock.js").then(m => m.default),
  },
]) as unknown as CoinModuleLoader[];
