name: "Setup E2E tests Broadcast"
description: "Export DISABLE_TRANSACTION_BROADCAST env variable"
inputs:
  enable_broadcast:
    description: "Enable transaction broadcast"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Set DISABLE_TRANSACTION_BROADCAST
      id: set-broadcast
      shell: bash
      run: |
        enable_broadcast="${{ inputs.enable_broadcast }}"
        event_name="${{ github.event_name }}"
        cron_schedule="${{ github.event.schedule.cron }}"

        echo "enable_broadcast: $enable_broadcast"
        echo "event_name: $event_name"
        echo "cron_schedule: $cron_schedule"

        if [[ "$enable_broadcast" == "true" || ( "$event_name" == "schedule" && "$cron_schedule" == "0 5 * * 1" ) ]]; then
          echo "DISABLE_TRANSACTION_BROADCAST=0" >> $GITHUB_ENV
          echo "DISABLE_TRANSACTION_BROADCAST is set to 0"
        else
          echo "DISABLE_TRANSACTION_BROADCAST=1" >> $GITHUB_ENV
          echo "DISABLE_TRANSACTION_BROADCAST is set to 1"
        fi
