export enum LedgerRecoverSubscriptionStateEnum {
  BACKUP_DEVICE_CONNECTION = "BACKUP_DEVICE_CONNECTION",
  BACKUP_DONE = "BACKUP_DONE",
  BACKUP_VERIFY_IDENTITY = "BACKUP_VERIFY_IDENTITY",
  NO_SUBSCRIPTION = "NO_SUBSCRIPTION",
  STARGATE_SUBSCRIBE = "STARGATE_SUBSCRIBE",
}

export enum LedgerRecoverSubscriptionStateInProgressEnum {
  BACKUP_DEVICE_CONNECTION = LedgerRecoverSubscriptionStateEnum.BACKUP_DEVICE_CONNECTION,
  BACKUP_VERIFY_IDENTITY = LedgerRecoverSubscriptionStateEnum.BACKUP_VERIFY_IDENTITY,
  STARGATE_SUBSCRIBE = LedgerRecoverSubscriptionStateEnum.STARGATE_SUBSCRIBE,
}
