#!/usr/bin/env node

"use strict";

const path = require("path");
const fs = require("fs");
const deepmerge = require("deepmerge");

const BANNER = "Generated by @support/generate-config — edit tsconfig.config.json instead.";

function parseSpecifier(specifier) {
  const parts = specifier.split("/");
  const pkg = parts[0].startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0];
  const fragment = parts.slice(pkg.split("/").length).join("/");
  return { pkg, fragment };
}

function resolveFragment(specifier) {
  try {
    return require.resolve(specifier);
  } catch {
    const { pkg, fragment } = parseSpecifier(specifier);
    const pkgBase = pkg.split("/").pop();
    return path.join(__dirname, `../${pkgBase}/fragments/${fragment}.json`);
  }
}

function loadFragment(specifier) {
  const fragmentPath = resolveFragment(specifier);
  if (!fs.existsSync(fragmentPath)) {
    console.error(
      `[generate-tsconfig] Fragment not found: ${specifier} (resolved to ${fragmentPath})`,
    );
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(fragmentPath, "utf8"));
}

function parseCwd() {
  const args = process.argv.slice(2);
  const idx = args.indexOf("--cwd");
  if (idx !== -1 && args[idx + 1]) {
    return path.resolve(args[idx + 1]);
  }
  return process.cwd();
}

function writeJson(filePath, data) {
  const out = Object.assign({ "//": BANNER }, data);
  fs.writeFileSync(filePath, JSON.stringify(out, null, 2) + "\n", "utf8");
}

function main() {
  const cwd = parseCwd();
  const configPath = path.join(cwd, "tsconfig.config.json");

  if (!fs.existsSync(configPath)) {
    console.error(`[generate-tsconfig] No tsconfig.config.json found in ${cwd}`);
    process.exit(1);
  }

  const { extends: specifiers = [], ...packageOverrides } = JSON.parse(
    fs.readFileSync(configPath, "utf8"),
  );

  let root = {};
  let web = {};
  let native = {};
  let hasWeb = false;
  let hasNative = false;

  for (const specifier of specifiers) {
    const fragment = loadFragment(specifier);

    if (fragment.root) root = deepmerge(root, fragment.root);
    if (fragment.web) {
      web = deepmerge(web, fragment.web);
      hasWeb = true;
    }
    if (fragment.native) {
      native = deepmerge(native, fragment.native);
      hasNative = true;
    }
  }

  root = deepmerge(root, packageOverrides);

  writeJson(path.join(cwd, "tsconfig.json"), root);
  console.log("[generate-tsconfig] wrote tsconfig.json");

  if (hasWeb) {
    writeJson(path.join(cwd, "tsconfig.web.json"), web);
    console.log("[generate-tsconfig] wrote tsconfig.web.json");
  }
  if (hasNative) {
    writeJson(path.join(cwd, "tsconfig.native.json"), native);
    console.log("[generate-tsconfig] wrote tsconfig.native.json");
  }
}

main();
