name: "Upload Allure Report"
description: "Uploading allure report to Allure Server"
inputs:
  login:
    required: true
    description: "Allure Server Login"
  password:
    required: true
    description: "Allure Server Password"
  platform:
    required: true
    description: "Tested Platform"
  path:
    required: true
    description: "Report Path"
  report_path_suffix:
    required: false
    description: "Extra tag appended after the platform in the Allure project ID (e.g. manual, PR-checks)"
outputs:
  report-url:
    description: "Allure report URL"
    value: ${{ steps.publish-report.outputs.report-url }}

runs:
  using: composite

  steps:
    - id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Set report path
      id: report-path
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        BRANCH: ${{ steps.branch-name.outputs.current_branch }}
        PLATFORM: ${{ inputs.platform }}
        EXTRA_SUFFIX: ${{ inputs.report_path_suffix }}
      run: ${{ github.action_path }}/set-report-path.sh
    - name: Compress PNG files
      shell: bash
      run: ${{ github.action_path }}/compress-pngs.sh "${{ inputs.path }}"
    - name: Publish report on Allure Server
      id: publish-report
      shell: bash
      env:
        ALLURE_SERVER_URL: "https://allure-ledger-live.aws.sbx.ldg-tech.com"
        ALLURE_LOGIN: ${{ inputs.login }}
        ALLURE_PASSWORD: ${{ inputs.password }}
        PROJECT_ID: ${{ steps.report-path.outputs.path }}
        RESULTS_DIR: ${{ inputs.path }}
        BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        BUILD_NAME: ${{ github.workflow }}-${{ inputs.platform }}
      run: ${{ github.action_path }}/upload-to-allure.sh
    - name: Write Allure report in summary
      shell: bash
      run: echo "::notice title=${{ inputs.platform }} Allure report URL::${{ steps.publish-report.outputs.report-url }}"
