name: "Setup Env for Coin Tester"
description: "Installs deps, builds modules"
runs:
  using: "composite"
  steps:
    - run: pnpm i --filter="!./apps/**"
      shell: bash

    - run: pnpm exec nx run-many -t build --projects=tag:type:coin-tester
      shell: bash
