export const MOCK = [
  {
    $type: "Token",
    contract: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
    data: {
      img: "https://assets.coingecko.com/coins/images/325/large/Tether.png?1668148663",
      marketCapRank: 3,
    },
    ledgerId: "polygon/erc20/(pos)_tether_usd",
    name: "(PoS) Tether USD",
    network: "polygon",
    providerId: "tether",
    reason: null,
    status: "Ok",
    ticker: "USDT",
  },
  {
    $type: "Token",
    contract: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    data: {
      img: "https://assets.coingecko.com/coins/images/325/large/Tether.png?1668148663",
      marketCapRank: 3,
    },
    ledgerId: "ethereum/erc20/usd_tether__erc20_",
    name: "Tether USD",
    network: "ethereum",
    providerId: "tether",
    reason: null,
    status: "Ok",
    ticker: "USDT",
  },
  {
    $type: "Token",
    contract: "0x55d398326f99059ff775485246999027b3197955",
    data: {
      img: "https://assets.coingecko.com/coins/images/325/large/Tether.png?1668148663",
      marketCapRank: 3,
    },
    ledgerId: "bsc/bep20/binance-peg_bsc-usd",
    name: "Binance-Peg BSC-USD",
    network: "bsc",
    providerId: "tether",
    reason: null,
    status: "Ok",
    ticker: "BSC-USD",
  },
];

export const MOCK_POL = [
  {
    $type: "Token",
    ledgerId: "bsc/bep20/matic_token",
    providerId: "matic-network",
    name: "Matic Token",
    ticker: "MATIC",
    network: "bsc",
    contract: "0xcc42724c6683b7e57334c4e856f4c9965ed682bd",
    status: "Ok",
    reason: null,
    data: {
      img: "https://proxycgassets.api.live.ledger.com/coins/images/4713/large/polygon.png",
      marketCapRank: 121,
    },
  },
  {
    $type: "Coin",
    ledgerId: "polygon",
    providerId: "matic-network",
    name: "Polygon",
    ticker: "POL",
    status: "Ok",
    reason: "Overridden",
    data: {
      img: "https://proxycgassets.api.live.ledger.com/coins/images/4713/large/polygon.png",
      marketCapRank: 121,
    },
  },
  {
    $type: "Token",
    ledgerId: "ethereum/erc20/matic",
    providerId: "matic-network",
    name: "Matic",
    ticker: "MATIC",
    network: "ethereum",
    contract: "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0",
    status: "Ok",
    reason: null,
    data: {
      img: "https://proxycgassets.api.live.ledger.com/coins/images/4713/large/polygon.png",
      marketCapRank: 121,
    },
  },
];
