source "https://rubygems.org"

gem "fastlane"
gem "dotenv"
gem 'cocoapods', '>= 1.11.3'
gem "semver2", "~> 3.4", ">= 3.4.2"

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
