source "https://rubygems.org"

gem "fastlane", '~> 2.228.0'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem "dotenv"
# CocoaPods 1.16.2 fixes "pathname contains null byte" with pnpm symlinks (CocoaPods/CocoaPods#12798).
gem 'cocoapods', '1.16.2'
gem "semver2", "~> 3.4", ">= 3.4.2"
gem 'concurrent-ruby', '< 1.3.4'

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)

