require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ledgerlivemobile' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods for ledgerlivemobile
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  pod 'djinni_objc', :path => '../node_modules/@ledgerhq/react-native-ledger-core'
  pod 'ledger-core-objc', :path => '../node_modules/@ledgerhq/react-native-ledger-core'
  pod 'RNLibLedgerCore', :path => '../node_modules/@ledgerhq/react-native-ledger-core'

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  target 'ledgerlivemobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
