require("../../../families/algorand/tokens").add("asa", [
    ["438840","M-TSLA","Micro-Tesla", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438839","M-AAPL", "Micro-Apple", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438838","M-GOOGL", "Micro-Google", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438837","M-NFLX", "Micro-Netflix", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438836","M-TWTR", "Micro-Twitter", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438833","M-AMZN", "Micro-Amazon", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438832","M-MSFT", "Micro-Microsoft", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 0],
    ["438831","MESX", "MESE Index Fund", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 6],
    ["438828","USD-MESE", "MESE USD Exchange Token", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 6],
    ["312769","USDt", "Tether USDt", "XIU7HGGAJ3QOTATPDSIIHPFVKMICXKHMOR2FJKHTVLII4FAOA3CYZQDLG4", 6],
    ["163650","ARCC", "Asia Reserve Currency Coin", "MESEJMPXKL7YUWEQGNRCKSLMQDKHOHWIZ3RBWP7BV4JDMUJXFUVQZWUBJM", 6],
]);