#!/usr/bin/env bash

set -euo pipefail

#MISE description="Install and setup mitmproxy. Automatically detect the host OS and configure it. Optionally configure the iOS/Android Simulator."
#MISE tools={mitmproxy="12.2.1"}
#MISE raw=true

#USAGE flag "--setup-ios-simulator [boolean]" default="false" help="Configure iOS Simulator"
#USAGE flag "--setup-android-simulator [boolean]" default="false" help="Configure Android Simulator"
#USAGE flag "--ios-simulator-name [name]" default="iOS Simulator" help="Simulator name to be configured"
#USAGE flag "--android-simulator-name [name]" default="avd-emulator" help="Simulator name to be configured"
#USAGE flag "--port [number]" default="8080" help="Port where mitmproxy will listen to"
#USAGE flag "--mock-responses-file [path]" help="Path to a JSON file of mocked responses (enables mock_responses addon)"

CONF_DIR="${HOME}/.mitmproxy"
CERT="${CONF_DIR}/mitmproxy-ca-cert.pem"

# Disable colors when not in a terminal or when NO_COLOR is set (e.g. CI log parsers)
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
	_RED="\033[0;31m" _CYAN="\033[0;36m" _GREEN="\033[0;32m" _RESET="\033[0m"
else
	_RED="" _CYAN="" _GREEN="" _RESET=""
fi

log_error() {
	echo -e "${_RED}[ERROR]${_RESET} ${*}" >&2
	exit 1
}
log_info() { echo -e "${_CYAN}[INFO]${_RESET} ${*}"; }
log_success() { echo -e "${_GREEN}[SUCCESS]${_RESET} ${*}"; }

function setup_macos() {
	# Configure host to use mitmproxy
	log_info "Configure host to use mitmproxy"

	local NETWORK_SERVICE
	NETWORK_SERVICE=$(/usr/sbin/networksetup -listallnetworkservices | grep -iE "wi-fi|ethernet|airport" | head -1)

	if [ -z "$NETWORK_SERVICE" ]; then
		log_error "Failed to detect network service"
	fi

	log_info "Using network service: $NETWORK_SERVICE"
	log_info "Adding certificate to host OS"

	sudo security add-trusted-cert -d -p ssl -p basic -k /Library/Keychains/System.keychain "${CERT}"

	# Set Web Proxy in the macOS system
	/usr/sbin/networksetup -setwebproxy "$NETWORK_SERVICE" 127.0.0.1 ${usage_port}
	/usr/sbin/networksetup -setwebproxystate "$NETWORK_SERVICE" on
	/usr/sbin/networksetup -setsecurewebproxy "$NETWORK_SERVICE" 127.0.0.1 ${usage_port}
	/usr/sbin/networksetup -setsecurewebproxystate "$NETWORK_SERVICE" on

	if [ -n "${GITHUB_ENV:-}" ]; then
		local PROXY_URL="http://127.0.0.1:${usage_port}"
		local NO_PROXY_VALUE="localhost,127.0.0.1,169.254.169.254,::1"
		log_info "GitHub Actions detected: writing proxy vars to \$GITHUB_ENV"
		for VAR in http_proxy https_proxy HTTP_PROXY HTTPS_PROXY; do
			echo "${VAR}=${PROXY_URL}" >>"${GITHUB_ENV}"
		done
		for VAR in no_proxy NO_PROXY; do
			echo "${VAR}=${NO_PROXY_VALUE}" >>"${GITHUB_ENV}"
		done
		echo "NODE_EXTRA_CA_CERTS=${CERT}" >>"${GITHUB_ENV}"
	fi

	log_success "macOS proxy configuration complete"
}

function setup_ios_simulator() {
	if [ "${usage_setup_ios_simulator}" != "true" ]; then
		return
	fi

	local SIMULATOR_NAME="${usage_ios_simulator_name}"

	log_info "Setting up the iOS simulator: ${usage_setup_ios_simulator} ${SIMULATOR_NAME}"

	log_info "Use simctl to set emulator"
	# Get the UDID of the simulator Detox is using
	xcrun simctl list devices

	log_info "Boot the simulator: ${SIMULATOR_NAME}"
	xcrun simctl boot "${SIMULATOR_NAME}" || true

	log_info "List simulators, ensure it's booted"
	xcrun simctl list devices

	# 2. Add the certificate to the simulator
	# Path to the cert generated by mitmproxy on the runner
	log_info "Add certificate to simulator: ${SIMULATOR_NAME}"
	xcrun simctl keychain "${SIMULATOR_NAME}" add-root-cert "${CERT}"
}

function setup_linux() {
	log_info "Configure host to use mitmproxy"

	log_info "Adding certificate to host OS"
	if command -v update-ca-certificates &>/dev/null; then
		# Debian/Ubuntu
		log_info "Detected system as Debian/Ubuntu"
		sudo cp "${CERT}" /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
		sudo update-ca-certificates
	elif command -v update-ca-trust &>/dev/null; then
		# RHEL/CentOS/Fedora
		log_info "Detected system as RHEL/CentOS/Fedora"
		sudo cp "${CERT}" /etc/pki/ca-trust/source/anchors/mitmproxy-ca-cert.pem
		sudo update-ca-trust extract
	else
		log_error "Unsupported Linux distribution: cannot install CA certificate"
	fi

	log_info "Setting webproxy on host OS"
	if command -v gsettings &>/dev/null && gsettings list-schemas 2>/dev/null | grep -q "^org.gnome.system.proxy$"; then
		gsettings set org.gnome.system.proxy mode 'manual'
		gsettings set org.gnome.system.proxy.http host '127.0.0.1'
		gsettings set org.gnome.system.proxy.http port ${usage_port}
		gsettings set org.gnome.system.proxy.https host '127.0.0.1'
		gsettings set org.gnome.system.proxy.https port ${usage_port}
	else
		log_info "GNOME proxy schema not available, skipping gsettings proxy configuration"
	fi

	# Set system-wide proxy environment variables.
	# /etc/environment is read at login shell startup (PAM/SSH), so it covers
	# local dev usage but has no effect on GitHub Actions, where each step is
	# a new process spawned from the runner agent — not a login shell.
	local ENV_FILE="/etc/environment"
	local PROXY_URL="http://127.0.0.1:${usage_port}"
	local NO_PROXY_VALUE="localhost,127.0.0.1,169.254.169.254,::1"
	for VAR in http_proxy https_proxy HTTP_PROXY HTTPS_PROXY; do
		if grep -q "^${VAR}=" "${ENV_FILE}" 2>/dev/null; then
			sudo sed -i "s|^${VAR}=.*|${VAR}=\"${PROXY_URL}\"|" "${ENV_FILE}"
		else
			echo "${VAR}=\"${PROXY_URL}\"" | sudo tee -a "${ENV_FILE}" >/dev/null
		fi
	done
	for VAR in no_proxy NO_PROXY; do
		if grep -q "^${VAR}=" "${ENV_FILE}" 2>/dev/null; then
			sudo sed -i "s|^${VAR}=.*|${VAR}=\"${NO_PROXY_VALUE}\"|" "${ENV_FILE}"
		else
			echo "${VAR}=\"${NO_PROXY_VALUE}\"" | sudo tee -a "${ENV_FILE}" >/dev/null
		fi
	done

	# In GitHub Actions, $GITHUB_ENV is a file that the runner agent reads
	# between steps and injects into the environment of every subsequent step.
	# This is the only reliable way to propagate env vars across steps.
	# The guard ensures this block is skipped outside of GitHub Actions.
	if [ -n "${GITHUB_ENV:-}" ]; then
		log_info "GitHub Actions detected: writing proxy vars to \$GITHUB_ENV"
		for VAR in http_proxy https_proxy HTTP_PROXY HTTPS_PROXY; do
			echo "${VAR}=${PROXY_URL}" >>"${GITHUB_ENV}"
		done
		for VAR in no_proxy NO_PROXY; do
			echo "${VAR}=${NO_PROXY_VALUE}" >>"${GITHUB_ENV}"
		done
		echo "NODE_EXTRA_CA_CERTS=${CERT}" >>"${GITHUB_ENV}"
	fi

	log_success "Linux proxy configuration complete"
}

function generate_certificate() {

	if [ ! -f "${CERT}" ]; then
		log_info "Certificate does not exist. Creating..."

		# Generate certificate first if it doesn't exist
		mitmdump --set confdir="${CONF_DIR}" --listen-port ${usage_port} --showhost &
		local MITMPROXY_PID=$!

		for i in $(seq 1 10); do
			[ -f "${CERT}" ] && break
			sleep 1
		done

		kill $MITMPROXY_PID 2>/dev/null || true
		wait $MITMPROXY_PID 2>/dev/null || true

		if [ -f "${CERT}" ]; then
			log_success "Created certificate" "${CERT}"
		else
			log_error "Failed to create certificate" "${CERT}"
		fi

	else
		log_info "Certificate already exists. Skipping creation."
	fi
}

function start_mitmproxy() {
	local LOG_DIR="${HOME}/.mitmproxy/logs"
	local LOG_FILE="${LOG_DIR}/mitmproxy.log"
	local FLOW_FILE="${LOG_DIR}/mitmproxy.flows"

	mkdir -p "${LOG_DIR}"

	log_info "Starting mitmproxy on port ${usage_port}, logging to ${LOG_FILE}"

	local ADDON_ARGS=()
	if [ -n "${usage_mock_responses_file:-}" ]; then
		log_info "Mock responses enabled: ${usage_mock_responses_file}"
		ADDON_ARGS+=(-s "$(dirname "$0")/mock_responses.py" --set "mock_responses_file=${usage_mock_responses_file}")
	fi

	mitmdump \
		--set confdir="${CONF_DIR}" \
		--listen-port "${usage_port}" \
		--showhost \
		"${ADDON_ARGS[@]}" \
		-w "${FLOW_FILE}" \
		>"${LOG_FILE}" 2>&1 &

	local MITMPROXY_PID=$!

	# Wait up to 10 seconds for mitmproxy to be ready
	local READY=false
	for i in $(seq 1 10); do
		if ! kill -0 "${MITMPROXY_PID}" 2>/dev/null; then
			log_error "mitmproxy process died unexpectedly. Check logs: ${LOG_FILE}"
		fi
		if (echo >/dev/tcp/127.0.0.1/${usage_port}) 2>/dev/null; then
			READY=true
			break
		fi
		sleep 1
	done

	if [ "${READY}" != "true" ]; then
		log_error "mitmproxy did not start within 10 seconds. Check logs: ${LOG_FILE}"
	fi

	log_success "mitmproxy started (PID: ${MITMPROXY_PID})"
	log_info "Flows: ${FLOW_FILE}"
	log_info "Logs:  ${LOG_FILE}"

	export MITMPROXY_PID

	# In GitHub Actions, propagate the PID to subsequent steps via $GITHUB_ENV
	if [ -n "${GITHUB_ENV:-}" ]; then
		log_info "GitHub Actions detected: writing MITMPROXY_PID to \$GITHUB_ENV"
		echo "MITMPROXY_PID=${MITMPROXY_PID}" >>"${GITHUB_ENV}"
	fi
}

function main() {
	generate_certificate

	case "${OSTYPE}" in
	darwin*)
		setup_macos
		setup_ios_simulator
		;;
	linux*) setup_linux ;;
	*)
		echo "Unknown system can't setup mitmproxy"
		return 1
		;;
	esac

	start_mitmproxy
}

main "${@}"
