const mockGroupedCurrenciesBySingleProviderData = {
  currenciesByProvider: [
    {
      providerId: "bitcoin",
      currenciesByNetwork: [
        {
          type: "CryptoCurrency",
          id: "bitcoin",
          coinType: 0,
          name: "Bitcoin",
          managerAppName: "Bitcoin",
          ticker: "BTC",
          scheme: "bitcoin",
          color: "#ffae35",
          symbol: "Ƀ",
          units: [
            { name: "bitcoin", code: "BTC", magnitude: 8 },
            { name: "mBTC", code: "mBTC", magnitude: 5 },
            { name: "bit", code: "bit", magnitude: 2 },
            { name: "satoshi", code: "sat", magnitude: 0 },
          ],
          supportsSegwit: true,
          supportsNativeSegwit: true,
          family: "bitcoin",
          blockAvgTime: 900,
          bitcoinLikeInfo: { P2PKH: 0, P2SH: 5, XPUBVersion: 76067358 },
          explorerViews: [
            {
              address: "https://blockstream.info/address/$address",
              tx: "https://blockstream.info/tx/$hash",
            },
            {
              address: "https://www.blockchain.com/btc/address/$address",
              tx: "https://blockchain.info/btc/tx/$hash",
            },
          ],
          keywords: ["btc", "bitcoin"],
          explorerId: "btc",
        },
      ],
    },
  ],
  sortedCryptoCurrencies: [
    {
      type: "CryptoCurrency",
      id: "bitcoin",
      coinType: 0,
      name: "Bitcoin",
      managerAppName: "Bitcoin",
      ticker: "BTC",
      scheme: "bitcoin",
      color: "#ffae35",
      symbol: "Ƀ",
      units: [
        { name: "bitcoin", code: "BTC", magnitude: 8 },
        { name: "mBTC", code: "mBTC", magnitude: 5 },
        { name: "bit", code: "bit", magnitude: 2 },
        { name: "satoshi", code: "sat", magnitude: 0 },
      ],
      supportsSegwit: true,
      supportsNativeSegwit: true,
      family: "bitcoin",
      blockAvgTime: 900,
      bitcoinLikeInfo: { P2PKH: 0, P2SH: 5, XPUBVersion: 76067358 },
      explorerViews: [
        {
          address: "https://blockstream.info/address/$address",
          tx: "https://blockstream.info/tx/$hash",
        },
        {
          address: "https://www.blockchain.com/btc/address/$address",
          tx: "https://blockchain.info/btc/tx/$hash",
        },
      ],
      keywords: ["btc", "bitcoin"],
      explorerId: "btc",
    },
  ],
};

const mockGroupedCurrenciesWithMultipleProviderData = {
  currenciesByProvider: [
    {
      providerId: "ethereum",
      currenciesByNetwork: [
        {
          type: "CryptoCurrency",
          id: "ethereum",
          coinType: 60,
          name: "Ethereum",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "ethereum",
          color: "#0ebdcd",
          symbol: "Ξ",
          family: "evm",
          blockAvgTime: 15,
          units: [
            { name: "ether", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 1 },
          explorerViews: [
            {
              tx: "https://etherscan.io/tx/$hash",
              address: "https://etherscan.io/address/$address",
              token: "https://etherscan.io/token/$contractAddress?a=$address",
            },
          ],
          keywords: ["eth", "ethereum"],
          explorerId: "eth",
        },
        {
          type: "CryptoCurrency",
          id: "zksync",
          coinType: 60,
          name: "ZKsync",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "zksync",
          color: "#000000",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 324 },
          explorerViews: [
            {
              tx: "https://explorer.zksync.io/tx/$hash",
              address: "https://explorer.zksync.io/address/$address",
              token: "https://explorer.zksync.io/token/$contractAddress?a=$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "scroll",
          coinType: 60,
          name: "Scroll",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "scroll",
          color: "#ebc28e",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          disableCountervalue: false,
          ethereumLikeInfo: { chainId: 534352 },
          explorerViews: [
            {
              tx: "https://scrollscan.com/tx/$hash",
              address: "https://scrollscan.com/address/$address",
              token: "https://scrollscan.com/token/$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "optimism",
          coinType: 60,
          name: "OP Mainnet",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "optimism",
          color: "#FF0421",
          family: "evm",
          units: [
            { name: "ether", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 10 },
          explorerViews: [
            {
              tx: "https://optimistic.etherscan.io/tx/$hash",
              address: "https://optimistic.etherscan.io/address/$address",
              token: "https://optimistic.etherscan.io/token/$contractAddress?a=$address",
            },
          ],
          keywords: ["optimism"],
        },
        {
          type: "CryptoCurrency",
          id: "linea",
          coinType: 60,
          name: "Linea",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "linea",
          color: "#000000",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          disableCountervalue: false,
          ethereumLikeInfo: { chainId: 59144 },
          explorerViews: [
            {
              tx: "https://lineascan.build/tx/$hash",
              address: "https://lineascan.build/address/$address",
              token: "https://lineascan.build/token/$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "base",
          coinType: 60,
          name: "Base",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "base",
          color: "#1755FE",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 8453 },
          explorerViews: [
            {
              tx: "https://basescan.org/tx/$hash",
              address: "https://basescan.org/address/$address",
              token: "https://basescan.org/token/$contractAddress?a=$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "arbitrum",
          coinType: 60,
          name: "Arbitrum",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "arbitrum",
          color: "#28a0f0",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 42161 },
          explorerViews: [
            {
              tx: "https://arbiscan.io/tx/$hash",
              address: "https://arbiscan.io/address/$address",
              token: "https://arbiscan.io/token/$contractAddress?a=$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "blast",
          coinType: 60,
          name: "Blast",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "blast",
          color: "#FCFC06",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          disableCountervalue: false,
          ethereumLikeInfo: { chainId: 81457 },
          explorerViews: [
            {
              tx: "https://blastscan.io/tx/$hash",
              address: "https://blastscan.io/address/$address",
              token: "https://blastscan.io/token/$address",
            },
          ],
        },
        {
          type: "CryptoCurrency",
          id: "boba",
          coinType: 60,
          name: "Boba",
          managerAppName: "Ethereum",
          ticker: "ETH",
          scheme: "boba",
          color: "#CBFF00",
          family: "evm",
          units: [
            { name: "ETH", code: "ETH", magnitude: 18 },
            { name: "Gwei", code: "Gwei", magnitude: 9 },
            { name: "Mwei", code: "Mwei", magnitude: 6 },
            { name: "Kwei", code: "Kwei", magnitude: 3 },
            { name: "wei", code: "wei", magnitude: 0 },
          ],
          ethereumLikeInfo: { chainId: 288 },
          explorerViews: [
            {
              tx: "https://bobascan.com/tx/$hash",
              address: "https://bobascan.com/address/$address",
              token: "https://bobascan.com/token/$contractAddress?a=$address",
            },
          ],
        },
      ],
    },
  ],
  sortedCryptoCurrencies: [
    {
      type: "CryptoCurrency",
      id: "ethereum",
      coinType: 60,
      name: "Ethereum",
      managerAppName: "Ethereum",
      ticker: "ETH",
      scheme: "ethereum",
      color: "#0ebdcd",
      symbol: "Ξ",
      family: "evm",
      blockAvgTime: 15,
      units: [
        { name: "ether", code: "ETH", magnitude: 18 },
        { name: "Gwei", code: "Gwei", magnitude: 9 },
        { name: "Mwei", code: "Mwei", magnitude: 6 },
        { name: "Kwei", code: "Kwei", magnitude: 3 },
        { name: "wei", code: "wei", magnitude: 0 },
      ],
      ethereumLikeInfo: { chainId: 1 },
      explorerViews: [
        {
          tx: "https://etherscan.io/tx/$hash",
          address: "https://etherscan.io/address/$address",
          token: "https://etherscan.io/token/$contractAddress?a=$address",
        },
      ],
      keywords: ["eth", "ethereum"],
      explorerId: "eth",
    },
  ],
};

export { mockGroupedCurrenciesBySingleProviderData, mockGroupedCurrenciesWithMultipleProviderData };
