export const URL_ORIGIN = "https://live-app-catalog.ledger.com";

export const RECENTLY_USED_KEY = "WEB3HUB_RECENTLY_USED";
export const DISSMISSED_MANIFETS_KEY = "WEB3HUB_DISSMISSED_MANIFETS";
export const TAB_HISTORY_KEY = "WEB3HUB_TAB_HISTORY";
export const WEB3HUB_KEYS = [RECENTLY_USED_KEY, DISSMISSED_MANIFETS_KEY, TAB_HISTORY_KEY];
