export enum DeviceLabels {
  Continue = "Continue",
  Amount = "Amount",
  Address = "Address",
  Reject = "Reject",
  Sign = "Sign",
  Approve = "Approve",
  Accept = "Accept",
  Transfer = "Transfer",
  Recipient = "Recipient",
  Pubkey = "Pubkey",
  Dest = "Dest",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  To = "To",
  Cancel = "Cancel",
  TODO = "",
}
