export enum DeviceLabels {
  CONTINUE = "Continue",
  AMOUT = "Amount",
  ADDRESS = "Address",
  REJECT = "Reject",
  SIGN = "Sign",
  APPROVE = "Approve",
  ACCEPT = "Accept",
  TRANSFER = "Transfer",
  RECIPIENT = "Recipient",
  PUBKEY = "Pubkey",
  DEST = "Dest",
  CAPS_APPROVE = "APPROVE",
  CAPS_REJECT = "REJECT",
  TO = "To",
  CANCEL = "Cancel",
  ACCOUNT = "Account",
  DESTINATION = "Destination",
}
