import { AppInfos } from "./AppInfos";
import { Network } from "./Network";
export type CurrencyType = Currency;
export declare class Currency {
    readonly name: string;
    readonly ticker: string;
    readonly id: string;
    readonly speculosApp: AppInfos;
    readonly networks: Network[];
    readonly contractAddress?: string | undefined;
    constructor(name: string, ticker: string, id: string, speculosApp: AppInfos, networks: Network[], contractAddress?: string | undefined);
    toString(): string;
    static readonly CELO: Currency;
    static readonly INJ: Currency;
    static readonly BTC: Currency;
    static readonly APT: Currency;
    static readonly ZEC: Currency;
    static readonly KAS: Currency;
    static readonly HBAR: Currency;
    static readonly tBTC: Currency;
    static readonly DOGE: Currency;
    static readonly ETH: Currency;
    static readonly sepETH: Currency;
    static readonly ETC: Currency;
    static readonly SOL: Currency;
    static readonly DOT: Currency;
    static readonly TRX: Currency;
    static readonly XRP: Currency;
    static readonly ADA: Currency;
    static readonly XLM: Currency;
    static readonly BCH: Currency;
    static readonly ALGO: Currency;
    static readonly ATOM: Currency;
    static readonly XTZ: Currency;
    static readonly POL: Currency;
    static readonly BSC: Currency;
    static readonly TON: Currency;
    static readonly ETH_USDT: Currency;
    static readonly ETH_USDC: Currency;
    static readonly ETH_LIDO: Currency;
    static readonly XLM_USDC: Currency;
    static readonly ALGO_USDT: Currency;
    static readonly TRX_USDT: Currency;
    static readonly TRX_BTT: Currency;
    static readonly BSC_BUSD: Currency;
    static readonly POL_DAI: Currency;
    static readonly POL_UNI: Currency;
    static readonly NEAR: Currency;
    static readonly OSMO: Currency;
    static readonly MULTIVERS_X: Currency;
    static readonly LTC: Currency;
    static readonly SOL_GIGA: Currency;
    static readonly SOL_WIF: Currency;
    static readonly OP: Currency;
    static readonly SUI: Currency;
    static readonly BASE: Currency;
    static readonly VET: Currency;
    static readonly MINA: Currency;
    static readonly SUI_USDC: Currency;
    static readonly ALEO: Currency;
    static readonly ICP: Currency;
    static readonly CCD_TESTNET: Currency;
    static readonly SEI_EVM: Currency;
}
//# sourceMappingURL=Currency.d.ts.map