import { z } from "zod";

import { BigNumberSchema } from "../../external/bignumber/schema";

export const OperationTypeSchema = z.enum([
  "IN",
  "OUT",
  "NONE",
  "CREATE",
  "REVEAL",
  "UNKNOWN",
  "DELEGATE",
  "UNDELEGATE",
  "REDELEGATE",
  "REWARD",
  "FEES",
  "FREEZE",
  "UNFREEZE",
  "WITHDRAW_EXPIRE_UNFREEZE",
  "UNDELEGATE_RESOURCE",
  "LEGACY_UNFREEZE",
  "VOTE",
  "REWARD_PAYOUT",
  "BOND",
  "UNBOND",
  "WITHDRAW_UNBONDED",
  "SET_CONTROLLER",
  "SLASH",
  "NOMINATE",
  "CHILL",
  "APPROVE",
  "OPT_IN",
  "OPT_OUT",
  "LOCK",
  "UNLOCK",
  "WITHDRAW",
  "REVOKE",
  "ACTIVATE",
  "REGISTER",
  "STAKE",
  "UNSTAKE",
  "WITHDRAW_UNSTAKED",
  "BURN",
  "ASSOCIATE_TOKEN",
  "CONTRACT_CALL",
  "UPDATE_ACCOUNT",
  "PRE_APPROVAL",
  "TRANSFER_PROPOSAL",
  "TRANSFER_REJECTED",
  "TRANSFER_WITHDRAWN",
]);

export const OperationSchema: z.ZodType<unknown> = z.lazy(() =>
  z.object({
    id: z.string(),
    hash: z.string(),
    type: OperationTypeSchema,
    value: BigNumberSchema,
    fee: BigNumberSchema,
    senders: z.array(z.string()),
    recipients: z.array(z.string()),
    blockHeight: z.number().nullable().optional(),
    blockHash: z.string().nullable().optional(),
    transactionSequenceNumber: BigNumberSchema.optional(),
    accountId: z.string(),
    standard: z.string().optional(),
    operator: z.string().optional(),
    contract: z.string().optional(),
    tokenId: z.string().optional(),
    date: z.date(),
    hasFailed: z.boolean().optional(),
    subOperations: z.array(OperationSchema).optional(),
    internalOperations: z.array(OperationSchema).optional(),
    transactionRaw: z.unknown().optional(),
    extra: z.unknown(),
  }),
);

export const OperationHistoryByAccountSchema = z.record(
  z.string(),
  z.array(OperationSchema),
);
