import { getCryptoCurrencyById } from "@ledgerhq/cryptoassets/currencies";
import type { TokenCurrency } from "@ledgerhq/types-cryptoassets";

const STABLECOIN_TOKENS_BY_CURRENCY: Record<string, TokenCurrency[]> = {
  ethereum: [
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/usd__coin",
      contractAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "USD Coin",
      ticker: "USDC",
      units: [{ name: "USD Coin", code: "USDC", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/usd_tether__erc20_",
      contractAddress: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "Tether USD",
      ticker: "USDT",
      units: [{ name: "Tether USD", code: "USDT", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/dai_stablecoin_v2_0",
      contractAddress: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "Dai Stablecoin",
      ticker: "DAI",
      units: [{ name: "Dai Stablecoin", code: "DAI", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/usde",
      contractAddress: "0x4c9EDD5852cd905f086C759E8383e09bff1E68B3",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "USDe",
      ticker: "USDe",
      units: [{ name: "USDe", code: "USDe", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/usds_stablecoin_0xdc035d45d973e3ec169d2276ddab16f1e407384f",
      contractAddress: "0xdC035D45d973E3EC169d2276DDab16f1e407384F",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "USDS Stablecoin",
      ticker: "USDS",
      units: [{ name: "USDS Stablecoin", code: "USDS", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/paypal_usd",
      contractAddress: "0x6c3ea9036406852006290770BEdFcAbA0e23A0e8",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "PayPal USD",
      ticker: "PYUSD",
      units: [{ name: "PayPal USD", code: "PYUSD", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/paxos_standard__pax_",
      contractAddress: "0x8E870D67F660D95d5be86380c7bA159c3B26252c",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "Paxos USD",
      ticker: "USDP",
      units: [{ name: "Paxos USD", code: "USDP", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/trueusd",
      contractAddress: "0x0000000000085d4780B73119b644AE5ecd22b376",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "TrueUSD",
      ticker: "TUSD",
      units: [{ name: "TrueUSD", code: "TUSD", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/stasis_eurs_token",
      contractAddress: "0xdB25f211AB05b1c97D595516F45794528a807ad8",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "STASIS EURO",
      ticker: "EURS",
      units: [{ name: "STASIS EURO", code: "EURS", magnitude: 2 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/frax",
      contractAddress: "0x853d955aCEf822Db058eb8505911ED77F175b99e",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "Frax",
      ticker: "FRAX",
      units: [{ name: "Frax", code: "FRAX", magnitude: 18 }],
    },
    {
      type: "TokenCurrency",
      id: "ethereum/erc20/lusd_stablecoin",
      contractAddress: "0x5f98805A4E8be255a32880FDeC7F6728C6568bA0",
      parentCurrency: getCryptoCurrencyById("ethereum"),
      tokenType: "erc20",
      name: "LUSD Stablecoin",
      ticker: "LUSD",
      units: [{ name: "LUSD Stablecoin", code: "LUSD", magnitude: 18 }],
    },
  ],
  tron: [
    {
      type: "TokenCurrency",
      id: "tron/trc20/tr7nhqjekqxgtci8q8zy4pl8otszgjlj6t",
      contractAddress: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
      parentCurrency: getCryptoCurrencyById("tron"),
      tokenType: "trc20",
      name: "Tether USD",
      ticker: "USDT",
      units: [{ name: "Tether USD", code: "USDT", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "tron/trc20/tekxitehnzsmse2xqrbj4w32run966rdz8",
      contractAddress: "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8",
      parentCurrency: getCryptoCurrencyById("tron"),
      tokenType: "trc20",
      name: "USD Coin",
      ticker: "USDC",
      units: [{ name: "USD Coin", code: "USDC", magnitude: 6 }],
    },
  ],
  solana: [
    {
      type: "TokenCurrency",
      id: "solana/spl/epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v",
      contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      parentCurrency: getCryptoCurrencyById("solana"),
      tokenType: "spl",
      name: "USD Coin",
      ticker: "USDC",
      units: [{ name: "USD Coin", code: "USDC", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "solana/spl/es9vmfrzacermjfrf4h2fyd4kconky11mcce8benwnyb",
      contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
      parentCurrency: getCryptoCurrencyById("solana"),
      tokenType: "spl",
      name: "Tether USD",
      ticker: "USDT",
      units: [{ name: "Tether USD", code: "USDT", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "solana/spl/usds_usdswr9apdhk5bvjkmjzff41ffux8bsxdkcr81vtwca",
      contractAddress: "USDSwr9ApdHk57bVjKZWn2pGF4rHiTu4DezmF3f6S2H",
      parentCurrency: getCryptoCurrencyById("solana"),
      tokenType: "spl",
      name: "USDS",
      ticker: "USDS",
      units: [{ name: "USDS", code: "USDS", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "solana/spl/usde_dekqhypn7gmrj5cartqfawefqbzb33hyf6s5icwjeont",
      contractAddress: "DEkqHyPN7GMRJ5cArtqFAWefqbZb33Hyf6s5icwJEONT",
      parentCurrency: getCryptoCurrencyById("solana"),
      tokenType: "spl",
      name: "USDe",
      ticker: "USDe",
      units: [{ name: "USDe", code: "USDe", magnitude: 9 }],
    },
    {
      type: "TokenCurrency",
      id: "solana/spl/paypal_usd_2b1kv6dkpanxd5ixfnxcpjxmkwqjjaymczfhsfu24gxo",
      contractAddress: "2b1kV6DkPAnxd5ixfnxCpjxmkwqjjaYmCZfHsFU24GXo",
      parentCurrency: getCryptoCurrencyById("solana"),
      tokenType: "spl",
      name: "PayPal USD",
      ticker: "PYUSD",
      units: [{ name: "PayPal USD", code: "PYUSD", magnitude: 6 }],
    },
  ],
  algorand: [
    {
      type: "TokenCurrency",
      id: "algorand/asa/312769",
      contractAddress: "312769",
      parentCurrency: getCryptoCurrencyById("algorand"),
      tokenType: "asa",
      name: "Tether USD",
      ticker: "USDT",
      units: [{ name: "Tether USD", code: "USDT", magnitude: 6 }],
    },
    {
      type: "TokenCurrency",
      id: "algorand/asa/31566704",
      contractAddress: "31566704",
      parentCurrency: getCryptoCurrencyById("algorand"),
      tokenType: "asa",
      name: "USD Coin",
      ticker: "USDC",
      units: [{ name: "USD Coin", code: "USDC", magnitude: 6 }],
    },
  ],
};

export const CURRENCIES_WITH_STABLECOINS = Object.keys(STABLECOIN_TOKENS_BY_CURRENCY);

export const getStablecoinTokensForCurrency = (currencyId: string): TokenCurrency[] =>
  STABLECOIN_TOKENS_BY_CURRENCY[currencyId] ?? [];
