import BigNumber from "bignumber.js";
import { z } from "zod";

import {
  CryptoCurrencySchema,
  CryptoOrTokenCurrencySchema,
  TokenCurrencySchema,
} from "../../external/currency/schema";

export const BigNumberSchema = z.custom<BigNumber>(value => BigNumber.isBigNumber(value), {
  message: "Expected BigNumber",
});

export const GranularityIdSchema = z.enum(["HOUR", "DAY", "WEEK"]);

export const BalanceHistoryDataCacheSchema = z.object({
  latestDate: z.number().nullable().optional(),
  balances: z.array(z.number()),
});

export const BalanceHistoryCacheSchema = z.record(
  GranularityIdSchema,
  BalanceHistoryDataCacheSchema,
);

export const DerivationModeSchema = z.enum([
  "",
  "ethM",
  "ethMM",
  "etcM",
  "aeternity",
  "tezbox",
  "tezosbip44h",
  "galleonL",
  "tezboxL",
  "taproot",
  "native_segwit",
  "segwit",
  "segwit_unsplit",
  "sep5",
  "unsplit",
  "polkadotbip44",
  "glifLegacy",
  "glif",
  "filecoinBIP44",
  "casper_wallet",
  "solanaMain",
  "solanaSub",
  "solanaBip44Change",
  "hederaBip44",
  "cardano",
  "nearbip44h",
  "vechain",
  "internet_computer",
  "stacks_wallet",
  "icon",
  "ton",
  "sui",
  "aptos",
  "minabip44",
  "canton",
  "cashaddr",
  "celo",
  "celoMM",
  "celoEvm",
]);

export const OperationTypeSchema = z.enum([
  "IN",
  "OUT",
  "NONE",
  "CREATE",
  "REVEAL",
  "UNKNOWN",
  "DELEGATE",
  "UNDELEGATE",
  "REDELEGATE",
  "REWARD",
  "FEES",
  "FREEZE",
  "UNFREEZE",
  "WITHDRAW_EXPIRE_UNFREEZE",
  "UNDELEGATE_RESOURCE",
  "LEGACY_UNFREEZE",
  "VOTE",
  "REWARD_PAYOUT",
  "BOND",
  "UNBOND",
  "WITHDRAW_UNBONDED",
  "SET_CONTROLLER",
  "SLASH",
  "NOMINATE",
  "CHILL",
  "APPROVE",
  "OPT_IN",
  "OPT_OUT",
  "LOCK",
  "UNLOCK",
  "WITHDRAW",
  "REVOKE",
  "ACTIVATE",
  "REGISTER",
  "STAKE",
  "UNSTAKE",
  "WITHDRAW_UNSTAKED",
  "BURN",
  "ASSOCIATE_TOKEN",
  "CONTRACT_CALL",
  "UPDATE_ACCOUNT",
  "PRE_APPROVAL",
  "TRANSFER_PROPOSAL",
  "TRANSFER_REJECTED",
  "TRANSFER_WITHDRAWN",
]);

export const OperationSchema: z.ZodType<unknown> = z.lazy(() =>
  z.object({
    id: z.string(),
    hash: z.string(),
    type: OperationTypeSchema,
    value: BigNumberSchema,
    fee: BigNumberSchema,
    senders: z.array(z.string()),
    recipients: z.array(z.string()),
    blockHeight: z.number().nullable().optional(),
    blockHash: z.string().nullable().optional(),
    transactionSequenceNumber: BigNumberSchema.optional(),
    accountId: z.string(),
    standard: z.string().optional(),
    operator: z.string().optional(),
    contract: z.string().optional(),
    tokenId: z.string().optional(),
    date: z.date(),
    hasFailed: z.boolean().optional(),
    subOperations: z.array(OperationSchema).optional(),
    internalOperations: z.array(OperationSchema).optional(),
    transactionRaw: z.unknown().optional(),
    extra: z.unknown(),
  }),
);

export const SwapOperationSchema = z.object({
  provider: z.string(),
  swapId: z.string(),
  status: z.string(),
  receiverAccountId: z.string(),
  tokenId: z.string().optional(),
  fromCurrency: CryptoOrTokenCurrencySchema.optional(),
  toCurrency: CryptoOrTokenCurrencySchema.optional(),
  operationId: z.string(),
  fromAmount: BigNumberSchema,
  toAmount: BigNumberSchema,
});

export const TokenAccountSchema = z.object({
  type: z.literal("TokenAccount"),
  id: z.string(),
  parentId: z.string(),
  token: TokenCurrencySchema,
  balance: BigNumberSchema,
  spendableBalance: BigNumberSchema,
  creationDate: z.date(),
  operationsCount: z.number(),
  operations: z.array(OperationSchema),
  pendingOperations: z.array(OperationSchema),
  balanceHistoryCache: BalanceHistoryCacheSchema,
  swapHistory: z.array(SwapOperationSchema),
});

export const AccountSchema = z.object({
  type: z.literal("Account"),
  id: z.string(),
  seedIdentifier: z.string(),
  xpub: z.string().optional(),
  derivationMode: DerivationModeSchema,
  index: z.number(),
  freshAddress: z.string(),
  freshAddressPath: z.string(),
  used: z.boolean(),
  balance: BigNumberSchema,
  spendableBalance: BigNumberSchema,
  creationDate: z.date(),
  blockHeight: z.number(),
  currency: CryptoCurrencySchema,
  feesCurrency: z.union([CryptoCurrencySchema, TokenCurrencySchema]).optional(),
  operationsCount: z.number(),
  operations: z.array(OperationSchema),
  pendingOperations: z.array(OperationSchema),
  lastSyncDate: z.date(),
  subAccounts: z.array(TokenAccountSchema).optional(),
  balanceHistoryCache: BalanceHistoryCacheSchema,
  swapHistory: z.array(SwapOperationSchema),
  syncHash: z.string().optional(),
});
