export enum ScreenName {
  Analytics = "Analytics",
  AboutSettings = "AboutSettings",
  Account = "Account",
  Accounts = "Accounts",
  AccountSettingsMain = "AccountSettingsMain",
  AccountsSettings = "AccountsSettings",
  AddAccountsAccounts = "AddAccountsAccounts",
  AddAccountsSelectDevice = "AddAccountsSelectDevice",
  AddAccountsSuccess = "AddAccountsSuccess",
  AddAccountsTokenCurrencyDisclaimer = "AddAccountsTokenCurrencyDisclaimer",
  AdvancedLogs = "AdvancedLogs",
  Asset = "Asset",
  Assets = "Assets",
  AccountsList = "AccountsList",
  AssetsList = "AssetsList",
  BenchmarkQRStream = "BenchmarkQRStream",
  BitcoinEditCustomFees = "BitcoinEditCustomFees",
  CantonEditMemo = "CantonEditMemo",
  ClaimRewardsConnectDevice = "ClaimRewardsConnectDevice",
  ClaimRewardsSelectDevice = "ClaimRewardsSelectDevice",
  ClaimRewardsValidationError = "ClaimRewardsValidationError",
  ClaimRewardsValidationSuccess = "ClaimRewardsValidationSuccess",
  ConfirmPassword = "ConfirmPassword",
  CountervalueSettings = "CountervalueSettings",
  CryptoAssetsSettings = "CryptoAssetsSettings",
  CurrencySettings = "CurrencySettings",
  EditCurrencyUnits = "EditCurrencyUnits",
  CustomCALRefInput = "CustomCALRefInput",
  DebugBLEDevicePairing = "DebugBLEDevicePairing",
  DebugConfiguration = "DebugConfiguration",
  DebugCommandSender = "DebugCommandSender",
  DebugConnectivity = "DebugConnectivity",
  DebugCrash = "DebugCrash",
  DebugCustomImageGraphics = "DebugCustomImageGraphics",
  DebugDebugging = "DebugDebugging",
  DebugQueuedDrawers = "DebugQueuedDrawers",
  DebugQueuedDrawerScreen0 = "DebugQueuedDrawerScreen0",
  DebugQueuedDrawerScreen1 = "DebugQueuedDrawerScreen1",
  DebugQueuedDrawerScreen2 = "DebugQueuedDrawerScreen2",
  DebugEnv = "DebugEnv",
  DebugFeatureFlags = "DebugFeatureFlags",
  DebugInstallSetOfApps = "DebugInstallSetOfApps",
  DebugFeatures = "DebugFeatures",
  DebugFetchCustomImage = "DebugFetchCustomImage",
  DebugFirmwareUpdate = "DebugFirmwareUpdate",
  DebugGenerators = "DebugGenerators",
  DebugHttpTransport = "DebugHttpTransport",
  DebugInformation = "DebugInformation",
  DebugPerformance = "DebugPerformance",
  DebugLogs = "DebugLogs",
  DebugLottie = "DebugLottie",
  DebugLumen = "DebugLumen",
  DebugWallet40 = "DebugWallet40",
  DebugWalletV4Tour = "DebugWalletV4Tour",
  DebugTermsOfUse = "DebugTermsOfUse",
  DebugVideos = "DebugVideos",
  DebugMockGenerateAccounts = "DebugMockGenerateAccounts",
  DebugModularAssetDrawer = "DebugModularAssetDrawer",
  DebugNetwork = "DebugNetwork",
  DebugPlayground = "DebugPlayground",
  DebugBluetoothAndLocationServices = "DebugBluetoothAndLocationServices",
  DebugStorageMigration = "DebugStorageMigration",
  DebugSettings = "DebugSettings",
  DebugSnackbars = "DebugSnackbars",
  DebugTransactionsAlerts = "DebugTransactionsAlerts",
  DebugSwipe = "DebugSwipe",
  DebugStore = "DebugStore",
  DebugSwap = "DebugSwap",
  DebugCameraPermissions = "DebugCameraPermissions",
  DebugTooltip = "DebugTooltip",
  DelegationConnectDevice = "DelegationConnectDevice",
  DelegationSelectDevice = "DelegationSelectDevice",
  DelegationSelectValidator = "DelegationSelectValidator",
  DelegationStarted = "DelegationStarted",
  DelegationSummary = "DelegationSummary",
  DelegationValidationError = "DelegationValidationError",
  DelegationValidationSuccess = "DelegationValidationSuccess",
  DeveloperCustomManifest = "DeveloperCustomManifest",
  DeveloperSettings = "DeveloperSettings",
  DeviceConnect = "DeviceConnect",
  EditAccountName = "EditAccountName",
  EditDeviceName = "EditDeviceName",
  Card = "Card",
  ExchangeBuy = "ExchangeBuy",
  ExchangeDeveloperMode = "ExchangeDeveloperMode",
  ExchangeSelectAccount = "ExchangeSelectAccount",
  ExchangeSelectCurrency = "ExchangeSelectCurrency",
  ExchangeSell = "ExchangeSell",
  ExperimentalSettings = "ExperimentalSettings",
  FirmwareUpdate = "FirmwareUpdate",
  FreezeAmount = "FreezeAmount",
  FreezeConnectDevice = "FreezeConnectDevice",
  FreezeInfo = "FreezeInfo",
  FreezeSelectDevice = "FreezeSelectDevice",
  FreezeValidationError = "FreezeValidationError",
  FreezeValidationSuccess = "FreezeValidationSuccess",
  GeneralSettings = "GeneralSettings",
  GetDevice = "GetDevice",
  HelpSettings = "HelpSettings",
  MyLedgerChooseDevice = "MyLedgerChooseDevice",
  MyLedgerDevice = "MyLedgerDevice",
  NotificationsSettings = "NotificationsSettings",
  OperationDetails = "OperationDetails",
  PasswordAdd = "PasswordAdd",
  PasswordRemove = "PasswordRemove",
  Portfolio = "Wallet",
  PortfolioOperationHistory = "PortfolioOperationHistory",
  ProviderList = "ProviderList",
  PurchaseDevice = "PurchaseDevice",
  ReceiveConfirmation = "ReceiveConfirmation",
  ReceiveConnectDevice = "ReceiveConnectDevice",
  ReceiveVerifyAddress = "ReceiveVerifyAddress",
  ReceiveProvider = "ReceiveProvider",
  Recover = "Recover",
  RegionSettings = "RegionSettings",
  Resources = "Resources",
  XrpEditTag = "XrpEditTag",
  ScanRecipient = "ScanRecipient",
  SendAmountCoin = "SendAmountCoin",
  SendCoin = "SendCoin",
  SendConnectDevice = "SendConnectDevice",
  SendSelectDevice = "SendSelectDevice",
  SendSelectRecipient = "SendSelectRecipient",
  SendSummary = "SendSummary",
  SendBroadcastError = "SendBroadcastError",
  SendValidationError = "SendValidationError",
  NewSendRecipient = "NewSendRecipient",
  SendFlowRecipient = "SendFlowRecipient",
  SendFlowAmount = "SendFlowAmount",
  SendFlowConfirmation = "SendFlowConfirmation",
  SendFlowSignature = "SendFlowSignature",
  TransactionAlreadyValidatedError = "TransactionAlreadyValidatedError",
  SendValidationSuccess = "SendValidationSuccess",
  SettingsScreen = "SettingsScreen",
  SignConnectDevice = "SignConnectDevice",
  SignSelectDevice = "SignSelectDevice",
  SignSummary = "SignSummary",
  SignValidationError = "SignValidationError",
  Swap = "Swap",
  SwapSelectAccount = "SelectAccount",
  SwapSelectCurrency = "SelectCurrency",
  SwapCustomError = "SwapCustomError",
  SwapForm = "SwapForm",
  SwapLiveApp = "SwapLiveApp",
  SwapHistory = "SwapHistory",
  SwapLoading = "SwapLoading",
  SwapOperationDetails = "SwapOperationDetails",
  SwapPendingOperation = "PendingOperation",
  SwapSelectFees = "SelectFees",
  SwapSelectProvider = "SelectProvider",
  SwapTab = "SwapTab",
  PerpsTab = "PerpsTab",
  Earn = "Earn",
  Transfer = "Transfer",
  UnfreezeAmount = "UnfreezeAmount",
  UnfreezeConnectDevice = "UnfreezeConnectDevice",
  UnfreezeSelectDevice = "UnfreezeSelectDevice",
  UnfreezeValidationError = "UnfreezeValidationError",
  UnfreezeValidationSuccess = "UnfreezeValidationSuccess",
  VoteCast = "VoteCast",
  VoteConnectDevice = "VoteConnectDevice",
  VoteSelectDevice = "VoteSelectDevice",
  VoteSelectValidator = "VoteSelectValidator",
  VoteStarted = "VoteStarted",
  VoteValidationError = "VoteValidationError",
  VoteValidationSuccess = "VoteValidationSuccess",
  FeeHomePage = "FeeHomePage",
  FeeCustomFeePage = "FeeCustomFeePage",

  // celo
  CeloRegistrationValidationSuccess = "CeloRegistrationValidationSuccess",
  CeloRegistrationValidationError = "CeloRegistrationValidationError",
  CeloRegistrationStarted = "CeloRegistrationStarted",
  CeloRegistrationSelectDevice = "CeloRegistrationSelectDevice",
  CeloRegistrationConnectDevice = "CeloRegistrationConnectDevice",
  CeloLockValidationSuccess = "CeloLockValidationSuccess",
  CeloLockValidationError = "CeloLockValidationError",
  CeloLockAmount = "CeloLockAmount",
  CeloLockSelectDevice = "CeloLockSelectDevice",
  CeloLockConnectDevice = "CeloLockConnectDevice",
  CeloUnlockValidationSuccess = "CeloUnlockValidationSuccess",
  CeloUnlockValidationError = "CeloUnlockValidationError",
  CeloUnlockAmount = "CeloUnlockAmount",
  CeloUnlockSelectDevice = "CeloUnlockSelectDevice",
  CeloUnlockConnectDevice = "CeloUnlockConnectDevice",
  CeloVoteValidationSuccess = "CeloVoteValidationSuccess",
  CeloVoteValidationError = "CeloVoteValidationError",
  CeloVoteStarted = "CeloVoteStarted",
  CeloVoteSummary = "CeloVoteSummary",
  CeloVoteAmount = "CeloVoteAmount",
  CeloVoteValidatorSelect = "CeloVoteValidatorSelect",
  CeloVoteSelectDevice = "CeloVoteSelectDevice",
  CeloVoteConnectDevice = "CeloVoteConnectDevice",
  CeloActivateValidationSuccess = "CeloActivateValidationSuccess",
  CeloActivateValidationError = "CeloActivateValidationError",
  CeloActivateSummary = "CeloActivateSummary",
  CeloActivateValidatorSelect = "CeloActivateValidatorSelect",
  CeloActivateSelectDevice = "CeloActivateSelectDevice",
  CeloActivateConnectDevice = "CeloActivateConnectDevice",
  CeloRevokeValidationSuccess = "CeloRevokeValidationSuccess",
  CeloRevokeValidationError = "CeloRevokeValidationError",
  CeloRevokeSummary = "CeloRevokeSummary",
  CeloRevokeAmount = "CeloRevokeAmount",
  CeloRevokeValidatorSelect = "CeloRevokeValidatorSelect",
  CeloRevokeSelectDevice = "CeloRevokeSelectDevice",
  CeloRevokeConnectDevice = "CeloRevokeConnectDevice",
  CeloWithdrawValidationSuccess = "CeloWithdrawValidationSuccess",
  CeloWithdrawValidationError = "CeloWithdrawValidationError",
  CeloWithdrawSelectDevice = "CeloWithdrawSelectDevice",
  CeloWithdrawConnectDevice = "CeloWithdrawConnectDevice",
  CeloWithdrawAmount = "CeloWithdrawAmount",

  // cosmos
  CosmosFamilyEditMemo = "CosmosFamilyEditMemo",
  CosmosDelegationStarted = "CosmosDelegationStarted",
  CosmosDelegationValidator = "CosmosDelegationValidator",
  CosmosDelegationValidatorSelect = "CosmosDelegationValidatorSelect",
  CosmosDelegationAmount = "CosmosDelegationAmount",
  CosmosDelegationSelectDevice = "CosmosDelegationSelectDevice",
  CosmosDelegationConnectDevice = "CosmosDelegationConnectDevice",
  CosmosDelegationValidationError = "CosmosDelegationValidationError",
  CosmosDelegationValidationSuccess = "CosmosDelegationValidationSuccess",
  CosmosDefaultRedelegationAmount = "CosmosDefaultRedelegationAmount",
  CosmosRedelegationValidator = "CosmosRedelegationValidator",
  CosmosRedelegationAmount = "CosmosRedelegationAmount",
  CosmosRedelegationBridgeTransaction = "CosmosRedelegationBridgeTransaction",
  CosmosRedelegationSelectDevice = "CosmosRedelegationSelectDevice",
  CosmosRedelegationConnectDevice = "CosmosRedelegationConnectDevice",
  CosmosRedelegationValidationError = "CosmosRedelegationValidationError",
  CosmosRedelegationValidationSuccess = "CosmosRedelegationValidationSuccess",
  CosmosUndelegationAmount = "CosmosUndelegationAmount",
  CosmosUndelegationBridgeTransaction = "CosmosUndelegationBridgeTransaction",
  CosmosUndelegationSelectDevice = "CosmosUndelegationSelectDevice",
  CosmosUndelegationConnectDevice = "CosmosUndelegationConnectDevice",
  CosmosUndelegationValidationError = "CosmosUndelegationValidationError",
  CosmosUndelegationValidationSuccess = "CosmosUndelegationValidationSuccess",
  CosmosClaimRewardsValidator = "CosmosClaimRewardsValidator",
  CosmosClaimRewardsMethod = "CosmosClaimRewardsMethod",
  CosmosClaimRewardsSelectDevice = "CosmosClaimRewardsSelectDevice",
  CosmosClaimRewardsConnectDevice = "CosmosClaimRewardsConnectDevice",
  CosmosClaimRewardsValidationError = "CosmosClaimRewardsValidationError",
  CosmosClaimRewardsValidationSuccess = "CosmosClaimRewardsValidationSuccess",

  // multiversx
  MultiversXDelegationStarted = "MultiversXDelegationStarted",
  MultiversXDelegationValidator = "MultiversXDelegationValidator",
  MultiversXDelegationValidatorList = "MultiversXDelegationValidatorList",
  MultiversXDelegationAmount = "MultiversXDelegationAmount",
  MultiversXDelegationSelectDevice = "MultiversXDelegationSelectDevice",
  MultiversXDelegationConnectDevice = "MultiversXDelegationConnectDevice",
  MultiversXDelegationValidationError = "MultiversXDelegationValidationError",
  MultiversXDelegationValidationSuccess = "MultiversXDelegationValidationSuccess",
  MultiversXUndelegationAmount = "MultiversXUndelegationAmount",
  MultiversXUndelegationSelectDevice = "MultiversXUndelegationSelectDevice",
  MultiversXUndelegationConnectDevice = "MultiversXUndelegationConnectDevice",
  MultiversXUndelegationValidationError = "MultiversXUndelegationValidationError",
  MultiversXUndelegationValidationSuccess = "MultiversXUndelegationValidationSuccess",
  MultiversXClaimRewardsValidator = "MultiversXClaimRewardsValidator",
  MultiversXClaimRewardsMethod = "MultiversXClaimRewardsMethod",
  MultiversXClaimRewardsSelectDevice = "MultiversXClaimRewardsSelectDevice",
  MultiversXClaimRewardsConnectDevice = "MultiversXClaimRewardsConnectDevice",
  MultiversXClaimRewardsValidationError = "MultiversXClaimRewardsValidationError",
  MultiversXClaimRewardsValidationSuccess = "MultiversXClaimRewardsValidationSuccess",
  MultiversXWithdrawFunds = "MultiversXWithdrawFunds",
  MultiversXWithdrawSelectDevice = "MultiversXWithdrawSelectDevice",
  MultiversXWithdrawConnectDevice = "MultiversXWithdrawConnectDevice",
  MultiversXWithdrawValidationError = "MultiversXWithdrawValidationError",
  MultiversXWithdrawValidationSuccess = "MultiversXWithdrawValidationSuccess",

  // internet_computer
  InternetComputerEditMemo = "InternetComputerEditMemo",

  // ton
  TonEditComment = "TonEditComment",
  // mina
  MinaEditMemo = "MinaEditMemo",

  // Algorand
  AlgorandEditMemo = "AlgorandEditMemo",
  AlgorandClaimRewardsInfo = "AlgorandClaimRewardsInfo",
  AlgorandClaimRewardsStarted = "AlgorandClaimRewardsStarted",
  AlgorandClaimRewardsSelectDevice = "AlgorandClaimRewardsSelectDevice",
  AlgorandClaimRewardsConnectDevice = "AlgorandClaimRewardsConnectDevice",
  AlgorandClaimRewardsSummary = "AlgorandClaimRewardsValidation",
  AlgorandClaimRewardsValidationError = "AlgorandClaimRewardsValidationError",
  AlgorandClaimRewardsValidationSuccess = "AlgorandClaimRewardsValidationSuccess",
  AlgorandOptInSelectToken = "AlgorandOptInSelectToken",
  AlgorandOptInSelectDevice = "AlgorandOptInSelectDevice",
  AlgorandOptInConnectDevice = "AlgorandOptInConnectDevice",
  AlgorandOptInSummary = "AlgorandOptInValidation",
  AlgorandOptInValidationError = "AlgorandOptInValidationError",
  AlgorandOptInValidationSuccess = "AlgorandOptInValidationSuccess",

  // Evm
  EvmEditGasLimit = "EvmEditGasLimit",
  EvmCustomFees = "EvmCustomFees",
  EditTransactionSummary = "EditTransactionSummary",
  EvmEditTransactionMethodSelection = "EvmEditTransactionMethodSelection",

  // Polkadot
  PolkadotBondStarted = "PolkadotBondStarted",
  PolkadotBondAmount = "PolkadotBondAmount",
  PolkadotBondSelectDevice = "PolkadotBondSelectDevice",
  PolkadotBondConnectDevice = "PolkadotBondConnectDevice",
  PolkadotBondValidationError = "PolkadotBondValidationError",
  PolkadotBondValidationSuccess = "PolkadotBondValidationSuccess",
  PolkadotUnbondAmount = "PolkadotUnbondAmount",
  PolkadotUnbondSelectDevice = "PolkadotUnbondSelectDevice",
  PolkadotUnbondConnectDevice = "PolkadotUnbondConnectDevice",
  PolkadotUnbondValidationError = "PolkadotUnbondValidationError",
  PolkadotUnbondValidationSuccess = "PolkadotUnbondValidationSuccess",
  PolkadotRebondAmount = "PolkadotRebondAmount",
  PolkadotRebondSelectDevice = "PolkadotRebondSelectDevice",
  PolkadotRebondConnectDevice = "PolkadotRebondConnectDevice",
  PolkadotRebondValidationError = "PolkadotRebondValidationError",
  PolkadotRebondValidationSuccess = "PolkadotRebondValidationSuccess",
  PolkadotNominateSelectValidators = "PolkadotNominateSelectValidators",
  PolkadotNominateSelectDevice = "PolkadotNominateSelectDevice",
  PolkadotNominateConnectDevice = "PolkadotNominateConnectDevice",
  PolkadotNominateValidationError = "PolkadotNominateValidationError",
  PolkadotNominateValidationSuccess = "PolkadotNominateValidationSuccess",
  PolkadotSimpleOperationStarted = "PolkadotSimpleOperationStarted",
  PolkadotSimpleOperationSelectDevice = "PolkadotSimpleOperationSelectDevice",
  PolkadotSimpleOperationConnectDevice = "PolkadotSimpleOperationConnectDevice",
  PolkadotSimpleOperationValidationError = "PolkadotSimpleOperationValidationError",
  PolkadotSimpleOperationValidationSuccess = "PolkadotSimpleOperationValidationSuccess",

  // Stellar
  StellarEditMemoType = "StellarEditMemoType",
  StellarEditMemoValue = "StellarEditMemoValue",
  StellarEditCustomFees = "StellarEditCustomFees",
  StellarAddAssetSelectAsset = "StellarAddAssetSelectAsset",
  StellarAddAssetSelectDevice = "StellarAddAssetSelectDevice",
  StellarAddAssetConnectDevice = "StellarAddAssetConnectDevice",
  StellarAddAssetValidation = "StellarAddAssetValidation",
  StellarAddAssetValidationError = "StellarAddAssetValidationError",
  StellarAddAssetValidationSuccess = "StellarAddAssetValidationSuccess",
  // Canton
  CantonOnboardAccount = "CantonOnboardAccount",

  OnboardingWelcome = "OnboardingWelcome",
  OnboardingPostWelcomeSelection = "OnboardingPostWelcomeSelection",
  OnboardingWelcomeBack = "OnboardingWelcomeBack",
  OnboardingLanguage = "OnboardingLanguage",
  OnboardingTermsOfUse = "OnboardingTermsOfUse",
  OnboardingDeviceSelection = "OnboardingDeviceSelection",
  OnboardingUseCase = "OnboardingUseCase",
  OnboardingModalDiscoverLive = "OnboardingModalDiscoverLive",
  OnboardingSetNewDevice = "OnboardingSetNewDevice",
  OnboardingSetupDeviceInformation = "OnboardingSetupDeviceInformation",
  OnboardingGeneralInformation = "OnboardingGeneralInformation",
  OnboardingBluetoothInformation = "OnboardingBluetoothInformation",
  OnboardingProtectionConnectionInformation = "OnboardingProtectionConnectionInformation",
  OnboardingInfoModal = "OnboardingInfoModal",
  OnboardingRecoveryPhrase = "OnboardingRecoveryPhrase",
  OnboardingPairNew = "OnboardingPairNew",
  OnboardingSecureYourCrypto = "OnboardingSecureYourCrypto",
  OnboardingFundSuccess = "OnboardingFundSuccess",
  OnboardingImportAccounts = "OnboardingImportAccounts",
  OnboardingQuiz = "OnboardingQuiz",
  OnboardingQuizFinal = "OnboardingQuizFinal",
  OnboardingBleDevicePairingFlow = "OnboardingBleDevicePairingFlow",
  OnboardingModalSetupNewDevice = "OnboardingModalSetupNewDevice",
  OnboardingModalSetupSecureRecovery = "OnboardingModalSetupSecureRecovery",
  OnboardingPreQuizModal = "OnboardingPreQuizModal",
  OnboardingProtectFlow = "OnboardingProtectFlow",
  SyncOnboardingCompanion = "SyncOnboardingCompanion",
  SyncOnboardingCompletion = "SyncOnboardingCompletion",
  BleDevicePairingFlow = "BleDevicePairingFlow",
  PlatformCatalog = "PlatformCatalog",
  PlatformApp = "PlatformApp",
  PlatformStartExchange = "PlatformStartExchange",
  PlatformCompleteExchange = "PlatformCompleteExchange",
  WalletConnectConnect = "WalletConnectConnect",
  NotificationCenter = "NotificationCenter",
  NotificationCenterStatus = "NotificationCenterStatus",
  SignTransactionSummary = "SignTransactionSummary",
  SignTransactionSelectDevice = "SignTransactionSelectDevice",
  SignTransactionConnectDevice = "SignTransactionConnectDevice",
  SignTransactionValidationError = "SignTransactionValidationError",
  SignRawTransactionSelectDevice = "SignRawTransactionSelectDevice",
  SignRawTransactionConnectDevice = "SignRawTransactionConnectDevice",
  SignRawTransactionValidationError = "SignRawTransactionValidationError",
  RequestAccountsSelectCrypto = "RequestAccountsSelectCrypto",
  RequestAccountsSelectAccount = "RequestAccountsSelectAccount",
  MarketList = "MarketList",
  MarketCurrencySelect = "MarketCurrencySelect",
  MarketDetail = "MarketDetail",
  VerifyAccount = "VerifyAccount",
  AnalyticsAllocation = "AnalyticsAllocation",
  AnalyticsOperations = "AnalyticsOperations",
  DetailedAllocation = "DetailedAllocation",
  CustomErrorScreen = "CustomErrorScreen",
  // solana
  SolanaEditMemo = "SolanaEditMemo",
  SolanaEditAmount = "SolanaEditAmount",
  SolanaDelegationStarted = "SolanaDelegationStarted",
  PostBuyDeviceScreen = "PostBuyDeviceScreen",
  PostBuyDeviceSetupNanoWallScreen = "PostBuyDeviceSetupNanoWallScreen",
  NoDeviceWallScreen = "NoDeviceWallScreen",
  DiscoverScreen = "DiscoverScreen",
  LearnWebView = "LearnWebView",
  // cardano
  CardanoEditMemo = "CardanoEditMemo",
  CardanoDelegationStarted = "CardanoDelegationStarted",
  CardanoDelegationSummary = "CardanoDelegationSummary",
  CardanoDelegationPoolSelect = "CardanoDelegationPoolSelect",
  CardanoDelegationSelectDevice = "CardanoDelegationSelectDevice",
  CardanoDelegationConnectDevice = "CardanoDelegationConnectDevice",
  CardanoDelegationValidationError = "CardanoDelegationValidationError",
  CardanoDelegationValidationSuccess = "CardanoDelegationValidationSuccess",
  CardanoUndelegationSummary = "CardanoUndelegationSummary",
  CardanoUndelegationSelectDevice = "CardanoUndelegationSelectDevice",
  CardanoUndelegationConnectDevice = "CardanoUndelegationConnectDevice",
  CardanoUndelegationValidationError = "CardanoUndelegationValidationError",
  CardanoUndelegationValidationSuccess = "CardanoUndelegationValidationSuccess",

  // stacks
  StacksEditMemo = "StacksEditMemo",
  // casper
  CasperEditTransferId = "CasperEditTransferId",
  // hedera
  HederaEditMemo = "HederaEditMemo",
  HederaAssociateTokenSelectToken = "HederaAssociateTokenSelectToken",
  HederaAssociateTokenSummary = "HederaAssociateTokenSummary",
  HederaAssociateTokenSelectDevice = "HederaAssociateTokenSelectDevice",
  HederaAssociateTokenConnectDevice = "HederaAssociateTokenConnectDevice",
  HederaAssociateTokenValidationError = "HederaAssociateTokenValidationError",
  HederaAssociateTokenValidationSuccess = "HederaAssociateTokenValidationSuccess",
  HederaDelegationSummary = "HederaDelegationSummary",
  HederaDelegationSelectValidator = "HederaDelegationSelectValidator",
  HederaDelegationSelectDevice = "HederaDelegationSelectDevice",
  HederaDelegationConnectDevice = "HederaDelegationConnectDevice",
  HederaDelegationValidationError = "HederaDelegationValidationError",
  HederaDelegationValidationSuccess = "HederaDelegationValidationSuccess",
  HederaUndelegationAmount = "HederaUndelegationAmount",
  HederaUndelegationSelectDevice = "HederaUndelegationSelectDevice",
  HederaUndelegationConnectDevice = "HederaUndelegationConnectDevice",
  HederaUndelegationValidationError = "HederaUndelegationValidationError",
  HederaUndelegationValidationSuccess = "HederaUndelegationValidationSuccess",
  HederaRedelegationSelectValidator = "HederaRedelegationSelectValidator",
  HederaRedelegationAmount = "HederaRedelegationAmount",
  HederaRedelegationSelectDevice = "HederaRedelegationSelectDevice",
  HederaRedelegationConnectDevice = "HederaRedelegationConnectDevice",
  HederaRedelegationValidationError = "HederaRedelegationValidationError",
  HederaRedelegationValidationSuccess = "HederaRedelegationValidationSuccess",
  HederaClaimRewardsSelectReward = "HederaClaimRewardsSelectReward",
  HederaClaimRewardsClaim = "HederaClaimRewardsClaim",
  HederaClaimRewardsSelectDevice = "HederaClaimRewardsSelectDevice",
  HederaClaimRewardsConnectDevice = "HederaClaimRewardsConnectDevice",
  HederaClaimRewardsValidationError = "HederaClaimRewardsValidationError",
  HederaClaimRewardsValidationSuccess = "HederaClaimRewardsValidationSuccess",
  // near
  NearStakingValidator = "NearStakingValidator",
  NearStakingValidatorSelect = "NearStakingValidatorSelect",
  NearStakingAmount = "NearStakingAmount",
  NearStakingStarted = "NearStakingStarted",
  NearUnstakingAmount = "NearUnstakingAmount",
  NearWithdrawingAmount = "NearWithdrawingAmount",
  NearStakingSelectDevice = "NearStakingSelectDevice",
  NearStakingConnectDevice = "NearStakingConnectDevice",
  NearStakingValidationError = "NearStakingValidationError",
  NearStakingValidationSuccess = "NearStakingValidationSuccess",
  NearUnstakingSelectDevice = "NearUnstakingSelectDevice",
  NearUnstakingConnectDevice = "NearUnstakingConnectDevice",
  NearUnstakingValidationError = "NearUnstakingValidationError",
  NearUnstakingValidationSuccess = "NearUnstakingValidationSuccess",
  NearWithdrawingSelectDevice = "NearWithdrawingSelectDevice",
  NearWithdrawingConnectDevice = "NearWithdrawingConnectDevice",
  NearWithdrawingValidationError = "NearWithdrawingValidationError",
  NearWithdrawingValidationSuccess = "NearWithdrawingValidationSuccess",
  // Aptos
  AptosStakingValidator = "AptosStakingValidator",
  AptosStakingValidatorSelect = "AptosStakingValidatorSelect",
  AptosStakingAmount = "AptosStakingAmount",
  AptosStakingStarted = "AptosStakingStarted",
  AptosStakingSelectDevice = "AptosStakingSelectDevice",
  AptosStakingConnectDevice = "AptosStakingConnectDevice",
  AptosStakingValidationError = "AptosStakingValidationError",
  AptosStakingValidationSuccess = "AptosStakingValidationSuccess",
  AptosRestakingAmount = "AptosRestakingAmount",
  AptosRestakingSelectDevice = "AptosRestakingSelectDevice",
  AptosRestakingConnectDevice = "AptosRestakingConnectDevice",
  AptosRestakingValidationError = "AptosRestakingValidationError",
  AptosRestakingValidationSuccess = "AptosRestakingValidationSuccess",
  AptosUnstakingAmount = "AptosUnstakingAmount",
  AptosUnstakingSelectDevice = "AptosUnstakingSelectDevice",
  AptosUnstakingConnectDevice = "AptosUnstakingConnectDevice",
  AptosUnstakingValidationError = "AptosUnstakingValidationError",
  AptosUnstakingValidationSuccess = "AptosUnstakingValidationSuccess",
  AptosWithdrawingAmount = "AptosWithdrawingAmount",
  AptosWithdrawingSelectDevice = "AptosWithdrawingSelectDevice",
  AptosWithdrawingConnectDevice = "AptosWithdrawingConnectDevice",
  AptosWithdrawingValidationError = "AptosWithdrawingValidationError",
  AptosWithdrawingValidationSuccess = "AptosWithdrawingValidationSuccess",
  // Kaspa
  KaspaEditCustomFees = "KaspaEditCustomFees",
  // sui
  SuiStakingValidator = "SuiStakingValidator",
  SuiStakingValidatorSelect = "SuiStakingValidatorSelect",
  SuiStakingAmount = "SuiStakingAmount",
  SuiUnstakingAmount = "SuiUnstakingAmount",
  SuiStakingSelectDevice = "SuiStakingSelectDevice",
  SuiStakingConnectDevice = "SuiStakingConnectDevice",
  SuiStakingValidationError = "SuiStakingValidationError",
  SuiStakingValidationSuccess = "SuiStakingValidationSuccess",
  SuiUnstakingSelectDevice = "SuiUnstakingSelectDevice",
  SuiUnstakingConnectDevice = "SuiUnstakingConnectDevice",
  SuiUnstakingValidationError = "SuiUnstakingValidationError",
  SuiUnstakingValidationSuccess = "SuiUnstakingValidationSuccess",

  CustomImageStep0Welcome = "CustomImageStep0Welcome",
  CustomImageStep1Crop = "CustomImageStep1Crop",
  CustomImageStep2ChooseContrast = "CustomImageStep2ChooseContrast",
  CustomImageStep3Transfer = "CustomImageStep3Transfer",
  CustomImageErrorScreen = "CustomImageErrorScreen",
  CustomImagePreviewPreEdit = "CustomImagePreviewPreEdit",
  CustomImagePreviewPostEdit = "CustomImagePreviewPostEdit",
  CustomImageRemoval = "CustomImageRemoval",

  PostOnboardingHub = "PostOnboardingHub",
  PostOnboardingDebugScreen = "PostOnboardingDebugScreen",
  PostOnboardingMockActionScreen = "PostOnboardingMockActionScreen",
  PostOnboardingDeeplinkHandler = "PostOnboardingDeeplinkHandler",
  NoFunds = "NoFunds",
  Stake = "Stake",

  RedirectToOnboardingRecoverFlow = "RedirectToOnboardingRecoverFlow",

  AnalyticsOptInPromptMain = "AnalyticsOptInPromptMain",
  AnalyticsOptInPromptDetails = "AnalyticsOptInPromptDetails",

  WalletSyncActivationInit = "WalletSyncActivationInit",
  WalletSyncActivationProcess = "WalletSyncActivationProcess",
  WalletSyncSuccess = "WalletSyncSuccess",
  WalletSyncLoading = "WalletSyncLoading",
  WalletSyncActivated = "WalletSyncActivated",
  WalletSyncManageKeyDeleteSuccess = "WalletSyncManageKeyDeleteSuccess",
  WalletSyncUnSynchSuccess = "WalletSyncUnSynchSuccess",
  WalletSyncManageInstancesProcess = "WalletSyncManageInstancesProcess",
  WalletSyncManageInstancesSuccess = "WalletSyncManageInstancesSuccess",
  LedgerSyncDeepLinkHandler = "LedgerSyncDeepLinkHandler",

  MockedAddAssetButton = "MockedAddAssetButton",
  MockedModularDrawer = "MockedModularDrawer",
  MockedWalletScreen = "MockedWalletScreen",
  GenericLandingPage = "GenericLandingPage",

  // Web3Hub
  Web3HubMain = "Web3HubMain",
  Web3HubSearch = "Web3HubSearch",
  Web3HubTabs = "Web3HubTabs",
  Web3HubApp = "Web3HubApp",

  // Add Accountv2 / Receive shared screens
  SelectDevice = "SelectDevice",
  ScanDeviceAccounts = "ScanDeviceAccounts",
  AddAccountsWarning = "AddAccountsWarning",
  NoAssociatedAccounts = "NoAssociatedAccounts",
  LargeMoverLandingPage = "LargeMoverLandingPage",
}

export enum NavigatorName {
  // Stack
  // add "Navigator" postfix to distinguish this from ScreenName.Accounts
  Accounts = "AccountsNavigator",
  Portfolio = "PortfolioNavigator",
  PortfolioAccounts = "PortfolioAccountsNavigator",
  AccountSettings = "AccountSettings",
  AddAccounts = "AddAccounts",
  Card = "CardFlow",
  Exchange = "Exchange",
  ExchangeStack = "ExchangeStack",
  Base = "Base",
  BaseOnboarding = "BaseOnboarding",
  BuyDevice = "BuyDevice",
  CosmosClaimRewardsFlow = "CosmosClaimRewardsFlow",
  CosmosDelegationFlow = "CosmosDelegationFlow",
  CosmosRedelegationFlow = "CosmosRedelegationFlow",
  CosmosUndelegationFlow = "CosmosUndelegationFlow",
  MultiversXClaimRewardsFlow = "MultiversXClaimRewardsFlow",
  MultiversXDelegationFlow = "MultiversXDelegationFlow",
  MultiversXWithdrawFlow = "MultiversXWithdrawFlow",
  MultiversXUndelegationFlow = "MultiversXUndelegationFlow",
  AlgorandClaimRewardsFlow = "AlgorandClaimRewardsFlow",
  AlgorandOptInFlow = "AlgorandOptInFlow",
  ClaimRewards = "ClaimRewards",
  Freeze = "Freeze",
  MyLedger = "MyLedger",
  Onboarding = "Onboarding",
  OnboardingCarefulWarning = "OnboardingCarefulWarning",
  OnboardingPreQuiz = "OnboardingPreQuiz",
  PasswordAddFlow = "PasswordAddFlow",
  PasswordModifyFlow = "PasswordModifyFlow",
  PlatformExchange = "PlatformExchange",
  ReceiveFunds = "ReceiveFunds",
  ReceiveFundsOptions = "ReceiveFundsOptions",
  SendFunds = "SendFunds",
  SendFlow = "SendFlow",
  Settings = "Settings",
  SignMessage = "SignMessage",
  Swap = "SwapNavigator",
  Perps = "PerpsNavigator",
  Earn = "EarnNavigator",
  Fees = "FeesNavigator",
  TezosDelegationFlow = "TezosDelegationFlow",
  TronVoteFlow = "TronVoteFlow",
  Unfreeze = "Unfreeze",
  NoFundsFlow = "NoFundsFlow",
  StakeFlow = "StakeFlow",
  CustomError = "CustomError",

  SignTransaction = "SignTransaction",
  SignRawTransaction = "SignRawTransaction",
  RequestAccount = "RequestAccount",
  RequestAccountsAddAccounts = "RequestAccountsAddAccounts",

  // Evm
  EvmEditTransaction = "EvmEditTransaction",

  // Polkadot
  PolkadotBondFlow = "PolkadotBondFlow",
  PolkadotUnbondFlow = "PolkadotUnbondFlow",
  PolkadotRebondFlow = "PolkadotRebondFlow",
  PolkadotNominateFlow = "PolkadotNominateFlow",
  PolkadotSimpleOperationFlow = "PolkadotSimpleOperationFlow",
  // Solana
  SolanaDelegationFlow = "SolanaDelegationFlow",
  // Stellar
  StellarAddAssetFlow = "StellarAddAssetFlow",
  NotificationCenter = "NotificationCenter",
  Market = "Market",
  // Celo
  CeloManageAssetsNavigator = "CeloManageAssetsNavigator",
  CeloRegistrationFlow = "CeloRegistrationFlow",
  CeloLockFlow = "CeloLockFlow",
  CeloUnlockFlow = "CeloUnlockFlow",
  CeloVoteFlow = "CeloVoteFlow",
  CeloActivateFlow = "CeloActivateFlow",
  CeloRevokeFlow = "CeloRevokeFlow",
  CeloWithdrawFlow = "CeloWithdrawFlow",
  // Cardano
  CardanoDelegationFlow = "CardanoDelegationFlow",
  CardanoUndelegationFlow = "CardanoUndelegationFlow",
  // NEAR
  NearStakingFlow = "NearStakingFlow",
  NearUnstakingFlow = "NearUnstakingFlow",
  NearWithdrawingFlow = "NearWithdrawingFlow",
  // Aptos
  // Hedera
  HederaAssociateTokenFlow = "HederaAssociateTokenFlow",
  HederaDelegationFlow = "HederaDelegationFlow",
  HederaUndelegationFlow = "HederaUndelegationFlow",
  HederaRedelegationFlow = "HederaRedelegationFlow",
  HederaClaimRewardsFlow = "HederaClaimRewardsFlow",
  // SUI
  SuiDelegateFlow = "SuiDelegationFlow",
  SuiUndelegateFlow = "SuiUndelegateFlow",

  CantonOnboard = "CantonOnboard",

  // Tab
  Main = "Main",
  WalletTab = "WalletTabNavigator",
  // Root
  RootNavigator = "RootNavigator",
  Discover = "Discover",

  // Custom Image
  CustomImage = "CustomImage",

  WalletConnect = "WalletConnect",

  PostOnboarding = "PostOnboarding",
  SyncOnboarding = "SyncOnboarding",

  AnalyticsOptInPrompt = "AnalyticsOptInPrompt",
  LandingPages = "LandingPages",

  // Web3Hub
  Web3Hub = "Web3Hub",
  Web3HubTab = "Web3HubTab",

  WalletSync = "WalletSync",
  ModularDrawer = "ModularDrawer",
  DeviceSelection = "DeviceSelection",
  Assets = "Assets",
  Analytics = "Analytics",
}
