export const TOKEN_OUTPUT_FIELDS = [
  "id",
  "name",
  "ticker",
  "symbol",
  "contract_address",
  "standard",
  "decimals",
  "network",
  "network_family",
  "units",
  "type",
  "delisted",
  "chain_id",
  "token_identifier",
  "network_type",
  "meta_currency_id",
  "blockchain_name",
  "live_signature",
] as const;
