export default [
  {
    address: "TLyqzVGLV1srkB7dToTAEqgDSfPtXRJZYH",
    voteCount: 13540171796,
    url: "https://www.binance.com/en/staking",
    isJobs: true,
    name: "Binance Staking",
    brokerage: 20,
  },
  {
    address: "TGj1Ej1qRzL9feLTLhjwgxXF4Ct6GTWg2U",
    voteCount: 982530100,
    url: "http://www.skypeople.co.kr",
    isJobs: true,
    name: "Skypeople",
    brokerage: 0,
  },
  {
    address: "TV9QitxEJ3pdiAUAfJ2QuPxLKp9qTTR3og",
    voteCount: 751248253,
    url: "https://www.bitguild.com",
    isJobs: true,
    name: "BitGuild",
    brokerage: 100,
  },
  {
    address: "TJvaAeFb8Lykt9RQcVyyTFN2iDvGMuyD4M",
    voteCount: 704559359,
    url: "https://poloniex.com/",
    isJobs: true,
    name: "Poloniex",
    brokerage: 0,
  },
  {
    address: "THYPk7Z72REsPrHtZkcwp9pWJadsPxp1UP",
    voteCount: 451296160,
    url: "https://www.beekuaibao.com",
    isJobs: true,
    name: "bitwirespool",
    brokerage: 100,
  },
  {
    address: "TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp",
    voteCount: 394325273,
    url: "https://www.sesameseed.org",
    isJobs: true,
    name: "Sesameseed",
    brokerage: 100,
  },
  {
    address: "TTcYhypP8m4phDhN6oRexz2174zAerjEWP",
    voteCount: 392981887,
    url: "https://www.cryptoguyinza.co.za/",
    isJobs: true,
    name: "CryptoGuyInZA",
    brokerage: 100,
  },
  {
    address: "TUD4YXYdj2t1gP5th3A7t97mx1AUmrrQRt",
    voteCount: 368574248,
    url: "https://www.trongrid.io",
    isJobs: true,
    name: "TRONGrid",
    brokerage: 20,
  },
  {
    address: "TWkpg1ZQ4fTv7sj41zBUTMo1kuJEUWTere",
    voteCount: 344190120,
    url: "https://tronlink.org",
    isJobs: true,
    name: "TRONLink",
    brokerage: 20,
  },
  {
    address: "TPMGfspxLQGom8sKutrbHcDKtHjRHFbGKw",
    voteCount: 331058215,
    url: "https://infstones.io/",
    isJobs: true,
    name: "Infinity-Stones",
    brokerage: 100,
  },
  {
    address: "TY65QiDt4hLTMpf3WRzcX357BnmdxT2sw9",
    voteCount: 330885392,
    url: "https://www.utorrent.com/",
    isJobs: true,
    name: "uTorrent",
    brokerage: 20,
  },
  {
    address: "TTMNxTmRpBZnjtUnohX84j25NLkTqDga7j",
    voteCount: 324218694,
    url: "https://tronspark.com",
    isJobs: true,
    name: "TronSpark",
    brokerage: 100,
  },
  {
    address: "TVFKwzE8qeETLaZEHMx2tjEsdnujAgAWaA",
    voteCount: 317236290,
    url: "http://blockchain.org",
    isJobs: true,
    name: "BlockchainOrg",
    brokerage: 100,
  },
  {
    address: "TTW663tQYJTTCtHh6DWKAfexRhPMf2DxQ1",
    voteCount: 311978510,
    url: "http://tronalliance.org",
    isJobs: true,
    name: "TRONALLIANCE",
    brokerage: 100,
  },
  {
    address: "TFA1qpUkQ1yBDw4pgZKx25wEZAqkjGoZo1",
    voteCount: 309227683,
    url: "https://twitter.com/justinsuntron",
    isJobs: true,
    name: "JustinSunTron",
    brokerage: 20,
  },
  {
    address: "TKSXDA8HfE9E1y39RczVQ1ZascUEtaSToF",
    voteCount: 305787023,
    url: "http://cryptochain.network",
    isJobs: true,
    name: "CryptoChain",
    brokerage: 100,
  },
  {
    address: "TCEo1hMAdaJrQmvnGTCcGT2LqrGU4N7Jqf",
    voteCount: 304967208,
    url: "https://tronscan.org",
    isJobs: true,
    name: "TRONScan",
    brokerage: 20,
  },
  {
    address: "TSNbzxac4WhxN91XvaUfPTKP2jNT18mP6T",
    voteCount: 297084129,
    url: "https://www.bittorrent.com/",
    isJobs: true,
    name: "BitTorrent",
    brokerage: 20,
  },
  {
    address: "TSzoLaVCdSNDpNxgChcFt9rSRF5wWAZiR4",
    voteCount: 295965461,
    url: "http://trx.market",
    isJobs: true,
    name: "TRXMarket",
    brokerage: 20,
  },
  {
    address: "TNaJADoq1u2atryP1ZzwvmEE4ZBELXfMqw",
    voteCount: 295528565,
    url: "http://zempty.peiwo.cn/",
    isJobs: true,
    name: "callmeSR",
    brokerage: 100,
  },
  {
    address: "TVa6MF7SgZa8PToLoQ9PNq6KQHyTXLBz1p",
    voteCount: 294948664,
    url: "http://krypto-knight.us/",
    isJobs: true,
    name: "KryptoKnight",
    brokerage: 100,
  },
  {
    address: "TRTC1DxDg2eWPHmyc3DTGR672rVHoZQa8h",
    voteCount: 294067127,
    url: "https://hitbtc.com",
    isJobs: true,
    brokerage: 100,
  },
  {
    address: "TAHg5zi2ejWeWiE6bqtDT9vfbH3zNTWrfA",
    voteCount: 293559594,
    url: "https://trxultra.org",
    isJobs: true,
    name: "TRXUltra",
    brokerage: 100,
  },
  {
    address: "TMG95kirH4cKW5GnKoCcCye1dBqbt77yGu",
    voteCount: 293110390,
    url: "https://minergate.com",
    name: "MinerGate",
    brokerage: 100,
  },
  {
    address: "TNmas2SUNGJ2R1jq4Sivya5nHDLYN9ggpG",
    voteCount: 290822555,
    url: "http://www.thelast.me",
    isJobs: true,
    name: "TheLastMe",
    brokerage: 20,
  },
  {
    address: "TJ2aDMgeipmoZRuUEru2ri8t7TGkxnm6qY",
    voteCount: 288013274,
    url: "https://www.huobipool.com",
    isJobs: true,
    name: "Huobi_pool",
    brokerage: 100,
  },
  {
    address: "TE7hnUtWRRBz3SkFrX8JESWUmEvxxAhoPt",
    voteCount: 286406965,
    url: "https://www.tronwallet.me/",
    isJobs: true,
    name: "TronWalletMe",
    brokerage: 100,
  },
  {
    address: "TBXB5tobBPCFkC8ihFDBWjaiwW2iSpzSfr",
    voteCount: 152926583,
    url: "https://www.tronvietnam.com/",
    name: "TRONVIETNAM",
    brokerage: 19,
    isJobs: false,
  },
  {
    address: "TVSdAnnZUdSH8gdeUgMPTht1mXmhtEXAN3",
    voteCount: 121803880,
    url: "www.tronspirit.com",
    name: "TRON-BOOM",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TW5oEHAE2LqMdozna7HBDiW6U56f6m8Vfa",
    voteCount: 110007642,
    url: "https://www.tronace.com",
    name: "TRON-Ace",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNMcBfKauBykfamL2YkE8WFNDUBmahQzYx",
    voteCount: 95548726,
    url: "https://tron.newdex.one",
    name: "Newpool-TRON",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TN2MEB71iox2mDwwngdTrUyUZXeENcb79F",
    voteCount: 92810037,
    url: "https://www.tron-europe.org",
    name: "SR-TRON-Europe",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TYVJ8JuQ6ctzCa2u79MFmvvNQ1U2tYQEUM",
    voteCount: 47245305,
    url: "http://tronone.com",
    name: "TRON-ONE",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TPjc5LNkpa5iwjUv8u4XXV92JA2JaAxHgL",
    voteCount: 35000141,
    url: "http://bz.com/",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TQwqK8LhHGria5gkkfCVqQfE5mSwpvdp3B",
    voteCount: 30782033,
    url: "https://tron-society.com",
    name: "Tron-Society",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TGfUjDNr5Huk8DumHfmzY2ksE6RRYpuGLG",
    voteCount: 28656094,
    url: "https://www.beatzcoin.io/",
    name: "BeatzCoin",
    brokerage: 30,
    isJobs: false,
  },
  {
    address: "TN2W4cc7a4dsYyTLiLMWa9m7jVpdLjGvYs",
    voteCount: 27632726,
    url: "https://www.huobiwallet.com/",
    name: "Huobi_Wallet",
    brokerage: 5,
    isJobs: false,
  },
  {
    address: "TEe7HDXdHJemT142R643cajh8BbKdWgR3H",
    voteCount: 18911809,
    url: "\thttps://www.cashierest.com",
    name: "CashierestStaking",
    brokerage: 10,
    isJobs: false,
  },
  {
    address: "TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH",
    voteCount: 6973000,
    url: "https://www.tronics.io/",
    name: "TeamTronics",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TV6qcwSp38uESiDczxxb7zbJX1h2LfDs78",
    voteCount: 6453458,
    url: "Tronstronics",
    name: "TronsTronics",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TEKUPpjTMKWw9LJZ9YJ4enhCjAmVXSL7M6",
    voteCount: 6265541,
    url: "http://www.lianjinshu.com",
    name: "lianjinshu",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSbhZijH2t7Qn1UAHAu7PBHQdVAvRwSyYr",
    voteCount: 6103864,
    url: "https://www.iggalaxy.com",
    name: "Intergalactic-Gaming",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWGGB35HUudizmcLheQN7kANDnD8KfgKkK",
    voteCount: 5086076,
    url: "https://www.tron-family.de",
    name: "TRON-Family",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAD78uBWAveGNg3nDN8Ku18MSDeHmTRpbB",
    voteCount: 4040739,
    url: "XREGlobal.com",
    name: "SmartRealEstateXRE",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TKV52nvtpLe5uapeTabyAYANMQYBXPGVds",
    voteCount: 3530984,
    url: "http://tronkorea.io",
    name: "TronKorea",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TB6nqQpQDoiWm3VKFjxQrEDi7m84jXjfus",
    voteCount: 3408540,
    url: "https://bixin.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TK4qxwmq8nDeymtjxzXMkPzq4Gsb39fkLu",
    voteCount: 3367244,
    url: "https://activ8coin.com",
    name: "Activ8Coin",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TRXDEXMoaAprSGJSwKanEUBqfQjvQEDuaw",
    voteCount: 2841396,
    url: "https://github.com/trondex/",
    name: "TrxDexCom",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDGy2M9qWBepSHDEutWWxWd1JZfmAed3BP",
    voteCount: 2429423,
    url: "http://www.communitynode.org/",
    name: "CommunityNode",
    brokerage: 5,
    isJobs: false,
  },
  {
    address: "TVMP5r12ymtNerq5KB4E8zAgLDmg2FqsEG",
    voteCount: 2274997,
    url: "https://www.cryptogirls.ro/",
    name: "CryptoGirls",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TFQVyHpWSRtH7YbH6xYDamNmKpqBGHmWwc",
    voteCount: 2138672,
    url: "https://www.coinnest.co.kr",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TJgmwx9TYaqujmdthJkjaLyWXrwTCmmTan",
    voteCount: 2028596,
    url: "www",
    name: "ZADEA-MadeInItaly",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TPRxUBEakukBMwTScCHgvCPSBYk5UhfboJ",
    voteCount: 1840547,
    url: "http://www.cryptodiva.io/",
    name: "CryptoDivaSR",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWEcP8CPhcdmmo1R2RANXGBRYAHvxNoLst",
    voteCount: 1734382,
    url: "https://www.millioncoinx.com/pl",
    name: "OneMillionCom_Community",
    brokerage: 50,
    isJobs: false,
  },
  {
    address: "TN8Y2ZztFHW3CrgPYQMK3BPp7VYiHKfvF9",
    voteCount: 1489261,
    url: "https://twitter.com/TronsRocknRoll",
    name: "SexTronsAndRocknRoll",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TA43K3sTFYstnRu5ku7DtyzjsR4MLdUgEu",
    voteCount: 1293775,
    url: "https://www.tronmacau.com",
    name: "TronMacau",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TMEQ4hu7DtLTHPn6qPsYktk1QGdTbAyTEK",
    voteCount: 1242931,
    url: "www.Tron-Europe.com",
    name: "Tron-Europe",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TEsRRMAs4n1yBwzdMuTFEdaKsYANzprtUb",
    voteCount: 1148920,
    url: "https://noraigi.com/en/home",
    name: "NORA-IGI",
    brokerage: 10,
    isJobs: false,
  },
  {
    address: "TMwGtBQioBk2pjCsLWUaQ4rcQNf5DS6FLQ",
    voteCount: 965817,
    url: "http://tronsiqveland.co.uk/",
    name: "siqveland",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TVGYho2v6mUhFMuhYy4sWx8BA79b4FzwSg",
    voteCount: 900163,
    url: "HTTPS://AOCOIN.IO",
    name: "AOCOINIO",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWcebMiHwZbnt6viAtyVEG57bj7DWcZUPx",
    voteCount: 865842,
    url: "https://www.whaleex.com",
    name: "whaleexbp",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TJQHeWxaxaSskBmi7EN19psRe5s9Xn8AcY",
    voteCount: 836166,
    url: "https://www.cityuptake.com",
    name: "mrlavman",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TBzwNEE7D3DdTB4wALiSBaMmpSK7jdoxYF",
    voteCount: 811101,
    url: "https://WINTokenGames.com",
    name: "TRONSiliconValley",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TG519wQRpmBNSzVUiHVx6wkVZkLKmxTXxS",
    voteCount: 801927,
    url: "https://member.alleexchange.com",
    name: "ALLE_Exchange",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAyVDZqhtymJq32itDSxdkRKTRTEb8kkXE",
    voteCount: 778643,
    url: "http://test.com",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TKYW4wDGg3FcaAR8cP8sbmiU8RdZwcK7Bz",
    voteCount: 640203,
    url: "https://WinTokenGames.com",
    name: "WINTokenCommunity",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TZ1ZBqgZ8PUdEk6dxEYwyZCqxYwHj9PmS2",
    voteCount: 432428,
    url: "https://metronix.imba-exchange.co",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TLpWEwR5bXM1GBJ2P3BgXLa8DzWTGsaRPb",
    voteCount: 412997,
    url: "http://tronshares.com",
    name: "TronShares",
    brokerage: 12,
    isJobs: false,
  },
  {
    address: "TFDEzwPqeyKyYGQrXtUTJqiLNKCqBHhVi6",
    voteCount: 408560,
    url: ".",
    name: "TronCommunityGroup",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNddBi3qJv26Ghqqd3qb97ERx47AwMWhR6",
    voteCount: 380161,
    url: "https://www.baggi.co/",
    name: "Segrith1",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TMXiQ2W35fDochXM6dDUrF3ZDnWR2uwcRW",
    voteCount: 345242,
    url: " https://www.phituasesor.com/smart-2/",
    name: "PHI-ECAFE",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TK9qME8revUZ2KfuZApTHwGqqXS9AoTuBX",
    voteCount: 339976,
    url: "https://tran.systems/tronhub/",
    name: "Tronhuborg",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLxcpCwAPTnBVYYrL7JeQCohnLVAfnyQQf",
    voteCount: 304710,
    url: "https://kryptowaluty.org.pl",
    name: "becometa",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TJPgacRkihkAxtsEgH3VY5R6fr8bqykf4j",
    voteCount: 297837,
    url: "https://tronhope.org/",
    name: "TronHope",
    brokerage: 1,
    isJobs: false,
  },
  {
    address: "TCKLRjJmhFABs4Hbjy5S3DBFoytMQ95hS4",
    voteCount: 290004,
    url: "digitalgeotreasure.com/",
    name: "GeoTreasureSR",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TMAbjAuefZqzJAyGhkn4AbWa3jinzcZtGc",
    voteCount: 221492,
    url: "https://mlgblockchain.com",
    name: "MLG-Global",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TX663KZ2dKmLvxhCnyY3rytowLNR4TmdVf",
    voteCount: 218677,
    url: "https://www.musiccasper.com/",
    name: "MusicCasper",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TXnqPcy9zWHYyCiQ7Kmvt3aCx5jm9Qnq3e",
    voteCount: 194014,
    url: "https://TRON-Want",
    name: "TRON-Want",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TYftfpnCitoxju9rMYx6XNegUHmFoPMary",
    voteCount: 177999,
    url: "https://reyna.exchange/",
    name: "ReynaExchange",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TXUqMBAisbzUg3myoZys7q9wQqafyUUJib",
    voteCount: 172148,
    url: "https://pyro.network",
    name: "PYRO-Network",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TKXnhSWxKAfYhsYLkh5wS8qUT1ESBbMSpn",
    voteCount: 158782,
    url: "https://promo.network/",
    name: "PROMO-NETWORK",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TWjGyMHSxx4pJ3V4ES5E4ANE2NWW9xcWcp",
    voteCount: 153874,
    url: "https://tronvote.club",
    name: "TronVote",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TAKFctfLwhcUwU7PPfijB35GzpPuiph2XE",
    voteCount: 151162,
    url: "https://twitter.com/mr_oceanview",
    name: "oceanview",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TJX4T7AgfkvWbNAyWTxhgXrJv6Yed6BgDx",
    voteCount: 150655,
    url: "https://www.tron-mining.com",
    name: "TRON-MINING",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TSyG9BdjsGE2GoHG9eeYKMns6zMQFDmbvS",
    voteCount: 143464,
    url: "xreglobal.com",
    name: "TarquinRealEstate",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TGnTYAB6XjLWoAGYXmDoLeLeX9X59JFBVK",
    voteCount: 137713,
    url: "https://cobo.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGiDnq7cxAFwProHPo8MFwhs7C5PU7EyJR",
    voteCount: 137468,
    url: "https://twitter.com/1000WONG",
    name: "1000WONG",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "THM4SAoJrNebe8zdQJ8d6eu41XFHHNbb8N",
    voteCount: 135459,
    url: "https://CharityCompassionCoin.com",
    name: "CharityCompassionCoin-CCC",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TYTYuSyiEpxNsjakQSRmjiZAymvxoBbziH",
    voteCount: 132619,
    url: "https://www.tronlabs.ro",
    name: "TronLabsRomania",
    brokerage: 40,
    isJobs: false,
  },
  {
    address: "TTENv9A7zf543xdVmnaon42SqsGGd7L7p8",
    voteCount: 117016,
    url: "https://bankroll.network",
    name: "Bankroll_Network",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFcBLX6W4u7xAFYvcyUDEHT6Cy7GroVLfD",
    voteCount: 114945,
    url: "https://tronbet.com",
    name: "TRONbet",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TA8VRz8ofdpmqAvxTKDVGkQRHRWxmRTXGA",
    voteCount: 112022,
    url: "https://tronpad.com",
    name: "TRONPADCOM",
    brokerage: 1,
    isJobs: false,
  },
  {
    address: "TZ8NZA6PPKSK2wHuFAo8vzf4VZnMtmDugF",
    voteCount: 109435,
    url: "https://t.me/tron_my",
    name: "Surface-Foundation",
    brokerage: 25,
    isJobs: false,
  },
  {
    address: "TNkRSKWP7VvdrisTwC8iNzUV6MRoEJh6xx",
    voteCount: 105111,
    url: "https://healthport.io/",
    name: "Health-Port-EHR-Issuing-Account",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TSRmKPv8kvokcHKfLeySQ3gNHyYrAAXrnc",
    voteCount: 100520,
    url: "http://dapps.house",
    name: "DAPPHOUSE",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TD4anu8auWfCDYqQpAEcLXVK6UgME9Jsid",
    voteCount: 97105,
    url: "https://tronsecure.io",
    name: "TronSecure-Super-Representative",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TE7BWvxSPbsxZ5MVFFLfmkDnBw3MRFQGtw",
    voteCount: 82676,
    url: "https://sites.google.com/view/proudbtc1nvest/startsida",
    name: "ProudBTC1nvest",
    brokerage: 0,
    isJobs: false,
  },
  {
    address: "TAXZHpzFwGdqMzF7w8KkFhWkikGY12yUpk",
    voteCount: 82613,
    url: "https://dexnode.net",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTCrBKXyTCS2B5ktjivNtHiSyCPTCLWv3v",
    voteCount: 75808,
    url: "https://www.tronvietnam.org",
    name: "TronVietNam",
    brokerage: 15,
    isJobs: false,
  },
  {
    address: "TTuT2AG5q37f74zra7PjAApUmyVaXmFvC4",
    voteCount: 75028,
    url: "http://raybo.com",
    name: "RayboTron",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TUHkTGbNAYWVbJ8WCcUJj66ui1nrFd9k2m",
    voteCount: 60390,
    url: "https://huxlium.org",
    name: "Huxliumworkforce",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TDdYEXqbqYGXaufkh2kiZhFQA3oi6A8yoi",
    voteCount: 54303,
    url: "https://www.tronboston.com",
    name: "TronBoston",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGBnYeW24FC9zcVmV3T2Vrz21hJQrHWfJW",
    voteCount: 50126,
    url: "https://www.tron.buzz",
    name: "Swisstron",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDJ8A5jRuAmb2ctYvZcwtPQaGDv33sVbDD",
    voteCount: 30832,
    url: "https://tronlottery.io",
    name: "TronLottery",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TMs377k86n2NXwoZoN6gNCf929u6BKdbvn",
    voteCount: 30001,
    url: "https://twitter.com/black0din",
    name: "odintron",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TCf5cqLffPccEY7hcsabiFnMfdipfyryvr",
    voteCount: 29284,
    url: "http://TronGr20.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TN9rYynDSPinTuvRg8G1TdrEjAc2f3X2dX",
    voteCount: 22936,
    url: "http://www.tron-france.com",
    name: "Tron-France",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TBkF5gRmwxq4Zm4K7oBMHvfvUKxD8KYkJ5",
    voteCount: 20821,
    url: "http://tronjapan.io",
    name: "TRONJAPAN",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "THX1ZF1CNdcDMNai2QUSYgdBmsECah6vtJ",
    voteCount: 20658,
    url: "https://www.thz.net",
    brokerage: 11,
    isJobs: false,
  },
  {
    address: "TU5gKG2QrysL4wmjM6ydonVDcEtupuVHCN",
    voteCount: 19392,
    url: "https://dexexchange.us",
    name: "DEXExchange-DEXCOIN",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TS4vTdFRNJCHZex8j7bozAiRXGXvtRjhAF",
    voteCount: 13457,
    url: "https://teamhelios.org/",
    name: "TEAMHELIOS",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "THWCmwMwtc97qDd1fqkeK8LBwSPgwTeq79",
    voteCount: 13328,
    url: "https://www.neoply.com",
    name: "NEOPLY-TRON",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TN8jmSQv79QHa37cckKMguDyf3vAKtpvDs",
    voteCount: 12208,
    url: "tronsr",
    name: "BlockChainRealEstate",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TLTeJxavvgAC5opkDXfXfhRXp4thLfHL5p",
    voteCount: 12204,
    url: "https://weibo.com/bitdog666",
    name: "BitDogSR",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TELjcuZeP3vCXjq2zvgLsi7dNQry6pDKn5",
    voteCount: 8976,
    url: "http://the-crazy-once.de",
    name: "SteveJobs",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TX3ZceVew6yLC5hWTXnjrUFtiFfUDGKGty",
    voteCount: 8791,
    url: "http://TronGr18.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TCjwPyWLgry8dD8QCgpYv7cvKe6oK5PM1j",
    voteCount: 7844,
    url: "https://theseusx.net",
    name: "theseusx",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TUpoK1NUFcXpVjn7AvTsSCAYwD559CEaxr",
    voteCount: 7070,
    url: "https://trip4web.com",
    name: "TrIP4web",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TQxyQu5d76MaxsEF4nBf9tFa8s93nSHe8M",
    voteCount: 6859,
    url: "http://tronpro.io",
    name: "tronproio",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLaqfGrxZ3dykAFps7M2B4gETTX1yixPgN",
    voteCount: 6831,
    url: "http://TronGr17.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRSZydUjAZaA5aMYA21J9iWriNF1q1bwzW",
    voteCount: 6283,
    url: "https://www.troncanada.com/",
    name: "TRONCanada",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TUbPJqc7pw9iSkWC2a3dWJAThSnnesAwFq",
    voteCount: 6020,
    url: "https://www.hashfin.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRKJzrZxN34YyB8aBqqPDt7g4fv6sieemz",
    voteCount: 6007,
    url: "http://TronGr24.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "THKJYuUmMKKARNf7s2VT51g5uPY6KEqnat",
    voteCount: 5783,
    url: "http://TronGr1.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLCuBEirVzB6V4menLZKw1jfBTFMZbuKq7",
    voteCount: 5597,
    url: "https://game.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFuC2Qge4GxA2U9abKxk1pw3YZvGM5XRir",
    voteCount: 5501,
    url: "http://TronGr11.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWwaKmzCGF4Hka99GHuR8Waz1mrEtkByeN",
    voteCount: 5496,
    url: "https://www.troninvestgroup.org",
    name: "TronInvestGroup",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TQQ6akqQfkUoB26PfnkLkEqKoh1BNvQoFs",
    voteCount: 5252,
    url: "https://www.bitcoinworld.com/",
    name: "BitcoinWorld",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLF5cNeWQKGUyDDHebQnLTfCNCKGCb4wiu",
    voteCount: 5109,
    url: "https://tronvip.io",
    name: "TeamTronVIP",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWeZZDaDu63CebHsnDGUhsKAZ2cHz7uFJt",
    voteCount: 5056,
    url: "http://www.nodecap.com/",
    name: "NodeCapital",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYNh7Td8z7jga1tZYvkZvn4AKxq8aPmGZm",
    voteCount: 5012,
    url: "http://newgenesiscap.com/",
    name: "genesiscap",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TH4nPzmbioavDew4GPxD4hHzsLXAetDFSA",
    voteCount: 5004,
    url: "https://tron.34rth.com/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWmYacoioZVVDn3jwVCd28sEJpJARyybSF",
    voteCount: 4450,
    url: "http://bt.co",
    name: "BitTorrentNow",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFYhSxKGD7Ysqi96wozmpGw5P3vC324Kem",
    voteCount: 4360,
    url: "https://helloworldteam.org",
    name: "HelloWorld",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGK6iAKgBmHeQyp5hn3imB71EDnFPkXiPR",
    voteCount: 4236,
    url: "http://TronGr16.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TM2WoRPjYAWjJuR6QSZgaGWkr2qDP2d6sA",
    voteCount: 4100,
    url: "http://tron-man.com/",
    name: "Tron-Man",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNHpUuakVeceLagF9k6j8HU9KruSQ23cXW",
    voteCount: 3676,
    url: "https://www.google.com/",
    name: "TronWatch",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TNEqakRxoJ1YsLK2t5c57vZyWWbDpetq7y",
    voteCount: 3552,
    url: "https://www.gameoftron.net/",
    name: "GameOfTron",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNGoca1VHC6Y5Jd2B1VFpFEhizVk92Rz85",
    voteCount: 3365,
    url: "http://TronGr12.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TK6V5Pw2UWQWpySnZyCDZaAvu1y48oRgXN",
    voteCount: 3257,
    url: "http://TronGr6.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYy6xnc35LkyEuU9fJv4x89vkhLZim1yJv",
    voteCount: 3087,
    url: "http://www.etherpoker.cc",
    name: "EtherPoker",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TVDmPWGYxgi5DNeW8hXrzrhY8Y6zgxPNg4",
    voteCount: 3050,
    url: "http://TronGr2.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGgF85TNinitZZ1zTf1bKbUyTByAxHLd7G",
    voteCount: 2926,
    url: "https://t.me/joinchat/F5QrYU9C8y-nAN2w0M327Q",
    name: "HOLDTRON",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDarXEG2rAD57oa7JTK785Yb2Et32UzY32",
    voteCount: 2731,
    url: "http://TronGr4.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TMXamLGmArfCEFoVXbrvbyXpzMT2Tq1FBy",
    voteCount: 2453,
    url: 'Change Your Vote From This SR Position, To Our New SR Position: "DEXExchange-DEXCOIN"',
    name: "DEXExchange-DEXCOIN-XDEX",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TWm3id3mrQ42guf7c4oVpYExyTYnEGy3JL",
    voteCount: 2452,
    url: "http://TronGr9.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEuVwDCt4qGehQTg7DJEC1EsJHpTkWHhqJ",
    voteCount: 2039,
    url: "http://www.meg4tron.com/",
    name: "MEG4TRON",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRLnLri5w7q9VigSeTJEjog4RuVtwoqvCr",
    voteCount: 2001,
    url: "https://mdt.co",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEEzguTtCihbRPfjf1CvW8Euxz1kKuvtR9",
    voteCount: 1839,
    url: "http://TronGr14.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRE6JANcQBfmXTDooRyStoALZNWvEgNpsE",
    voteCount: 1643,
    url: " ",
    name: "Tronbite",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TRMP6SKeFUt5NtMLzJv8kdpYuHRnEGjGfe",
    voteCount: 1626,
    url: "http://TronGr25.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSkXBuJBsnjdVFADqU2CsmD6YaCuxN7AHe",
    voteCount: 1589,
    url: "https://antpool.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEVAq8dmSQyTYK7uP1ZnZpa6MBVR83GsV6",
    voteCount: 1525,
    url: "http://TronGr23.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAa14iLEKPAetX49mzaxZmH6saRxcX7dT5",
    voteCount: 1501,
    url: "http://TronGr21.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDEhi48MepJYzdb2XfEKe294prSiMssmTx",
    voteCount: 1405,
    url: "http://www.trongalaxy.io",
    name: "trongalaxy",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TBzaVm3e3QmoaG5xjR98DNqZE9bYwqgZcg",
    voteCount: 1378,
    url: "https://trx.bitcoingod.org",
    name: "BitcoinGOD",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGXRA72hwr47NDezgfSqhBJczxsYFQcK2H",
    voteCount: 1377,
    url: "http://VeganIS.ME/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TJz3YaEaeceU3qhsanaomQp9oomR2Rbecf",
    voteCount: 1364,
    url: "www.tronixglobal.com",
    name: "Tronix_Global",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TVsofxarmK6TYPzF7QkYsKxUhYtKFzrsRW",
    voteCount: 1357,
    url: "https://coinhe.io",
    name: "COINHEIO",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFuWG1FeQ3CXTsXnuydHahy3JsZZy11w5M",
    voteCount: 1312,
    url: "https://globalricetoken.wixsite.com/grttoken",
    name: "Lucky2019YearOfThePig",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDbNE1VajxjpgM5p7FyGNDASt3UVoFbiD3",
    voteCount: 1214,
    url: "http://TronGr26.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTyNZXwUjF9g8us4HUgEXMvNuzRkcvopbL",
    voteCount: 1176,
    url: "http://tronbitcoin.io",
    name: "TRONBITCOIN",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TNi5gk1xVLR3QddJ5t6ReraYed63WjWGPj",
    voteCount: 1153,
    url: "ffgtrgh",
    name: "smoksolutios",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TBWMoK75hMmjRUtDrEEweA7g8nkSPUzDjG",
    voteCount: 1087,
    url: "http://www.ocoins.cc/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TQ4EtNraCeAh4xkw7xLGiWZMbtMtbBv7Bj",
    voteCount: 1076,
    url: "https://trontx.com",
    name: "TronTexas",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TCvwc3FV3ssq2rD82rMmjhT4PVXYTsFcKV",
    voteCount: 1000,
    url: "http://TronGr10.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTTZFEVSxpZ8gVHwJVs6yhzBuN4xbHuoES",
    voteCount: 876,
    url: "www.tbd.com",
    name: "--BANK--",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "THWeUoi3HYEnLDXigeyejjFSFAMaAJGnDU",
    voteCount: 864,
    url: "VoteTronicStorm",
    name: "TronicStorm",
    brokerage: 15,
    isJobs: false,
  },
  {
    address: "TGK8YYb9bJVnkw2hRFG1FyNVvXuqkWB4VD",
    voteCount: 803,
    url: "https://trongameglobal.network",
    name: "TronGameGlobal",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TQq5ynrFUoDt338dXSWM4abFfF8YQ1PysX",
    voteCount: 752,
    url: "https://www.trxkings.com",
    name: "TRXKings",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TQNCne1UuKFmihsHjzebNSob7nS9xk9JNL",
    voteCount: 750,
    url: "https://TRXGUARDIAN.ORG",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYEYCoYyKdH2zekWo7fy77sALpQJmSTixr",
    voteCount: 653,
    url: "http://www.dagbvi.com",
    name: "Tron-DAG",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TG6Nn9pnTv6XLKqoda1CHpaEYYFfyLS9T6",
    voteCount: 645,
    url: "http://jdi.group",
    name: "JDI-Venture",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEbYtf3gRudzLGEGhfqxkVuUWsNAqmjCLi",
    voteCount: 641,
    url: "https://www.robocoinexchange.com",
    name: "RoboCoin",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFsgyrtVwUFdc5uZSprhyBJNQzpuoMXjwC",
    voteCount: 621,
    url: "https://tronkh.org",
    name: "TRONCAMBODIA",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TC1ZCj9Ne3j5v3TLx5ZCDLD55MU9g3XqQW",
    voteCount: 611,
    url: "http://TronGr8.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDpzrQUkUuMBsx67HXByZZNT6u9PUvbifE",
    voteCount: 600,
    url: "http://www.linkvc.com/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGZdwPPqsR3B9JghJryozpBtZz3kbDEjGM",
    voteCount: 600,
    url: "https://DoNotVote-Not-Active-SR",
    name: "MyTronScan-FullNode",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDGAnbNhYA1dsbPSF2RBNEu1fz4c2vRWbU",
    voteCount: 580,
    url: "https://www.museprotocol.com",
    name: "Muse_Incorporated",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TBYsHxDmFaRmfCF3jZNmgeJE8sDnTNKHbz",
    voteCount: 529,
    url: "http://TronGr22.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTxt1K49riY6FvAkk84xJzBEBPtMbFa85M",
    voteCount: 512,
    url: "https://global.bittrex.com/",
    name: "BittrexStaking",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSeJtWDCowLuYnibVsZVr3N2U3ypVap5hG",
    voteCount: 510,
    url: "https://tronswap.io",
    name: "TronSwap",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNRKgJ6Le7xLsewFayFonaVhftxV5KNVnC",
    voteCount: 505,
    url: "http://www.tronium.net",
    name: "TRONIUM-SR",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TJuRfL3tRdSQvVPKDXi6FRivcbZpsbz7AD",
    voteCount: 502,
    url: "http://www.apexinformatics.com",
    name: "ApexInformatics",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TKEppdcqcY73hgeL9ogta6ZoXR1jfzA2gV",
    voteCount: 501,
    url: "http://d2fapp.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRni6NxF8CQVcywcDm67sEpCYCo7BUGXCD",
    voteCount: 498,
    url: "https://youtu.be/pWhw_NjVV68",
    name: "FreeSpace",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TJE3hXDseyEgwv31QzysrNBJyDjEhVDBVQ",
    voteCount: 407,
    url: "Https://www.numeriuno.eu",
    name: "PRESIDENT",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TZ2iD3EW2fGSkez7zZXEo7VwXhQPPXRkVR",
    voteCount: 360,
    url: "http://bit.ly/libertytron",
    name: "rewards-for-all-not-just-for-SR",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLCjmH6SqGK8twZ9XrBDWpBbfyvEXihhNS",
    voteCount: 340,
    url: "http://TronGr13.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLTDZBcPoJ8tZ6TTEeEqEvwYFk2wgotSfD",
    voteCount: 315,
    url: "http://TronGr27.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDirsgwgL8i95nzQqyPZ6XuHv9jvJQfTmF",
    voteCount: 300,
    url: "http://hqn.vn",
    name: "vongabau",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNaMNHgtqS763tXwbzGDRhn5qUL9RwfcTn",
    voteCount: 300,
    url: "https://tronix.international/",
    name: "TronixInternational",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNfqpGrR3v4bQo8jemVyEpiUGFipQxj8sH",
    voteCount: 250,
    url: "www.dtroynx.com",
    name: "TheProphet",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTDY8aQQizYCHA7qdmgtLgPNEe2YWEfPZa",
    voteCount: 200,
    url: "https://www.teamx.com",
    name: "TEAMX-SR",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TMNUDeyr6ZEW8vHAUnaKi2Bbgi14TPq63q",
    voteCount: 167,
    url: "https://cobo.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TA5Ub5djuEe8naTMxyXyRoKjemqFiE3RmC",
    voteCount: 163,
    url: "firekraken.media",
    name: "FireKrakenMedia",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TPtryrrXSVT9cefs4wvL3ks2J5sr8PJLcg",
    voteCount: 162,
    url: "https://tronblock.co",
    name: "TronBlock",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TX9nw7PXpGHLqRNMWmj8izyNvzy7JU5qXi",
    voteCount: 159,
    url: "http://www.troncenter.com",
    name: "TronCenter",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDo2qwRLEkTZCXzcotiEQLt2wLeTttKTnZ",
    voteCount: 154,
    url: "http://www.tron.school/",
    name: "TronSchool",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSQ8c97uCRG5ZugLDZ8jdbhtktNLgh6f26",
    voteCount: 140,
    url: " ",
    name: "AurumCryptoCompany",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGuS4RVh8wpQCtAdxij6pYSk9ur6J8fsmb",
    voteCount: 127,
    url: "http://he.capital/",
    name: "Happy_East_Capital",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TZHvwiw9cehbMxrtTbmAexm9oPo4eFFvLS",
    voteCount: 125,
    url: "http://TronGr15.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAEw4zwwYMiDcWFC9xQrLP9moMi34YAZbz",
    voteCount: 114,
    url: "http://imcash.io",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TVQ6wERJ4YBd1TqH9bdYT1VV93CP393eiT",
    voteCount: 106,
    url: "https://www.tronbet.io",
    name: "TRON-Bet",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYqxoFgQLtq7f146uJS533GMU88nEpwKgz",
    voteCount: 104,
    url: "https://www.gm-informatics.com",
    name: "GM-Informatics-SR-001",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAmFfS4Tmm8yKeoqZN8x51ASwdQBdnVizt",
    voteCount: 103,
    url: "http://TronGr5.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWKZN1JJPFydd5rMgMCV5aZTSiwmoksSZv",
    voteCount: 102,
    url: "http://TronGr3.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TAhXnVYaAKx6xa8E6JeASR5SrGXHSeyqaL",
    voteCount: 100,
    url: "https://rinzler.eu",
    name: "RinzlerSR",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "THyFzhbcfWw2CJa4eAaHRCst3d5hnyqXLL",
    voteCount: 100,
    url: "https://www.livenodes.network/",
    name: "LivenodesNetwork",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TPsQ4XsQEFwSWGr2Zae62kuo69MABA1cVU",
    voteCount: 100,
    url: "http://www.contactnetwork.fr/",
    name: "FedayKeen",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TL8rrg2ZNPHtpPFp3j2nwH9BLhN7qg32dh",
    voteCount: 90,
    url: "https://cobo.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSEHJbvpnevJP4zR3uTgXJ1toZ16bPz3uW",
    voteCount: 80,
    url: "https://zhizhu.top/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TRAzTRvjfd7TCqfUkB1zJ6vMv7Y7F7puZr",
    voteCount: 63,
    url: "https://www.vena.network",
    name: "Vena_Family",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGMZpmGpx8KTGJc8NzBkEBnfzpWGp9Rar8",
    voteCount: 60,
    url: "http://www.nextgenius.com.au",
    name: "NextGenius",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TXSh73A7dwbQU3Navx5217hf9Yjp3QEGD1",
    voteCount: 56,
    url: "https://t.me/TronParty",
    name: "LUCKYGAMES",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFkHXapDnFCq8Cw4LFUzM3cSe6EGnMb4pk",
    voteCount: 54,
    url: "https://atticlab.net",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TXio2SKopbzwyZ5XPxfFwceBFFHDKjEvUZ",
    voteCount: 53,
    url: "www",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TQANnQ4DwspKuuF3BCvaukwXGHD4G36XGH",
    voteCount: 52,
    url: "https://mobile.twitter.com/busyblaze",
    name: "BlakeStorie",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TGqFJPFiEqdZx52ZR4QcKHz4Zr3QXA24VL",
    voteCount: 51,
    url: "http://TronGr7.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TMofnVBZeuFTrkYAnQ54TDWNyMbrHzXkwy",
    voteCount: 51,
    url: "https://twitter.com/@brianjun09",
    name: "BrianJun_Web",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TZBABURn1nNxw63QiezbTvhRPmFjomSz2Q",
    voteCount: 45,
    url: "https://cryptotalkers.com",
    name: "RB-Main-L",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TCmubWCoL7cLA2VDkVn4WGWCT7nqcFavXX",
    voteCount: 42,
    url: "https://twitter.com/KaanKOZANn",
    name: "KaanKOZAN",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEVwq7bwFf6ToBu8M3ydD96tnVPyGXf394",
    voteCount: 40,
    url: "https://darano.network/",
    name: "daranonetwork",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TK1Q72E87K9T8evFW2ucBGByf96WEbX777",
    voteCount: 37,
    url: "https://molotovlab.com",
    name: "MolotovLab",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "THpWeDXW422Suo5fNZtz1XU8kpPJ3jo4q1",
    voteCount: 35,
    url: "https://www.rightbtc.com",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TLipnfPL5ajqYB9eqEJuaUBqr2jEG75X2B",
    voteCount: 35,
    url: "https://gconnect.io/",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TFxanMr7ffV9YsbXcaSzA9Eja7AA318rha",
    voteCount: 31,
    url: "http://tronman.io/",
    name: "TRONMANkr",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TTiAHqKadiLPVZjiKaAjHDXkq7sfEozQZr",
    voteCount: 31,
    url: "Can",
    name: "Cancancan",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TPVMxXoci8SAoJMF1Xyqzethg4Qzoh51Z7",
    voteCount: 30,
    url: "https://www.facebook.com/sevo.nikolov",
    name: "SevoNikolovTRX",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TSeU7Sa22kRVo2gUSt47S6PiW8NRktPt8o",
    voteCount: 27,
    url: "https://a4oo.ml",
    name: "a4ooooooo",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TEsuA4ULsZwfvSRSbu8yx7K3UB6aLi5Djn",
    voteCount: 26,
    url: "http://t.me/TheL1Crew",
    name: "TheL1Crew",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TU5Td1DnsL84aeoMXTm7HGW7Nt5kuxHoCs",
    voteCount: 26,
    url: "https://gsc.social",
    name: "GSC-GlobalSocialChain",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TVMC8C7Y4f4ABr48PJencVdunVVB4XUW96",
    voteCount: 26,
    url: "https://dootron.com/en/home",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TNd2MPxccwBZoqpJuCrDEeNJizx5tmyNLs",
    voteCount: 25,
    url: "www.upvote.world TBD",
    name: "TRAC_REG",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TC1yZaa75GPPzM26pxfSP3AxsPT8yartQR",
    voteCount: 24,
    url: "https://twitter.com/Filo_0x",
    name: "CBD-OIL-NETWORK-TOKEN",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TMykaWQe9YinNb36yE5k4MH9VUEGyKgQQA",
    voteCount: 23,
    url: "https://www.wunderchain.com",
    name: "testmain",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TWT4BantYCwgQCN9ubxd8Lz765Sw8yv8iL",
    voteCount: 22,
    url: "    ",
    name: "ROCA-TRON",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TC34KZDLwARaBrZ2B8eet9GqgLGDpvifiz",
    voteCount: 20,
    url: "http://blog.naver.com/coolkim01",
    name: "Peterkim7238",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TDUjtGPXM6UJkxREWyNV53c9r1L5ZVJLPb",
    voteCount: 20,
    url: "https://reyna2.com",
    name: "justanthonyhero",
    brokerage: 100,
    isJobs: false,
  },
  {
    address: "TLyKxzA5QUkV6R4PCZKZiLaKeoyT5qnEAA",
    voteCount: 19,
    url: "https://c773.com/",
    name: "C773Tron",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TPr4Po9LHUuxqfuRyjpiWctkP39EbpujXH",
    voteCount: 18,
    url: "https://t.me/ONGISTRON_NewsChannel",
    name: 'ONGISTRONb\u0004" ',
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYShuadcBNBKgk8UgxsnB43yeBdyioswHh",
    voteCount: 12,
    url: "http://www.tronfans.info",
    brokerage: 20,
    isJobs: false,
  },
  {
    address: "TYednHaV9zXpnPchSywVpnseQxY9Pxw4do",
    voteCount: 10,
    url: "http://TronGr19.com",
    isJobs: false,
  },
];
