import { MODULAR_DRAWER_ADD_ACCOUNT_STEP } from "LLD/features/AddAccountDrawer/domain";

export const ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP = {
  ...MODULAR_DRAWER_ADD_ACCOUNT_STEP,
  VIEW_KEY_WARNING: "VIEW_KEY_WARNING",
  VIEW_KEY_APPROVE: "VIEW_KEY_APPROVE",
} as const;

export type AleoModularDrawerAddAccountStep =
  (typeof ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP)[keyof typeof ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP];

export const ALEO_ADD_ACCOUNT_STEP_ORDER: AleoModularDrawerAddAccountStep[] = [
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.CONNECT_YOUR_DEVICE,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.VIEW_KEY_WARNING,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.SCAN_ACCOUNTS,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.VIEW_KEY_APPROVE,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.ACCOUNTS_ADDED,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.ACCOUNTS_WARNING,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.SELECT_ACCOUNT,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.EDIT_ACCOUNT_NAME,
  ALEO_MODULAR_DRAWER_ADD_ACCOUNT_STEP.FUND_ACCOUNT,
];
