#!/usr/bin/env node
/**
 * Bundles snarkjs + circuit assets into a self-contained HTML page
 * that can be loaded in a React Native WebView for Groth16 proving.
 *
 * Usage: node scripts/generateZkHtml.js
 */
const fs = require("fs");
const path = require("path");

const APP_ROOT = path.join(__dirname, "..");

const snarkjsPath = path.join(APP_ROOT, "node_modules/snarkjs/build/snarkjs.min.js");
const wasmPath = path.join(APP_ROOT, "assets/zk/ageVerification.wasm");
const zkeyPath = path.join(APP_ROOT, "assets/zk/ageVerification.zkey");
const vkeyPath = path.join(APP_ROOT, "assets/zk/verification_key.json");

const snarkjsJs = fs.readFileSync(snarkjsPath, "utf-8");
const wasmB64 = fs.readFileSync(wasmPath).toString("base64");
const zkeyB64 = fs.readFileSync(zkeyPath).toString("base64");
const vkey = fs.readFileSync(vkeyPath, "utf-8").trim();

const htmlContent = `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<script>${snarkjsJs}</script>
<script>
var WASM_B64 = "${wasmB64}";
var ZKEY_B64 = "${zkeyB64}";
var VKEY = ${vkey};

function b64ToUint8Array(b64) {
  var bin = atob(b64);
  var arr = new Uint8Array(bin.length);
  for (var i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

window.executeCommand = async function(jsonString) {
  var msg = JSON.parse(jsonString);
  var id = msg.id;
  var command = msg.command;
  var params = msg.params;
  try {
    if (command === "generateProof") {
      var wasmBuf = b64ToUint8Array(WASM_B64);
      var zkeyBuf = b64ToUint8Array(ZKEY_B64);
      var result = await snarkjs.groth16.fullProve(params, wasmBuf, zkeyBuf);
      window.ReactNativeWebView.postMessage(JSON.stringify({
        id: id, type: "result", payload: { proof: result.proof, publicSignals: result.publicSignals }
      }));
    } else if (command === "verifyProof") {
      var valid = await snarkjs.groth16.verify(VKEY, params.publicSignals, params.proof);
      window.ReactNativeWebView.postMessage(JSON.stringify({
        id: id, type: "result", payload: { valid: valid }
      }));
    } else {
      throw new Error("Unknown command: " + command);
    }
  } catch(err) {
    window.ReactNativeWebView.postMessage(JSON.stringify({
      id: id, type: "error", payload: err.message || String(err)
    }));
  }
};

window.ReactNativeWebView.postMessage(JSON.stringify({ type: "ready" }));
</script></head><body></body></html>`;

// Escape backticks and dollar signs for template literal
const escaped = htmlContent.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

const output = `// AUTO-GENERATED by scripts/generateZkHtml.js — DO NOT EDIT
// Re-generate with: node scripts/generateZkHtml.js
export const zkProofHtmlPage = \`${escaped}\`;
`;

const outPath = path.join(
  APP_ROOT,
  "src/mvvm/features/PassportAttestation/utils/zkProofHtml.ts",
);
fs.writeFileSync(outPath, output);

const sizeKB = Math.round(Buffer.byteLength(output) / 1024);
console.log(`Generated zkProofHtml.ts (${sizeKB} KB)`);
