import { PageHolder } from "./abstractClasses";
import { AccountPage } from "./account.page";
import { AccountsPage } from "./accounts.page";
import { PortfolioPage } from "./portfolio.page";
import { MarketPage } from "./market.page";
import { AddAccountModal } from "./modal/add.account.modal";
import { Layout } from "../component/layout.component";
import { Modal } from "../component/modal.component";
import { ReceiveModal } from "./modal/receive.modal";
import { SpeculosPage } from "./speculos.page";
import { SendModal } from "./modal/send.modal";
import { Drawer } from "../component/drawer.component";
import { SettingsPage } from "./settings.page";
import { LedgerSyncDrawer } from "./drawer/ledger.sync.drawer";
import { SwapPage } from "./swap.page";
import { SwapConfirmationDrawer } from "./drawer/swap.confirmation.drawer";
import { delegateModal } from "./modal/delegate.modal";
import { DelegateDrawer } from "./drawer/delegate.drawer";
import { SendDrawer } from "./drawer/send.drawer";
import { AssetDrawer } from "./drawer/asset.drawer";
import { PasswordlockModal } from "./modal/passwordlock.modal";
import { LockscreenPage } from "./lockscreen.page";
import { NFTDrawer } from "./drawer/nft.drawer";
import { NftGallery } from "./nftGallery.page";
import { AssetPage } from "./asset.page";
import { SettingsModal } from "./modal/settings.modal";
import { OnboardingPage } from "./onboarding.page";
import { OperationDrawer } from "./drawer/operation.drawer";
import { LiveApp } from "./liveApp.page";

export class Application extends PageHolder {
  public account = new AccountPage(this.page);
  public drawer = new Drawer(this.page);
  public accounts = new AccountsPage(this.page);
  public portfolio = new PortfolioPage(this.page);
  public market = new MarketPage(this.page);
  public addAccount = new AddAccountModal(this.page);
  public layout = new Layout(this.page);
  public modal = new Modal(this.page);
  public receive = new ReceiveModal(this.page);
  public speculos = new SpeculosPage(this.page);
  public send = new SendModal(this.page);
  public delegate = new delegateModal(this.page);
  public settings = new SettingsPage(this.page);
  public ledgerSync = new LedgerSyncDrawer(this.page);
  public swap = new SwapPage(this.page);
  public swapDrawer = new SwapConfirmationDrawer(this.page);
  public delegateDrawer = new DelegateDrawer(this.page);
  public sendDrawer = new SendDrawer(this.page);
  public assetDrawer = new AssetDrawer(this.page);
  public password = new PasswordlockModal(this.page);
  public LockscreenPage = new LockscreenPage(this.page);
  public nftDrawer = new NFTDrawer(this.page);
  public nftGallery = new NftGallery(this.page);
  public assetPage = new AssetPage(this.page);
  public settingsModal = new SettingsModal(this.page);
  public onboarding = new OnboardingPage(this.page);
  public operationDrawer = new OperationDrawer(this.page);
  public liveApp = new LiveApp(this.page);
}
