import { AccountPage } from "./account.page";
import { AccountsPage } from "./accounts.page";
import { AnalyticsPage } from "./analytics.page";
import { AddAccountModal } from "./modal/add.account.modal";
import { AssetDrawer } from "./drawer/asset.drawer";
import { AssetPage } from "./asset.page";
import { BuyAndSellPage } from "./buyAndSell.page";
import { DelegateDrawer } from "./drawer/delegate.drawer";
import { DelegateModal } from "./modal/delegate.modal";
import { Drawer } from "tests/component/drawer.component";
import { EarnPage } from "./earn.dashboard.page";
import { Layout } from "tests/component/layout.component";
import { LedgerSyncDrawer } from "./drawer/ledger.sync.drawer";
import { LiveApp } from "./liveApp.page";
import { LockscreenPage } from "./lockscreen.page";
import { MarketPage } from "./market.page";
import { Modal } from "tests/component/modal.component";
import { ModularDrawer } from "./drawer/modular.drawer";
import { OnboardingPage } from "./onboarding.page";
import { OperationDrawer } from "./drawer/operation.drawer";
import { PageHolder } from "./abstractClasses";
import { PasswordlockModal } from "./modal/passwordlock.modal";
import { PortfolioPage } from "./portfolio.page";
import { ReceiveModal } from "./modal/receive.modal";
import { Redux } from "tests/utils/redux";
import { SendDrawer } from "./drawer/send.drawer";
import { SendModal } from "./modal/send.modal";
import { SettingsModal } from "./modal/settings.modal";
import { SettingsPage } from "./settings.page";
import { SpeculosPage } from "./speculos.page";
import { SwapConfirmationDrawer } from "./drawer/swap.confirmation.drawer";
import { SwapPage } from "./swap.page";
import { ModularScanAccountsDrawer } from "./drawer/modular.scan.accounts.drawer";
import { ModularDialog } from "./dialog/modular.dialog";
import { MarketBannerPage } from "./marketBanner.page";
import { FearAndGreedDialog } from "./dialog/fearGreed.dialog";
import { PrivateBalanceModal } from "./modal/private.balance.modal";
import { MainNavigationPage } from "./mainNavigation.page";

export class Application extends PageHolder {
  public account = new AccountPage(this.page);
  public accounts = new AccountsPage(this.page);
  public analytics = new AnalyticsPage(this.page);
  public addAccount = new AddAccountModal(this.page);
  public assetDrawer = new AssetDrawer(this.page);
  public assetPage = new AssetPage(this.page);
  public buyAndSell = new BuyAndSellPage(this.page, this.electronApp);
  public delegate = new DelegateModal(this.page);
  public delegateDrawer = new DelegateDrawer(this.page);
  public drawer = new Drawer(this.page);
  public earnDashboard = new EarnPage(this.page, this.electronApp);
  public layout = new Layout(this.page);
  public ledgerSync = new LedgerSyncDrawer(this.page);
  public liveApp = new LiveApp(this.page);
  public LockscreenPage = new LockscreenPage(this.page);
  public market = new MarketPage(this.page);
  public modal = new Modal(this.page);
  public modularDrawer = new ModularDrawer(this.page);
  public modularDialog = new ModularDialog(this.page);
  public scanAccountsDrawer = new ModularScanAccountsDrawer(this.page);
  public onboarding = new OnboardingPage(this.page);
  public operationDrawer = new OperationDrawer(this.page);
  public password = new PasswordlockModal(this.page);
  public portfolio = new PortfolioPage(this.page);
  public receive = new ReceiveModal(this.page);
  public privateBalance = new PrivateBalanceModal(this.page);
  public redux = new Redux(this.page);
  public send = new SendModal(this.page);
  public sendDrawer = new SendDrawer(this.page);
  public settings = new SettingsPage(this.page);
  public settingsModal = new SettingsModal(this.page);
  public speculos = new SpeculosPage(this.page);
  public swap = new SwapPage(this.page);
  public swapDrawer = new SwapConfirmationDrawer(this.page);
  public marketBanner = new MarketBannerPage(this.page);
  public fearAndGreedDialog = new FearAndGreedDialog(this.page);
  public mainNavigation = new MainNavigationPage(this.page);
}
