import { AccountPage } from "./account.page";
import { AccountsPage } from "./accounts.page";
import { AddAccountModal } from "./modal/add.account.modal";
import { AssetDrawer } from "./drawer/asset.drawer";
import { AssetPage } from "./asset.page";
import { BuyAndSellPage } from "./buyAndSell.page";
import { DelegateDrawer } from "./drawer/delegate.drawer";
import { DelegateModal } from "./modal/delegate.modal";
import { Drawer } from "../component/drawer.component";
import { EarnPage } from "./earn.dashboard.page";
import { Layout } from "../component/layout.component";
import { LedgerSyncDrawer } from "./drawer/ledger.sync.drawer";
import { LiveApp } from "./liveApp.page";
import { LockscreenPage } from "./lockscreen.page";
import { MarketPage } from "./market.page";
import { Modal } from "../component/modal.component";
import { ModularAccountDrawer } from "./drawer/modular.account.drawer";
import { ModularAssetDrawer } from "./drawer/modular.asset.drawer";
import { ModularNetworkDrawer } from "./drawer/modular.network.drawer";
import { NFTDrawer } from "./drawer/nft.drawer";
import { PageHolder } from "./abstractClasses";
import { SettingsPage } from "./settings.page";
import { SwapConfirmationDrawer } from "./drawer/swap.confirmation.drawer";
import { SwapPage } from "./swap.page";

export class Application extends PageHolder {
  public account = new AccountPage(this.page);
  public accounts = new AccountsPage(this.page);
  public addAccount = new AddAccountModal(this.page);
  public assetDrawer = new AssetDrawer(this.page);
  public assetPage = new AssetPage(this.page);
  public buyAndSell = new BuyAndSellPage(this.page, this.electronApp);
  public delegate = new DelegateModal(this.page);
  public delegateDrawer = new DelegateDrawer(this.page);
  public drawer = new Drawer(this.page);
  public earnDashboard = new EarnPage(this.page, this.electronApp);
  public layout = new Layout(this.page);
  public ledgerSync = new LedgerSyncDrawer(this.page);
  public liveApp = new LiveApp(this.page);
  public LockscreenPage = new LockscreenPage(this.page);
  public market = new MarketPage(this.page);
  public modal = new Modal(this.page);
  public modularAccountDrawer = new ModularAccountDrawer(this.page);
  public modularAssetDrawer = new ModularAssetDrawer(this.page);
  public modularNetworkDrawer = new ModularNetworkDrawer(this.page);
  public nftDrawer = new NFTDrawer(this.page);
  public settings = new SettingsPage(this.page);
  public swap = new SwapPage(this.page);
  public swapDrawer = new SwapConfirmationDrawer(this.page);
}
