import { TFunction } from "i18next";
import { BigNumber } from "bignumber.js";
import { Account, AccountLike, SignedOperation } from "@ledgerhq/types-live";
import { Device } from "@ledgerhq/live-common/hw/actions/types";
import { Step } from "~/renderer/components/Stepper";
import { HOOKS_TRACKING_LOCATIONS } from "~/renderer/analytics/hooks/variables";
export type StepId = "amount" | "summary" | "device" | "confirmation" | "warning";
export type StepProps = {
  t: TFunction;
  transitionTo: (a: string) => void;
  transaction: string;
  account: AccountLike;
  parentAccount: Account | undefined | null;
  device: Device | undefined | null;
  useApp?: string;
  dependencies?: string[];
  error: Error | undefined | null;
  warning: Error | undefined | null;
  closeModal: (a: void) => void;
  openModal: (b: string, a: unknown) => void;
  onChangeAccount: (b?: AccountLike | null, a?: Account | null) => void;
  onChangeTransaction: (a: Transaction) => void;
  onTransactionError: (a: Error) => void;
  onTransactionSigned: (a: SignedOperation) => void;
  onRetry: (a: void) => void;
  maybeRecipient?: string;
  onResetMaybeRecipient: () => void;
  maybeAmount?: BigNumber;
  onResetMaybeAmount: () => void;
  manifestId?: string;
  manifestName?: string;
  location?: HOOKS_TRACKING_LOCATIONS;
  broadcast?: boolean;
};
export type St = Step<StepId, StepProps>;
