import {
  CategoryContentCard,
  ContentCardsLayout,
  ContentCardsType,
  LandingPageStickyCtaContentCard,
  LandingPageUseCase,
} from "~/dynamicContent/types";
import { WidthFactor } from "~/contentCards/layouts/types";
import { ContentCard } from "@braze/react-native-sdk";

export const fakeCategoryContentCards: CategoryContentCard[] = [
  {
    id: "category1",
    categoryId: "offers",
    location: "LP_Generic" as LandingPageUseCase,
    createdAt: 1634310000,
    viewed: true,
    order: 1,
    carouselWidthFactor: WidthFactor.Full,
    gridWidthFactor: WidthFactor.Full,
    type: ContentCardsType.category,
    cardsLayout: ContentCardsLayout.unique,
    cardsType: ContentCardsType.bigSquare,
    title: "New Arrivals",
    description: "Check out the latest arrivals in our store.",
    cta: "Shop Now",
    link: "https://example.com/new-arrivals",
    isDismissable: true,
    hasPagination: true,
  },
  {
    id: "category2",
    categoryId: "offers",
    location: "LP_Generic" as LandingPageUseCase,
    createdAt: 1634310000,
    viewed: true,
    order: 2,
    carouselWidthFactor: WidthFactor.Full,
    gridWidthFactor: WidthFactor.Full,
    type: ContentCardsType.category,
    cardsLayout: ContentCardsLayout.unique,
    cardsType: ContentCardsType.bigSquare,
    title: "Nano X Accessories",
    description: "Check out the latest Nanox.",
    cta: "Get one",
    link: "https://example.com/new-arrivals",
    isDismissable: true,
    hasPagination: true,
  },
];

export const landingPageStickyCtaCard: LandingPageStickyCtaContentCard = {
  id: "stickyCta001",
  createdAt: 1634310000,
  viewed: false,
  cta: "Sign Up Now",
  link: "https://example.com/signup",
  landingPage: "LP_Generic" as LandingPageUseCase,
};

export const classicCards: ContentCard[] = [
  {
    id: "card1",
    created: 1690112400, // Example UNIX timestamp
    expiresAt: -1, // Never expires
    viewed: false,
    clicked: false,
    pinned: false,
    dismissed: false,
    dismissible: true,
    openURLInWebView: true,
    isControl: false,
    extras: { categoryId: "news", tag: "featured" },
    type: "Classic",
    image: "https://example.com/images/card1.jpg",
    title: "Breaking News",
    cardDescription: "Stay updated with the latest news from around the globe.",
    domain: "news.example.com",
    url: "https://news.example.com/breaking-news",
  },
  {
    id: "card2",
    created: 1690115400,
    expiresAt: 1700115400, // Example expiration timestamp
    viewed: true,
    clicked: true,
    pinned: false,
    dismissed: false,
    dismissible: false,
    openURLInWebView: false,
    isControl: false,
    extras: { categoryId: "events", priority: "high" },
    type: "Classic",
    image: "https://example.com/images/card2.jpg",
    title: "Upcoming Event",
    cardDescription: "Join us for the annual tech conference happening next week!",
    domain: "events.example.com",
    url: "https://events.example.com/conference",
  },
  {
    id: "card3",
    created: 1690118400,
    expiresAt: 1693123200, // Example expiration timestamp
    viewed: false,
    clicked: false,
    pinned: true,
    dismissed: false,
    dismissible: true,
    openURLInWebView: true,
    isControl: false,
    extras: { categoryId: "offers", discount: "20%" },
    type: "Classic",
    image: "https://example.com/images/card3.jpg",
    title: "Exclusive Offer",
    cardDescription: "Get 20% off on your first purchase. Limited time only!",
    domain: "shop.example.com",
    url: "https://shop.example.com/offer",
  },
];
