name: "[All Platforms] - Build and Test - Push"
on:
  push:
    branches:
      - main
      - develop
      - release
      - hotfix
      - support/skip-coverage-on-push

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # LLD
  build-desktop:
    name: "Build Desktop"
    uses: LedgerHQ/ledger-live/.github/workflows/build-desktop-reusable.yml@support/skip-coverage-on-push
    secrets: inherit

  test-desktop:
    name: "Desktop E2E & Mock Tests"
    uses: LedgerHQ/ledger-live/.github/workflows/test-desktop-reusable.yml@support/skip-coverage-on-push
    secrets: inherit

  codecheck-desktop:
    name: "Desktop Lint & Unit Tests"
    uses: LedgerHQ/ledger-live/.github/workflows/test-desktop-codechecks-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      coverage: false

  test-mobile:
    name: "Test Mobile"
    uses: LedgerHQ/ledger-live/.github/workflows/test-mobile-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      coverage: false

  build-test-mobile:
    name: "Build & Test Mobile"
    uses: LedgerHQ/ledger-live/.github/workflows/test-mobile-mock-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      macos-specificity-runner-label: "general-pool"
      skip-bundle-size-reporting: true
      max-shards: 2
      skip-pod-checks: "true"

  # Tests
  test-libraries:
    name: "Test Libraries"
    uses: LedgerHQ/ledger-live/.github/workflows/test-libs-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      coverage: false

  test-features:
    name: "Test Features"
    uses: LedgerHQ/ledger-live/.github/workflows/test-features-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      coverage: false

  test-design-system:
    name: "Test UI Libs"
    uses: LedgerHQ/ledger-live/.github/workflows/test-design-system-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      coverage: false

  build-web-tools:
    name: "Build Web Tools"
    uses: LedgerHQ/ledger-live/.github/workflows/build-web-tools-reusable.yml@support/skip-coverage-on-push
    secrets: inherit
    with:
      vercel-production: ${{ github.ref_name == 'develop' && 'true' || 'false' }}

  test-cli:
    name: "Test CLI"
    uses: LedgerHQ/ledger-live/.github/workflows/test-cli-reusable.yml@support/skip-coverage-on-push
    secrets: inherit

  build-wallet-cli:
    name: "Build Wallet CLI"
    uses: LedgerHQ/ledger-live/.github/workflows/build-wallet-cli-reusable.yml@support/skip-coverage-on-push
    secrets: inherit

  # Final Check required
  ok:
    name: "OK"
    needs:
      - build-desktop
      - test-desktop
      - codecheck-desktop
      - test-mobile
      - build-test-mobile
      - test-libraries
      - test-features
      - test-design-system
      - build-web-tools
      - test-cli
      - build-wallet-cli
    runs-on: ubuntu-22.04
    if: always() && !cancelled()
    steps:
      - name: Check result
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
