name: "[Release] - Rollback Version - Manual"

on:
  workflow_dispatch:
    inputs:
      application:
        description: "Application to create branch for (live-desktop or live-mobile)"
        required: true
        type: choice
        options:
          - live-desktop
          - live-mobile
      version-number:
        description: "Version number to restore"
        required: true
        type: string
      replacement-version-number:
        description: "Version number to replace"
        required: true
        type: string

permissions:
  contents: read

jobs:
  create-rollback:
    runs-on: ubuntu-24.04
    env:
      RELEASE_NOTES: "This release includes small security improvements and minor bug fixes."
      REPO: "ledger-live"
    steps:
      - name: Set environment variables
        run: |
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$APP_NAME@$APP_VERSION" >> $GITHUB_ENV
          echo "RESTORE_TAG=$APP_NAME@$RESTORE_VERSION" >> $GITHUB_ENV
        env:
          APP_NAME: ${{ inputs.application == 'live-desktop' && '@ledgerhq/live-desktop' || 'live-mobile' }}
          RESTORE_VERSION: ${{ inputs.version-number }}
          APP_VERSION: ${{ inputs.replacement-version-number }}

      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # 2.2.1
        with:
          app-id: ${{ secrets.GH_BOT_APP_ID }}
          private-key: ${{ secrets.GH_BOT_PRIVATE_KEY }}
          repositories: |
            ledger-live
            ledger-live-build

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: LedgerHQ/${{ env.REPO }}
          ref: refs/tags/${{ env.RESTORE_TAG }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup the caches
        uses: LedgerHQ/ledger-live/tools/actions/composites/setup-caches@develop
        with:
          install-proto: true

      - name: Install dependencies
        run: pnpm i -D -F "ledger-live" --ignore-scripts

      - name: Checkout rollback branch
        run: |
          git checkout -b rollback
          git push -u origin rollback

      - name: Override base version
        run: pnpm version --new-version ${{ inputs.replacement-version-number }} --no-git-tag-version
        working-directory: ${{ inputs.application == 'live-desktop' && 'apps/ledger-live-desktop' || 'apps/ledger-live-mobile' }}

      - name: Create version bump changeset
        run: |
          PACKAGE_NAME="${{ inputs.application == 'live-desktop' && 'ledger-live-desktop' || 'live-mobile' }}"
          echo "Creating changeset for $PACKAGE_NAME"
          echo -e "---\n\"$PACKAGE_NAME\": patch\n---\n\n${{ env.RELEASE_NOTES }}" > .changeset/rollback-bump.md

      - name: Apply changeset version bump
        run: pnpm changeset version

      - name: Get desktop version
        uses: LedgerHQ/ledger-live/tools/actions/get-package-infos@develop
        id: desktop-version
        with:
          path: ${{ github.workspace }}/apps/ledger-live-desktop

      - name: Get mobile version
        uses: LedgerHQ/ledger-live/tools/actions/get-package-infos@develop
        id: mobile-version
        with:
          path: ${{ github.workspace }}/apps/ledger-live-mobile

      - name: Update desktop release notes
        if: ${{ inputs.application == 'live-desktop' }}
        run: |
          {
            echo "# ${{ steps.desktop-version.outputs.version }}"
            echo
            echo "${{ env.RELEASE_NOTES }}"
            echo
            cat apps/ledger-live-desktop/RELEASE_NOTES.md
          } > apps/ledger-live-desktop/RELEASE_NOTES.md.tmp
          mv apps/ledger-live-desktop/RELEASE_NOTES.md.tmp apps/ledger-live-desktop/RELEASE_NOTES.md

      - name: Commit version bump
        uses: planetscale/ghcommit-action@v0.2.9
        with:
          commit_message: "chore(version): :package: patch bump for rollback [skip ci]"
          repo: ${{ github.repository }}
          branch: rollback
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Create new tag name
        id: new-tag
        run: |
          echo "tag-name=${{ env.APP_NAME }}@${{ inputs.application == 'live-desktop' && steps.desktop-version.outputs.version || steps.mobile-version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: '${{ env.REPO }}',
              target_commitish: 'rollback',
              tag_name: '${{ steps.new-tag.outputs.tag-name }}',
              name: `${{ steps.new-tag.outputs.tag-name }} Release`,
              body: `${{ env.RELEASE_NOTES }}`,
              prerelease: false,
              draft: false
            });

      - name: Delete rollback branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: '${{ env.REPO }}',
              ref: 'heads/rollback'
            });
            console.log('Successfully deleted rollback branch');

      - uses: actions/github-script@v7
        name: Trigger release build for desktop
        if: ${{ inputs.application == 'live-desktop' }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "ledgerhq",
              repo: "ledger-live-build",
              ref: "main",
              workflow_id: "release-desktop.yml",
              inputs: {
                branch: "tags/${{ steps.new-tag.outputs.tag-name }}"
              }
            });

      - uses: actions/github-script@v7
        name: Trigger release build for mobile
        if: ${{ inputs.application == 'live-mobile' }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "ledgerhq",
              repo: "ledger-live-build",
              ref: "main",
              workflow_id: "release-mobile.yml",
              inputs: {
                ref: "tags/${{ steps.new-tag.outputs.tag-name }}"
              }
            });
