name: "Just a test"
run-name: Just a test
permissions:
  contents: read
on:
  push:
    branches:
      - '**'

jobs:
  simple-test:
    runs-on: [ledger-live-4xlarge]
    steps:
      - name: Post to live-repo-health slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          method: chat.postMessage
          payload: |
            channel: "D084SJ8RDL5"
            text: "[Monitoring] Coin modules"
            blocks: 
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "✅️ *Coin modules monitoring success*"
