name: "[CI] - Stale Issues and PRs - Scheduled"
on:
  schedule:
    - cron: "20 4 * * *"

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@a20b814fb01b71def3bd6f56e7494d667ddf28da # v4
        with:
          ascending: true
          operations-per-run: 200
          days-before-close: 7
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove the Stale label or comment, otherwise it will be closed in 7 days."
          days-before-issue-stale: 30
          stale-pr-message: "There has been no activity on this PR for the last 15 days. Remove the Stale label or comment, otherwise it will be closed in 7 days."
          days-before-pr-stale: 15
