name: "[Shared] - Test - Called"

on:
  workflow_call:
    outputs:
      coverage_generated:
        value: ${{ jobs.test-shared.outputs.coverage_generated }}

  workflow_dispatch:
    inputs:
      ref:
        description: |
          If you run this manually, and want to run on a PR, the correct ref should be refs/pull/{PR_NUMBER}/merge to
          have the "normal" scenario involving checking out a merge commit between your branch and the base branch.
          If you want to run only on a branch or specific commit, you can use either the sha or the branch name instead (prefer the first version for PRs).
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  test-shared:
    name: "Shared Test"
    timeout-minutes: 10
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
      FORCE_COLOR: 3
      CI_OS: ubuntu-22.04
    outputs:
      coverage_generated: ${{ contains(steps.generate_coverage.outcome, 'success') }}

    runs-on: [ledger-live-linux-8CPU-32RAM]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Setup the caches
        uses: LedgerHQ/ledger-live/tools/actions/composites/setup-caches@develop
        id: setup-caches
        with:
          use-mise: true
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          cache-develop-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_DEVELOP }}
          cache-branch-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_BRANCH }}
          nx-key: ${{ secrets.NX_KEY }}
          accountId: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          roleName: ${{ secrets.AWS_CACHE_ROLE_NAME }}
          region: ${{ secrets.AWS_CACHE_REGION }}

      - name: Install dependencies
        run: pnpm i --filter="./shared/**"

      - name: Run coverage on shared packages
        run: |
          mkdir -p ${{ github.workspace }}/coverage
          touch ${{ github.workspace }}/coverage/lcov.info
          touch ${{ github.workspace }}/coverage/sonar-executionTests-report.xml

          pnpm exec nx run-many -t coverage --projects=tag:scope:shared --parallel=4 -- --runInBand=1

      - name: Process coverage files
        id: process-coverage
        run: |
          for package_json in $(find ./shared -name "package.json" -not -path "*/node_modules/*"); do
            pkg=$(dirname "$package_json")
            echo "Processing package at path: $pkg"
            if [ -f "$package_json" ] && jq -e '.scripts.coverage' "$package_json" > /dev/null 2>&1; then
              if [ -f "$pkg/coverage/lcov.info" ] && [ -f "$pkg/coverage/sonar-executionTests-report.xml" ]; then
                echo "Appending coverage files for $pkg"
                cat "$pkg/coverage/lcov.info" >> ${{ github.workspace }}/coverage/lcov.info
                cat "$pkg/coverage/sonar-executionTests-report.xml" >> ${{ github.workspace }}/coverage/sonar-executionTests-report.xml
              fi
            else
              echo "No coverage script found for $pkg, skipping."
            fi
          done
        shell: bash

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ !cancelled() }}
        id: generate_coverage
        with:
          name: coverage-shared
          path: ${{ github.workspace }}/coverage
