name: "[CI] - Repo Scripts Unit Tests - PR"

on:
  pull_request:
    branches-ignore:
      - "smartling-content-updated**"
      - "smartling-translation-completed**"
    paths:
      - "scripts/**"
      - "tools/actions/composites/get-failed-tests-summary/**"
      - ".github/workflows/test-scripts.yml"

concurrency:
  group: ci-scripts-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-scripts:
    name: "Repo scripts unit tests"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@v4
        with:
          node-version: 24.14.0
      - name: Run repo scripts unit tests
        run: node --test "scripts/**/*.test.mjs"

