name: "[Common] - Integration - Weekly (flaky network tests)"

on:
  schedule:
    - cron: "20 9 * * 1" # Mondays 09:20 UTC
  workflow_dispatch:
    inputs:
      ref:
        description: "Which ref (branch or tag) to pull from ?"
        required: false
        default: develop

permissions:
  id-token: write
  contents: read

jobs:
  integration-tests:
    name: "Integration Tests"
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
      FORCE_COLOR: 3
      CI_OS: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: ${{ inputs.ref || github.sha }}
      - name: Setup the caches
        uses: LedgerHQ/ledger-live/tools/actions/composites/setup-caches@develop
        id: setup-caches
        with:
          use-mise: true
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          cache-develop-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_DEVELOP }}
          cache-branch-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_BRANCH }}
          nx-key: ${{ secrets.NX_KEY }}
          accountId: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          roleName: ${{ secrets.AWS_CACHE_ROLE_NAME }}
          region: ${{ secrets.AWS_CACHE_REGION }}
      - name: Install dependencies
        run: pnpm i --filter="live-common..." --filter="ledger-live"
      - name: Build
        run: pnpm exec nx run @ledgerhq/live-common:build
      - name: Test
        shell: bash
        env:
          VERBOSE_FILE: logs.txt
        run: |
          pnpm common ci-test-integration-weekly
          git diff --exit-code libs/ledger-live-common/src
      - name: (On Failure) Upload live-common snapshots and source
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: ${{ format('live-common-src-{0}', matrix.os) }}
          path: |
            libs/ledger-live-common/src
      - name: (On Failure) Upload logs
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: logs.txt
          path: logs.txt

  integ-tests-fail:
    name: failure report
    needs: integration-tests
    if: failure() && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Post to coin-integration-private slack channel
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          method: chat.postMessage
          payload: |
            channel: "C06RTDKT324"
            text: "[Test] Weekly integration"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "❌ *Weekly integration tests failed*"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow run>"
