name: "[Desktop] E2E Lint & Typecheck - Called"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-desktop-e2e-lint:
    name: "Desktop E2E Lint & Typecheck"
    runs-on: ubuntu-22.04
    env:
      NODE_OPTIONS: "--max-old-space-size=7168"
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup the caches
        uses: LedgerHQ/ledger-live/tools/actions/composites/setup-caches@develop
        id: setup-caches
        with:
          use-mise: true
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          skip-turbo-cache: "true"
          cache-develop-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_DEVELOP }}
          cache-branch-role-arn: ${{ secrets.AWS_CACHE_OIDC_ROLE_ARN_BRANCH }}
          nx-key: ${{ secrets.NX_KEY }}
          accountId: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          roleName: ${{ secrets.AWS_CACHE_ROLE_NAME }}
          region: ${{ secrets.AWS_CACHE_REGION }}

      - name: Install dependencies
        run: pnpm i --filter="ledger-live-desktop-e2e-tests..." --filter="ledger-live-desktop..." --no-frozen-lockfile --unsafe-perm

      - name: Run lint and typecheck
        run: pnpm exec nx run-many -t lint,typecheck --projects=ledger-live-desktop-e2e-tests
