name: "[Mobile] - E2E Test - Scheduled/Called"

on:
  workflow_dispatch:
    inputs:
      coin_app:
        description: Coin application to run
        required: true
        type: string
      coin_app_version:
        description: The version of the coin application
        required: true
        type: string
      device:
        description: The device to emulate (nanox, nanos, nanos+, flex, stax)
        required: true
        type: string
      device_os_version:
        description: The version of the device OS
        required: true
        type: string
      additional_args:
        description: Additional arguments for speculos
        required: false
        type: string
      cluster:
        description: Cluster where to launch the speculos instance
        required: true
        type: string
      aws_role:
        description: AWS role to assume
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  start-speculos:
    name: Start Speculos
    uses: ledgerhq/actions/.github/workflows/start-speculos.yml@zheker
    with:
      coin_app: ${{ inputs.coin_app }}
      coin_app_version: ${{ inputs.coin_app_version }}
      device: ${{ inputs.device }}
      device_os_version: ${{ inputs.device_os_version }}
      aws_role: ${{ inputs.aws_role }}
      additional_args: ${{ inputs.additional_args }}
      cluster: ${{ inputs.cluster }}

  stop-speculos:
    name: Stop Speculos
    needs: [start-speculos]
    if: always()
    uses: ledgerhq/actions/.github/workflows/stop-speculos.yml@main
    with:
      aws_role: ${{ inputs.aws_role }}
      run_id: ${{ needs.start-speculos.outputs.run_id }}
      cluster: ${{ inputs.cluster }}
