import Changelly from "./Changelly";
import Cic from "./Cic";
import Coinify from "./Coinify";
import CoinifySquare from "./CoinifySquare";
import MoonPay from "./MoonPay";
import Oneinch from "./Oneinch";
import Paraswap from "./Paraswap";
import Wyre from "./Wyre";
import FTXLogo from "./FTX";
const FTX = FTXLogo();
const FTXUS = FTXLogo(true);
export { Changelly, Cic, Coinify, CoinifySquare, MoonPay, Oneinch, Paraswap, Wyre, FTX, FTXUS };
